### ISSUE TITLE
Couldn't run in the Windows11, but Win10 works

### ISSUE THREAD

**Issue by sky5454** [iced-rs/iced#1009]
the iced native couldn't run in the Win11 ?
the source is download from https://github.com/hecrj/iced/tree/master/examples/counter
and compiled in my Win11, but while running:
```ps
PS D:\0Download\counter\target\debug> .\counter.exe
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `-2005270523`,
 right: `0`: error on command list creation: 887a0005', D:\CARGO_HOME\registry\src\mirrors.ustc.edu.cn-12df342d903acd47\gfx-backend-dx12-0.7.1\src\pool.rs:105:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```
and it can run in Win10 while compiled in Win11.

**Comment by hecrj** [comment]
- Is the issue present in all of the examples? For instance, try `game_of_life` which should choose your high performance GPU.
- Is the issue present in [the `wgpu` examples]? If yes, then please report the issue there!

Closing this for now, as it seems like a hardware compatibility issue. Feel free to reopen if there is further evidence that something is wrong with `iced` itself.

[the `wgpu` examples]: https://github.com/gfx-rs/wgpu/tree/master/wgpu/examples
