### ISSUE TITLE
Text not rendering

### ISSUE THREAD

**Issue by mqudsi** [iced-rs/iced#1013]
On Ubuntu 18.04 and using the default configuration, iced runs and renders shapes/paths but does not render any text. I have not done any debugging.

The following screenshot was taking by `cd`ing into `examples/tour` and executing `cargo run` then clicking the button (which had no text) once:

![Screenshot from 2021-08-27 15-32-51@2x](https://user-images.githubusercontent.com/606923/131185456-b63b50fd-a9cc-4f3c-9d72-c2b02b5f497f.png)

No errors are logged to the console during execution. Please let me know what additional information I can provide.

**Comment by hecrj** [comment]
Could you try [the `wgpu_glyph` examples](https://github.com/hecrj/wgpu_glyph/tree/master/examples) and provide some more information about your hardware (e.g. GPU, driver, backend used, etc.)?

**Comment by ZakisM** [comment]
So I think i am getting a similar issue, one of my users who is using a GTX 1650 is facing an issue where some of the texts in a list are missing - I cannot see anything in logs which points to why this is happening, please see this image:

![image](https://user-images.githubusercontent.com/8143258/132985089-170d8a2c-3a69-4357-8999-9dc9c37b2078.png)

The "Element" on the right under "Current Parts (8/63)" is missing, as well as on the left in the "Available Parts" tab.

However, on my machine and other machines with the exact same interface:

![image](https://user-images.githubusercontent.com/8143258/132985602-bc2385e7-1f77-484e-926a-833cdfc66b1e.png)

There is no text missing.

For reference I am using a forked version of Iced that is in sync with master (#74d5589) with some extra components - but I have not modified any of the button element code: https://github.com/ZakisM/iced/tree/bl3_save_edit

Do you think it's an issue with my code or is it related to this issue #1013?

Thanks,

Zak

**Comment by hecrj** [comment]
@ZakisM Most likely a driver or `wgpu` issue. My previous comment still applies here!

**Comment by ZakisM** [comment]
Thanks will try to get them to run the example and see if I can get more hardware info from them.

**Comment by ZakisM** [comment]
@hecrj I haven't been able to contact the user yet, however, I implemented a feature to change the `scale_factor` as part of another request, this just changes the value provided to the `Application` trait under the function: `fn scale_factor(&self) -> f64 {`.

With the scale set to `1.0` everything looks fine.

With the scale set to any of these values: `1.30, 1.60, 1.85, 0.80, 0.65`. I can see the same issue:

![image](https://user-images.githubusercontent.com/8143258/133239450-05d05740-ad36-4b8f-811e-b0f41ae8e412.png)

I'm assuming this is related to the issue one of my users was having - perhaps his screen resolution was affecting the scale of the UI and he was seeing the same issue?

**Comment by ZakisM** [comment]
@hecrj I believe I have nailed down the issue, so to create the appearance of a margin I was adding a space before the text (a bit of a hack), using something like this:

`Text::new(format!("{:width$}{}", " ", label, width = margin));`

It just adds a blank space before the start of the text.

Removing this space before the start of the text fixes the issue from the screenshot above:

![image](https://user-images.githubusercontent.com/8143258/133244676-a658a197-7803-407c-b590-949c324a5ba8.png)

**Comment by hecrj** [comment]
@ZakisM I see. This is most likely related to #782.

**Comment by ZakisM** [comment]
@hecrj Hmm seems to be the case

**Comment by hecrj** [comment]
Closing as the original issue seems to be a hardware compatibility issue with `wgpu`.

If the issue persists:

- Is the issue present in all of the examples? For instance, try `game_of_life` which should choose your high performance GPU.
- Is the issue present in [the `wgpu` examples]? If yes, then please report the issue there!

**Comment by williameliasson-dev** [comment]
Using a nerd font caused this for me, just in case anyone runs into the same issue.
