### ISSUE TITLE
How do I stretch an image

### ISSUE THREAD

**Issue by foodornt** [iced-rs/iced#1014]
I want to create an image without keeping the aspect ratio

is that possible with iced

**Comment by yusdacra** [comment]
Simplest way would be to resize the image with the `image` crate and store the resulting image in memory as a `Handle::Pixel`. I'm sure you could modify the `Image` widget to not respect the aspect ratio, but I didn't look into that.

**Comment by foodornt** [comment]
Excellent, thank you!

**Comment by hecrj** [comment]
I think we could replicate the new logic of the `image::Viewer` introduced in #885. I'll look into it!
