### ISSUE TITLE
Feature request: support for Trunk, or sycamore alongside dodrio for WebAssembly?

### ISSUE THREAD

**Issue by marek-lach** [iced-rs/iced#1017]
It could be useful for Web UIs: https://github.com/thedodd/trunk
also https://github.com/sycamore-rs/sycamore ?

**Comment by madmaxio** [comment]
Very good call, is that library ok for dodrio replacement?

**Comment by hecrj** [comment]
`trunk` looks great! I'd be okay with updating the `README` of `iced_web` to suggest using `trunk` (see #1161).

When it comes to `sycamore`, I tried to explain a bit why I think it'd wouldn't work well in https://github.com/iced-rs/iced/issues/1126#issuecomment-1008236470

I'm closing this issue in favor of both of these I mentioned!
