### ISSUE TITLE
Toolbar window

### ISSUE THREAD

**Issue by TimUntersberger** [iced-rs/iced#1023]
I am currently trying to rewrite the appbar of one of my projects to use iced instead of winapi and I need the window to not show up in the `Window Switcher` of Windows 10. Right now i just modify the window styles using winapi, but I can't access the HWND of the created window so I can't do that anymore.

I read in https://github.com/hecrj/iced/issues/822 that you don't want to expose the window handle, so I would like some guidance on where I should/could add this and whether you even want something like this in the project.

**Comment by hecrj** [comment]
For this kind of niche use case, I recommend you to directly rely on the `iced_native` crate and write your own event loop, which will give you complete control over your window! [The `integration_wgpu` example](https://github.com/iced-rs/iced/tree/4aa943cbc63230dfcb995c469ceec9f74e6132e1/examples/integration_wgpu/src) can be a good starting point.
