### ISSUE TITLE
Is this very minimal the bloat you get compared to other GUI libraries?

### ISSUE THREAD

**Issue by Joe23232** [iced-rs/iced#1034]
Hey guys just curious is this very lightweight and minimal the amount of bloat you get if using `iced` as compared to something such as `gtk` and/or `qt`?

**Comment by dhardy** [comment]
Try building a binary with release optimisations, stripping, and checking the size. My finding is that `wgpu` in particular is quite large.

GTK and QT can "cheat": they use shared system libraries. Great for Linux distributions or if you can ensure users have the right libs installed from source, less good if you want to ship a *complete* application (e.g. a [flatpack](https://www.flatpak.org/)).

**Comment by sourcebox** [comment]
Lightweight is a relative term, but I can say that it's lightweight enough for me. I did [this application](https://github.com/sourcebox/tooro-editor) with `iced` and it resulted in images/installer of around 1MB for Windows/Mac as you can see [here](https://github.com/sourcebox/tooro-editor/releases/tag/release-1.0.0). I know that the files there are compressed, but the overall size is really acceptable, even if my application is not very sophisticated.

**Comment by Joe23232** [comment]
> Try building a binary with release optimisations, stripping, and checking the size. My finding is that `wgpu` in particular is quite large.
> 
> GTK and QT can "cheat": they use shared system libraries. Great for Linux distributions or if you can ensure users have the right libs installed from source, less good if you want to ship a _complete_ application (e.g. a [flatpack](https://www.flatpak.org/)).



Right I see thanks mate

**Comment by Joe23232** [comment]
@sourcebox 

> Lightweight is a relative term, but I can say that it's lightweight enough for me. I did this application with iced and it resulted in images/installer of around 1MB for Windows/Mac as you can see here. 

I gotta say, it looks really nice mate. And that is good mate.

**Comment by Kaiden42** [comment]
You can use [`cargo bloat`](https://github.com/RazrFalcon/cargo-bloat) to analyze the size of each dependency you are using. I've analyzed my current project and it confirms that wgpu takes a lot of space, but it's less than the std crate.

```
cargo bloat --release --crates
    Finished release [optimized] target(s) in 0.17s
    Analyzing target/release/my-application

 File  .text     Size Crate
 6.9%  16.1%   1.4MiB std
 5.9%  13.7%   1.2MiB wgpu
 3.3%   7.8% 682.6KiB spirv_cross
 2.8%   6.4% 567.5KiB my_gui
 2.4%   5.7% 501.8KiB inplace_it
 1.8%   4.1% 365.3KiB wgpu_core
 1.7%   4.0% 354.2KiB naga
 1.7%   3.9% 340.7KiB iced_wgpu
 1.4%   3.3% 287.4KiB winit
 1.3%   3.1% 271.0KiB smithay_client_toolkit
 0.9%   2.2% 191.2KiB wgpu_glyph
 0.9%   2.2% 189.5KiB my_core
 0.8%   2.0% 173.8KiB gfx_backend_gl
 0.8%   1.9% 165.6KiB ttf_parser
 0.8%   1.8% 158.7KiB wayland_client
 0.7%   1.6% 137.7KiB wayland_protocols
 0.6%   1.4% 120.3KiB smithay_clipboard
 0.6%   1.3% 117.0KiB iced_native
 0.5%   1.2% 109.8KiB [Unknown]
 0.5%   1.2% 108.6KiB hashbrown
 5.5%  12.9%   1.1MiB And 120 more crates. Use -n N to show more.
42.8% 100.0%   8.6MiB .text section size, the file size is 20.1MiB

Note: numbers above are a result of guesswork. They are not 100% correct and never will be.
```

**Comment by dhardy** [comment]
> but it's less than the std crate.

`wgpu_core` and `naga` are "part of" WGPU, and `spirv_cross` is an (optional) dependency, so you're wrong.

> 42.8% 100.0%   8.6MiB .text section size, the file size is 20.1MiB

This line is *exactly* the same result I get when running this on the KAS `gallery` example. Weird. (And I don't think I'm even using the same `wgpu` version since the size is quite different.)
