### ISSUE TITLE
Rendering images on high-density/retina displays

### ISSUE THREAD

**Issue by captbaritone** [iced-rs/iced#1036]
I'm experimenting with an app that builds its UI out of raster sprites using `iced::widget::image::Image`. On high density displays (such as a macbook pro) this results in blurry looking UI because my image ends up getting upscaled, presumably using an algorithm that's optimized for photos and not pixel art. Is there some way to control how this scaling is performed? Or perhaps a way to detect the current display's pixel density and a way to define an image which is given in screen pixels and not display pixels? In that world, I could do the upscaling myself.

For context, in the browser, this problem can be addressed using the [`image-rendering`](https://developer.mozilla.org/en-US/docs/Web/CSS/image-rendering) CSS property.

You can zoom into this image to see the blur:

<img width="387" alt="Screen Shot 2021-09-10 at 9 53 27 AM" src="https://user-images.githubusercontent.com/162735/132891608-f1710feb-696a-4cfb-be18-448e49dec8f6.png">

**Comment by hecrj** [comment]
Closing in favor #557.
