### ISSUE TITLE
not compiling on Mac, unresolved import super::dx12

### ISSUE THREAD

**Issue by DavidBJaffe** [iced-rs/iced#1042]
I tried updating `iced` to `93fec8d273ef8305e1c2456abe0c8ecd7a9d9407` (Sept. 13).  When I run `cargo b` in the `iced` crate, it compiles, however when I try to compile my own code, I get this error:

```
error: DX12 API enabled on non-Windows OS. If your project is not using resolver="2" in Cargo.toml, it should.
  --> /Users/david.jaffe/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.10.6/src/lib.rs:47:1
   |
47 | compile_error!("DX12 API enabled on non-Windows OS. If your project is not using resolver=\"2\" in Cargo.toml, it should.");
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0432]: unresolved import `super::dx12`
  --> /Users/david.jaffe/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-hal-0.10.6/src/lib.rs:62:20
   |
62 |     pub use super::dx12::Api as Dx12;
   |                    ^^^^ could not find `dx12` in the crate root
```

This is on a Mac.  I tried `cargo update` but that did not resolve the problem.  I also tried lowering the version of `wgpu-hal` to 0.10.3.  Any ideas?

**Comment by TimUntersberger** [comment]
> If your project is not using resolver=\"2\" in Cargo.toml, it should.

Is your project using workspaces? If so did you add `resolver="2"` to the root `Cargo.toml`?

**Comment by DavidBJaffe** [comment]
Figured it out.  I had thought that resolver="2" was referring to a crate called resolver.  It is not.  It is referring to a directive that one puts in one's Cargo.toml.
