### ISSUE TITLE
Am I able to make very custom widgets?

### ISSUE THREAD

**Issue by Joe23232** [iced-rs/iced#1045]
Am I able to make these kinds of widgets?

![Desktop](https://user-images.githubusercontent.com/34926497/133364297-6922599b-1033-44c2-b4f2-3dacadcb8147.png)

**Comment by Kaiden42** [comment]
Could you provide more informations about this? So yes, you can draw things on the screen :wink: but what do you want to achieve with these widgets?

Not everything needs to be a whole new widget. You can probably use the existing widgets for nearly all of the things on the screenshot. All of the horizontally aligned bars can be easily build with the `Row` widget or you could draw them using a `Canvas`.

I've build something similar in my current project using only one `Row` with five `Containers`, each containing a `Space`. The containers have a different background color based on the calculated value.
![Bildschirmfoto vom 2021-09-17 18-21-46](https://user-images.githubusercontent.com/26521388/133821620-b36d82b3-dbef-4850-b732-a1a7599ac607.png)

**Comment by Joe23232** [comment]
> Could you provide more informations about this? So yes, you can draw things on the screen wink but what do you want to achieve with these widgets?

With a tiling window manager I want to put these kinds of widgets that will tell the CPU usage per core etc. :)  Can this be used on wayland?

> Not everything needs to be a whole new widget. You can probably use the existing widgets for nearly all of the things on the screenshot. All of the horizontally aligned bars can be easily build with the Row widget or you could draw them using a Canvas.

What about the triangles you see up at the top left hand side mate?

> I've build something similar in my current project using only one Row with five Containers, each containing a Space. The containers have a different background color based on the calculated value.


Looks nice mate, it does mate =D

**Comment by Kaiden42** [comment]
> Can this be used on wayland?

I would recommend to try out the examples. Especially the tour as they show most of the widgets of iced and the solar_system as this is using a canvas. If they work, everything else should work.

> What about the triangles you see up at the top left hand side mate?

For this, you can simply use a canvas or when a widget is needed you could draw them with an image/svg or you could try the Mesh2D [primitive]([primitives](https://github.com/iced-rs/iced/blob/master/graphics/src/primitive.rs)).

It is also possible to use a canvas inside a widget. The [color picker](https://github.com/iced-rs/iced_aw#color-picker) is a good example for this.

> Is this kinda like processing in regards to how I draw shapes?

It is the more easy way, but you could also use a Mesh2D of the primitives, a widget can use, to draw things.

> Looks nice mate, it does mate =D

Thanks! :smile: When using some padding/spacing, more containers in the row and a different color, it could look like the horizontal bars on your image.

**Comment by Joe23232** [comment]
> I would recommend to try out the examples. Especially the tour as they show most of the widgets of iced and the solar_system as this is using a canvas. If they work, everything else should work.

Do you like make the background of the widgets transparent?

> It is also possible to use a canvas inside a widget. The color picker is a good example for this.

Very interesting mate.

> It is the more easy way, but you could also use a Mesh2D of the primitives, a widget can use, to draw things.

Is Mesh2D a drawing tool for iced?

> Thanks! smile When using some padding/spacing, more containers in the row and a different color, it could look like the horizontal bars on your image.

No worries and I understand :)
