### ISSUE TITLE
iced cannot run beacause of MESA?

### ISSUE THREAD

**Issue by PeterlitsZo** [iced-rs/iced#1048]
This is a simple example:

<details>
<summary>
<code>src/main.rs</code>
</summary>

``` rust
use iced::{Element, Sandbox, Settings, Text};

pub fn main() -> iced::Result {
    Counter::run(Settings::default())
}

#[derive(Default)]
struct Counter { }

#[derive(Debug, Clone, Copy)]
enum Message { }

impl Sandbox for Counter {
    type Message = Message;

    fn new() -> Self { Self::default() }

    fn title(&self) -> String {
        String::from("QR-code")
    }

    fn update(&mut self, _message: Message) { }

    fn view(&mut self) -> Element<Message> {
        Text::new("Hello?").into()
    }
}
```

</details>

And configure:

<details>
<summary>
<code>Cargo.toml</code>
</summary>

``` rust
[package]
name = "qr-code"
version = "0.1.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
iced = "0.3"
```

</details>

This is the screenshot:
![image](https://user-images.githubusercontent.com/25707198/133633372-332f4849-8b5f-4f4f-9927-3367abb89bc6.png)

And also in the shell, error raise:
```
$ cargo run
Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/qr-code`
     INTEL-MESA: warning: Performance support disabled, consider sysctl
     dev.i915.perf_stream_paranoid=0

     thread 'main' panicked at 'Next frame: Timeout',
     /home/peterlits/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_wgpu-0.4.0/src/window/compositor.rs:126:52
     note: run with `RUST_BACKTRACE=1` environment variable to display a
     backtrace
     [1]    51786 segmentation fault (core dumped)  cargo run
```

**Comment by PeterlitsZo** [comment]
It close auto. I am not sure what is MESA and how to solve it.

**Comment by PeterlitsZo** [comment]
But I can run the examples in this project. I notice that:
``` toml
iced = { path = "../.." }
```
in the `Cargo.toml` but I just use `"0.3"`..

**Comment by PeterlitsZo** [comment]
By the way, I find that when I run command `cargo run --package clock` in `examples/clock`, it raise error:
```
error: failed to select a version for `wasm-bindgen`.
    ... required by package `wgpu v0.7.0`
    ... which is depended on by `iced_wgpu v0.4.0`
    ... which is depended on by `iced v0.3.0`
    ... which is depended on by `counter v0.1.0 (/tmp/iced/examples/counter)`
versions that meet the requirements `=0.2.69` are: 0.2.69

all possible versions conflict with previously selected packages.

  previously selected package `wasm-bindgen v0.2.78`
    ... which is depended on by `dodrio v0.2.0`
    ... which is depended on by `iced_web v0.4.0 (/tmp/iced/web)`
    ... which is depended on by `iced v0.3.0 (/tmp/iced)`
    ... which is depended on by `bezier_tool v0.1.0 (/tmp/iced/examples/bezier_tool)`

failed to select a version for `wasm-bindgen` which could resolve this conflict
```

Oh no, I forget how to run the example successly!

**Comment by PossiblyAShrub** [comment]
With your first issue, that looks like a `wgpu` bug. If you are able to run the examples after cloning the repository then this issue likely has been resolved. This means that you will want to use `iced` as a git dependency in order to make sure you are using the fixed version:

```toml
# Cargo.toml
[package]
name = "qr-code"
version = "0.1.0"
edition = "2018"

[dependencies]
iced = { git = "https://github.com/iced-rs/iced" }
```

For the second issue, try: 
 - running `git pull && cargo upgrade` before rebuilding the example or
 - re-cloning the repository (`rm -r iced && git clone https://github.com/iced-rs/iced`)

**Comment by hecrj** [comment]
- Is the issue present in all of the examples? For instance, try `game_of_life` which should choose your high performance GPU.
- Is the issue present in [the `wgpu` examples]? If yes, then please report the issue there!

Closing this for now, as it seems like a hardware compatibility issue. Feel free to reopen if there is further evidence that something is wrong with `iced` itself.

[the `wgpu` examples]: https://github.com/gfx-rs/wgpu/tree/master/wgpu/examples

**Comment by PeterlitsZo** [comment]
I am not sure weather the bug is still here or not.

I have already change my OS. Sorry. Thanks for your kindly reply and it really help.
