### ISSUE TITLE
resvg dependency update

### ISSUE THREAD

**Issue by 0x192** [iced-rs/iced#1052]
It would be nice to have an updated version of [resvg](https://github.com/RazrFalcon/resvg/blob/master/CHANGELOG.md) (especially because it would fix an issue I encounter).

I've tried to make `iced_wgpu` compatible with `resvg v0.18` as there are some breaking changes but I guess I'm not skilled enough for this task.

I managed to make it compile but it's clearly broken ([no svg display on screen](https://github.com/0x192/iced/tree/master/examples/svg)) => [my fork](https://github.com/0x192/iced)

Can someone have a look? It may be easy to fix. I didn't open a pull request but I can open a draft if someone want to help me on this.

**Comment by hecrj** [comment]
I gave a shot at this in #1060.

It seems to work for me. Let me know!

**Comment by 0x192** [comment]
It works for me too! Thanks @hecrj!
