### ISSUE TITLE
iced_wgpu: wgpu dependency is outdated

### ISSUE THREAD

**Issue by Consoli0** [iced-rs/iced#1053]
The dependency of wgpu in iced_wgpu is using 0.7.1 instead of 0.10.2, causing a problem to occur.

See https://github.com/zakarumych/gpu-alloc/issues/56.

**Comment by yusdacra** [comment]
`iced-wgpu` on `master` branch uses `wgpu 0.10`. There hasn't yet been a release that includes it. You can change your `iced` dependency to point to the git `master` branch instead of using the `crates.io` version.

**Comment by Consoli0** [comment]
I see.
