### ISSUE TITLE
How to add an icon in the input_text

### ISSUE THREAD

**Issue by push-and-pop** [iced-rs/iced#1055]
like this
![image](https://user-images.githubusercontent.com/80676432/134791441-1c0d7704-5fc5-4aa6-9497-ef17a3d65557.png)

thank your help

**Comment by yusdacra** [comment]
You can use the [icons from iced_aw](https://github.com/iced-rs/iced_aw#bootstrap-icons), and use the `Row` widget to put an icon before your text input.

Example (might not compile):
```rust
let icon = Text::new(Icon::Lock);
let text_input = /* create text input */;
let row = Row::with_children(vec![icon.into(), text_input.into()]);
```

**Comment by push-and-pop** [comment]
thank you
