### ISSUE TITLE
Delay when resizing

### ISSUE THREAD

**Issue by Diggsey** [iced-rs/iced#1086]
This on windows 10 compiled in release mode.

I created the following simple application:
```rust

struct App;

impl Application for App {
    type Executor = iced::executor::Default;

    type Message = ();

    type Flags = ();

    fn new(flags: Self::Flags) -> (Self, iced::Command<Self::Message>) {
        (Self, iced::Command::none())
    }

    fn title(&self) -> String {
        "Hello, world!".into()
    }

    fn update(
        &mut self,
        message: Self::Message,
        clipboard: &mut iced::Clipboard,
    ) -> iced::Command<Self::Message> {
        iced::Command::none()
    }

    fn view(&mut self) -> iced::Element<'_, Self::Message> {
        iced::Text::new("Hello, world!").into()
    }
}
```

When resizing by dragging the window border, there is a very noticeable delay (about 500ms) between moving the mouse and the window resizing.

**Comment by Diggsey** [comment]
This appears to be much less of an issue when the `glow` renderer is used.

**Comment by hecrj** [comment]
- Is the issue present in all of the examples? For instance, try `game_of_life` which should choose your high performance GPU.
- Is the issue present in [the `wgpu` examples]? If yes, then please report the issue there!

Closing this for now, as it seems like a hardware compatibility issue. Feel free to reopen if there is further evidence that something is wrong with `iced` itself.

[the `wgpu` examples]: https://github.com/gfx-rs/wgpu/tree/master/wgpu/examples
