### ISSUE TITLE
Image is black

### ISSUE THREAD

**Issue by YXL76** [iced-rs/iced#1103]
I run the example.

```
cargo run --package tour
```

The image is black. And it took a long time to  jump to this page.

![image](https://user-images.githubusercontent.com/43405544/139293507-7e8eaa9c-e7f2-4ca1-bb3a-0a5273fba553.png)

OS: Arch Linux x86_64
Kernel: 5.11.2-zen1-1-zen

**Comment by hecrj** [comment]
Could you provide a bit more information about your environment (e.g. GPU, drivers...)?

> And it took a long time to jump to this page.

In `debug` mode, the image takes a while to load. Try compiling with the `--release` flag!

**Comment by oknozor** [comment]
FYI I had the exact same problem this morning, I rebooted and now image is fine (no compilation in between). Just a guess but this might be related to some power saving feature in mesa ? 
Using the following hardware  :
- Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 14 [Radeon RX 5500/5500M / Pro 5500M] (rev c1)
- VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Renoir (rev c7)

**Comment by YXL76** [comment]
I use [optimus-manager](https://github.com/Askannz/optimus-manager) to switch to the Nvidia GPU. It works fine. I think this should be the problem of Intel GPU driver.

My GPU info:

```shell
lshw -numeric -C display
  *-display
       description: VGA compatible controller
       product: UHD Graphics 620 [8086:5917]
       vendor: Intel Corporation [8086]
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 07
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list
       configuration: driver=i915 latency=0
       resources: irq:140 memory:b2000000-b2ffffff memory:c0000000-cfffffff ioport:4000(size=64) memory:c0000-dffff
  *-display
       description: 3D controller
       product: GP108M [GeForce MX150] [10DE:1D10]
       vendor: NVIDIA Corporation [10DE]
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:156 memory:b3000000-b3ffffff memory:a0000000-afffffff memory:b0000000-b1ffffff ioport:3000(size=128)
```

**Comment by YXL76** [comment]
```
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
    error matching FRAGMENT shader requirements against the pipeline
    unable to filter the texture (ResourceBinding { group: 0, binding: 2 }) by the sampler (ResourceBinding { group: 0, binding: 1 })
    non-filterable float texture

', /home/yxl/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.11.1/src/backend/direct.rs:2195:5
```

latest code

**Comment by raymanfx** [comment]
FYI this seems to happen because the default Wgpu backend on Linux is OpenGL. See all supported backends here: https://docs.rs/wgpu/latest/wgpu/enum.Backend.html.

In my case, manually enforcing the vulkan backend by doing:
`WGPU_BACKEND=vulkan cargo run --release`
fixes the issue on my Intel GPU.

**Comment by hecrj** [comment]
Closing as it seems to be an issue with `wgpu`!

**Comment by cyqsimon** [comment]
There should be an open issue for this. Maybe here under `iced`, maybe under somewhere else, but there should definitely be one. Not being able to render images with OpenGL on Linux is quite a major compatibility issue IMO. And "use Vulkan" is a workaround, not a solution.

I did a search in `wgpu`'s repo and didn't find anything obvious. Can we confirm that this is indeed a `wgpu` issue? If not, I propose re-opening this issue; if so, we should certainly go open an issue over there (or maybe I just missed an existing one).

**Comment by curt-wise** [comment]
Same issue here: https://discourse.iced.rs/t/images-arent-properly-loading/84/5?u=curt-wise
