### ISSUE TITLE
left click not captured on images

### ISSUE THREAD

**Issue by najtin** [iced-rs/iced#1108]
The following code does not print the left-click-event, when the image is left-clicked, whereas right-clicks are correctly captured. Left-clicks on the background do also work.

```rust
use iced::{
    image, Application, Command,
    Element, Settings, Subscription,
};

pub fn main() -> iced::Result {
    Pokedex::run(Settings::default())
}

#[derive(Debug)]
struct Pokedex {
    image: image::Handle,
    image_viewer: image::viewer::State,
}

impl Application for Pokedex {
    type Executor = iced::executor::Default;
    type Message = iced_native::Event;
    type Flags = ();

    fn new(_flags: ()) -> (Pokedex, Command<iced_native::Event>) {
        let image = image::Handle::from_path("test.png");
        let image_viewer = image::viewer::State::new();
        (
            Pokedex {image: image, image_viewer: image_viewer },
            Command::none(),
        )
    }


    fn subscription(&self) -> Subscription<iced_native::Event> {
        iced_native::subscription::events()
    }


    fn title(&self) -> String {
        "Title".to_string()
    }

    fn update(&mut self, event: iced_native::Event) -> Command<iced_native::Event> {
        println!("{:?}", event);
        Command::none()
    }

    fn view(&mut self) -> Element<iced_native::Event> {
        image::Viewer::new(
            &mut self.image_viewer,
            self.image.clone(),
        ).into()
    }
}
```
with Cargo.toml: https://github.com/iced-rs/iced/blob/8a2a7f7e2144542b47c1d259f296ad7dcc5f3cf9/examples/pokedex/Cargo.toml

with test.png: https://user-images.githubusercontent.com/42641080/140061721-d1e39a64-8c58-4c5b-b33f-d0963c7a0aad.png

Tested on Ubuntu-Mate 20.04.2, X11

**Comment by 13r0ck** [comment]
To make any widget "left-clickable" it needs to be wrapped in a `button` widget

```rust
Button::new(button_state, Image::new()).on_press(Message::Left_Click)
```

**Comment by hecrj** [comment]
The `image::Viewer` processes left click events and captures them. The `events` subscription does not notify of captured events and, therefore, you won't see them printed.

If all you want is a simple image, use the [`Image`](https://docs.rs/iced_native/0.4.0/iced_native/widget/image/struct.Image.html) widget directly. If you want a subscription that notifies of any events, even if they are captured by widgets, then use [`events_with`](https://docs.rs/iced_native/0.4.0/iced_native/subscription/fn.events_with.html).

**Comment by najtin** [comment]
Thank you very much! Both your answers where extremely helpful. 

I will close the issue now. Please do not delete the issue, so that other people with the same question may also be enlightened.
