### ISSUE TITLE
are the examples also MIT licensed?

### ISSUE THREAD

**Issue by SArpnt** [iced-rs/iced#1115]
do i need to copy over the MIT license when starting with the example code for a project? it's not clear how much of the examples need to be used for it to be credited. i want to use the grid panes example to start off a project but i'm not sure if i need the license and how much i would have to alter the example until i don't need it anymore.

**Comment by aisq2008** [comment]
do what you want

**Comment by hecrj** [comment]
This question is unrelated to `iced` specifics, but software licensing in general.
