### ISSUE TITLE
Why not use `FnOnce` rather than `Fn` in `Cache::draw`?

### ISSUE THREAD

**Issue by YdrMaster** [iced-rs/iced#1119]
Hello, I'm sorry about my broken English. So let me ask the question directly. In file [cache.rs](https://github.com/iced-rs/iced/blob/master/graphics/src/widget/canvas/cache.rs), the method `draw` use a `impl Fn(&mut Frame)` as its parameter:

```rust
pub fn draw(&self, bounds: Size, draw_fn: impl Fn(&mut Frame)) -> Geometry
```

So, I can't move a iterator into the closure and have to collect the iterator before calling `draw` method. I wonder why not just use a `FnOnce`?

**Comment by sushigiri** [comment]
Seems like a super quick change, and I've tried `FnOnce` with both Cargo tests and each of the examples in `master`; is there a reason this might not be a good idea? Or should I just make a tiny MR?

**Comment by sushigiri** [comment]
Got it, PR made. Thank you!
