### ISSUE TITLE
Get bounds of a container?

### ISSUE THREAD

**Issue by QuinnFreedman** [iced-rs/iced#1120]
Is there a way to get the bounds of an element? For example, if I want to set an element to fill available space, but then I want to know how big that element actually ended up being, is there a way to query that? If not, I guess this is a feature request for that.

Also, it would be nice to know the x,y position of an element so you could translate mouse events from [`iced_native::subscription::events()`](https://docs.rs/iced_native/0.3.0/iced_native/subscription/fn.events.html) into the relative coordinates of the element.

For example, Elm provides that functionality in [`Browser.Dom`](https://package.elm-lang.org/packages/elm/browser/latest/Browser.Dom)

**Comment by davidclevenger** [comment]
I am also wondering this. I am trying to get relative pixel locations of an image by querying the cursor position over a displayed image.

**Comment by 13r0ck** [comment]
@QuinnFreedman 
It sounds like you are looking for something like [getElement](https://package.elm-lang.org/packages/elm/browser/latest/Browser-Dom#getElement) from elm. That is not yet implemented in iced

**Comment by 13r0ck** [comment]
@davidclevenger 

You will need to use a canvas for that. The [game of life](https://github.com/iced-rs/iced/tree/master/examples/game_of_life) example uses a canvas to track mouse inputs

**Comment by hecrj** [comment]
I have just opened #1193, which implements a `Responsive` widget that may suit some of the use cases described here. Let me know!

**Comment by davidclevenger** [comment]
@hecrj I *believe* this should work for my use case. I am trying to create a photo editor so I need to track mouse location inside the `Image` widget to mark pixel locations. I will update here with any successes or difficulties. Thanks for adding!
