### ISSUE TITLE
Help Wanted : 'Error in Surface::configure: invalid surface'

### ISSUE THREAD

**Issue by oknozor** [iced-rs/iced#1129]
Hello, Someone is trying to install an app that I made with iced. There are running in some wgpu error. 
Seems related to vulkan drivers but I am not sure. 

Could you please take a look ? 

The issue is here: https://github.com/oknozor/onagre/issues/35#issuecomment-980434615

**Comment by hecrj** [comment]
The user seems to have solved the issue by installing proper graphics drivers. Closing!
