### ISSUE TITLE
how to hide the command line window?

### ISSUE THREAD

**Issue by hu76589** [iced-rs/iced#1137]
windows 10 x64
iced 0.3

when I run the todos example,there are two windows,a command line window and a GUI window.
the command line window is not necessary,how to hide it?

**Comment by yusdacra** [comment]
You can put `#![windows_subsystem = "windows"]` at the top of your `main.rs` file, that should solve it.

**Comment by hu76589** [comment]
> You can put `#![windows_subsystem = "windows"]` at the top of your `main.rs` file, that should solve it.

it works,thanks!
