### ISSUE TITLE
canvas will not work correct with wgpu enabled antialiasing

### ISSUE THREAD

**Issue by cossonleo** [iced-rs/iced#1159]
iced version: 
e24eaa7c665f6b73aa4e9bac4b723cd8d24b78e1 on master

rust:
stable, 1.57.0

cpu & gpu:
AMD Ryzen 5 3400G with Radeon Vega Graphics

system: 
archlinux

canvas will not work correct when set antialiasing: `true`:
![2021-12-16_13-19](https://user-images.githubusercontent.com/20379044/146312912-84d89d09-6ac7-4e92-aca3-8b6a1e36c4f5.png)

it will work when set antialiasing: `false` or use glow
![2021-12-16_13-18](https://user-images.githubusercontent.com/20379044/146312961-37a8ee92-250b-4491-8eb2-bf6b9d169394.png)

**Comment by hecrj** [comment]
- Is the issue present in all of the examples? For instance, try `game_of_life` which should choose your high performance GPU.
- Is the issue present in [the `wgpu` examples]? If yes, then please report the issue there!

Closing this for now, as it seems like a hardware compatibility issue. Feel free to reopen if there is further evidence that something is wrong with `iced` itself.

[the `wgpu` examples]: https://github.com/gfx-rs/wgpu/tree/master/wgpu/examples
