### ISSUE TITLE
How to create a subscription that needs to be created async?

### ISSUE THREAD

**Issue by matthiasbeyer** [iced-rs/iced#1163]
Hi,

I have a conceptual problem: I need to create a `Subscription`, but that function that creates the subscription object needs to be `async`.

From what I see, I need to create a `Command` for running an async task, but the `Application::subscriptions()` function is not `async`... so how do I do that correctly?

**Comment by atlanticaccent** [comment]
Could you write the Subscription creation function as its own Subscription? Alternatively, you could write your async Subscription creation function to place it's subscriptions to a variable accessible from the "sync" runtime - for example an MPSC or mutex protected container/variable, which the Application::subscriptions function then reads from.

**Comment by matthiasbeyer** [comment]
It might work with a `tokio::sync::oneshot` as the receiving end is not async (https://docs.rs/tokio/latest/tokio/sync/oneshot/struct.Receiver.html) as far as I can see. I will report back as soon as I tried it!

**Comment by matthiasbeyer** [comment]
So this seems to work, although the code for it is a mess. I'll close this issue for now and reopen if I run into more issues (or open a new one).
