### ISSUE TITLE
Easy way to turn a Receiver<_> into a Subscription?

### ISSUE THREAD

**Issue by cbeust** [iced-rs/iced#1171]
I set up a pair of `tx` and `rx`:

```
        let (tx, rx) = mpsc::channel::<CpuMessage>();
```

The transmitter emits a bunch of messages and I was wondering if there is an easy way to turn the receiver (`std::sync::mpsc::Receiver`) into a `Subscription` so I can easily hook it up into my iced application.

**Comment by 13r0ck** [comment]
I think #1172 has morphed into a dupe of this. As that one has responses, would you mind closing this one please?

**Comment by cbeust** [comment]
Dupe of https://github.com/iced-rs/iced/issues/1172, closing.
