### ISSUE TITLE
Intercepting Paste Events

### ISSUE THREAD

**Issue by Alch-Emi** [iced-rs/iced#1177]
I'm trying to write an app which includes custom behavior for pasting, and especially multi-line pasting.  It's fairly easy to listen for a Ctr+V event, check if a relevant input is selected, grab the clipboard, and then run the custom behavior.

However, by the time the message reaches my code, the UI will have already filled the widget with the text clipboard.  I can work around this by just guessing the length of the pasted text (i think it's just the text length - the # of newlines) and truncating the text in the UI, but this feels a little messy.

It would be nice to be able to intercept a paste event, maybe by setting a property on the `TextInput` component that produces a `Message` instead of pasting text, or just disabling pasting into the `TextInput`.

**Comment by brightly-salty** [comment]
Just a possible solution, not a permanent one: you could copy the code of this file and remove the linked lines to create a widget which doesn't handle pasting, or just insert your custom logic into that area
https://github.com/iced-rs/iced/blob/5466d6a11d0a4bee01e954b7c727b3fd67cea02a/native/src/widget/text_input.rs#L680-L710

**Comment by Alch-Emi** [comment]
ooh that's handy, thank you!

**Comment by hecrj** [comment]
We could extend the `TextInput` widget with additional methods to override paste behavior.

Could you elaborate a bit on your use case? Do you want to simply perform a transformation on the pasted text?

**Comment by Alch-Emi** [comment]
Sorry I didn't get back to this sooner!  The project I'm working on is displaying several lines of text in a context where it makes sense to use individual, single-line text inputs.  However, I'd like the user to be able to do a multi-line paste, so I'm trying to fudge it a little bit by intercepting the paste and breaking up the text between lines.

That said, I could definitely see this being used in other usecases where transformations might need to be applied as well.
