### ISSUE TITLE
[Feature Request] Control image fit / scaling in image widget

### ISSUE THREAD

**Issue by Alch-Emi** [iced-rs/iced#1179]
As of right now, the `Image` widget displays an image downscaled to fit within the widgets bounds.

However, as mentioned in #885, some users may want their image upscaled within the widget bounds as well.  Beyond this, however, some users may want an image to completely cover (as opposed to just fit within) the image bounds, cropping out the edges.  This is especially useful for images meant to act as backgrounds, headers, or other places where the shape of the bounding box of the image is important.  The user in issue #1014 represents another possible usecase where the image should be stretched to fit without preserving the aspect ratio.

I'd like to propose a feature similar to [`object-fit` in css][1], where the user can select their preferred behavior by passing an enum to the Image widget.  I think that a feature like this would make designing UIs with different behaviors easier for users who might otherwise need to manually do the calculations to scale the image to fit their screen.

Thank you for your time and consideration!

[1]: https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit

**Comment by hecrj** [comment]
Sounds good to me! Contributions welcome!
