### ISSUE TITLE
thread 'main' panicked at 'Error in Surface::configure: invalid surface'

### ISSUE THREAD

**Issue by g-cyan** [iced-rs/iced#1229]
As I `cargo run --package counter` inside `~/iced/examples` , the following error occurs.
```bash
thread 'main' panicked at 'Error in Surface::configure: invalid surface', /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:214:9
```
What should I do for next?

**Comment by hecrj** [comment]
Duplicate of #1129.

**Comment by g-cyan** [comment]
I've also resolved that problem with `sudo apt install -y nvidia-driver nvidia-cuda-toolkit`
