### ISSUE TITLE
Add Documentation Website to Repo

### ISSUE THREAD

**Issue by elibroftw** [iced-rs/iced#1251]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

There should be a link to the documentation in the sidebar of the repo.

### What is the expected behavior?

There should be a link to the documentation in the sidebar of the repo.

### Version

master

### Operative System

Windows

**Comment by hecrj** [comment]
Done!
