### ISSUE TITLE
Web canvas is stuck at fixed size on master

### ISSUE THREAD

**Issue by jg2562** [iced-rs/iced#1265]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

When building both tour and my own app on master, they now get rendered into a web canvas. However, the web canvas is a fixed size of 1024x768. Oddly, the canvas also doesn't get rendered until the mouse is hovered over it. This also seems to happen when rendered on both windows and linux.

After a discussion with hecjr, I realized this problem is probably on `iced` rather than `iced_web` as it uses a canvas. So I moved the issue to here.

### What is the expected behavior?

The canvas should be resized to fit the screen.

### Version

master

### Operative System

Linux

**Comment by powpingdone** [comment]
Some asides I found while diving into this and what I'll document here.

The current system is currently bound by `winit`'s implementation of the window in WASM. Manually resizing the canvas element doesn't work, so using the inner `Action::Window(Action::Resize` to do so is needed. The code needed to fire the command is as such:
```rust
#[cfg(target_arch = "wasm32")]
{
    use iced_native::{command, window};
    let window = web_sys::window().unwrap();
    let (width, height) = (
        (window.inner_width().unwrap().as_f64().unwrap())
            as u32,
        (window.inner_height().unwrap().as_f64().unwrap())
            as u32,
    );
    Command::single(command::Action::Window(
        window::Action::Resize { width, height },
   ))
},
```
Note that the body must also have the style: 
```css
margin:0px;
overflow:hidden;
```
The only thing I haven't figured out at this point is getting text inputs to work on mobile (no keyboard pops up) and how to impl a subscription that sends a message on `onresize`.
