### ISSUE TITLE
A horizontal and vertical scrolling widget

### ISSUE THREAD

**Issue by tareksalem** [iced-rs/iced#1273]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

I am asking if there a vertical and horizontal scrolling widget to use

### What is the expected behavior?

A supported widget that enables horizontal and vertical scrolling

### Version

0.3.0

### Operative System

Linux

**Comment by hecrj** [comment]
Duplicated of #331.

**Comment by tareksalem** [comment]
sorry, I didn't know, but when it will be available??

**Comment by hecrj** [comment]
> sorry, I didn't know, but when it will be available??

Eventually. When someone decides to spend their free time to gift their work.
