### ISSUE TITLE
Iced app sometimes takes 5 to 10 second to start 

### ISSUE THREAD

**Issue by oknozor** [iced-rs/iced#1300]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

When I launch any iced app either in release or debug mode it can take up to 10 seconds to show up. 
This is random and sometimes does not happen at all. I have not been able to reproduce on other laptops.

At first I thought it was related to the app I am writing but I am getting the same result with the Pokedex example. 

I tried to change the wgpu backend like so : `WGPU_BACKEND=vulkan onagre`, `WGPU_BACKEND=gl onagre`  without success. 

**Hardware :**
- MSI bravo 15
- 03:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 14 [Radeon RX 5500/5500M / Pro 5500M] (rev c1)
- 07:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Renoir (rev *c7)

**Drivers :** 
- mesa 21.3.7-2
- vulkan-radeon 21.3.7-2

I'd be curious to know if people with the same hardware experience the same issue. Also does this belongs in wgpu's repo ? 
 

### What is the expected behavior?

Iced apps should start faster.

### Version

0.3.0

### Operative System

Linux

### Do you have any log output?

The application hangs at the last line of these logs : https://gist.github.com/oknozor/024a8baa43466b1bf5d9b9d19fa8d0f7

And continue with the following: https://gist.github.com/oknozor/8a55d64df7a77f347454d7dc379cfde0

**Comment by hecrj** [comment]
Is this specific to `iced` or does it also happen with the [`wgpu`] examples?

**Comment by oknozor** [comment]
I just tried one of the wgpu example and I am getting the same startup latency

**Comment by hecrj** [comment]
Closing as this seems an upstream issue.
