### ISSUE TITLE
Different look on different computer with the same build on windows

### ISSUE THREAD

**Issue by luanmenglei** [iced-rs/iced#1317]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

I made a app that is used to get a random student in class.
It works on my computer.
But when I move the app that is build on my computer to the school's computer, I got a very wired result.
The UI is both Mirror flip and up and down flip.
I don't have the screenshot now but I will upload it tomorrow.

### What is the expected behavior?

![image](https://user-images.githubusercontent.com/52412246/165110756-797b29ac-5100-4668-903a-4acbbccbf647.png)

### Version

0.3.0

### Operative System

Windows

### Do you have any log output?

```shell
no
```

**Comment by hecrj** [comment]
`0.3` is quite an old release and many fixes have landed both to `iced` and `wgpu` since then.

We recently released `0.4` (see #1328). Could you try upgrading and report back?
