### ISSUE TITLE
Non-ASCII symbols (e.g. cyrillic) are rendered as question marks after 825c7749ff364cf1f7ae5cab0c25f27ed85c7d82

### ISSUE THREAD

**Issue by anarsoul** [iced-rs/iced#1335]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

"todo" example cannot render cyrillic symbols correctly.

I bisected it and 825c7749ff364cf1f7ae5cab0c25f27ed85c7d82 is the first bad commit.

### What is the expected behavior?

Cyrillic symbols are rendered correctly.

### Version

master

### Operative System

Linux

**Comment by hecrj** [comment]
825c7749ff364cf1f7ae5cab0c25f27ed85c7d82 removes the `default_system_font` from the `default` crate features.

If you are not enabling it manually, then it will try to use the embedded font: `Lato`, which probably does not contain the glyphs you are trying to render.

I advice you to enable the `default_system_font` feature in your `Cargo.toml` or embed your own font in the application.

**Comment by vasilykh-arista** [comment]
Maybe it makes sense to change embedded font to another that has more glyphs?

**Comment by unreal79** [comment]
Knowing about `default_system_font` feature would have saved me a lot of time...

**Comment by fenhl** [comment]
Please consider listing optional features in the crate-level docs to make this more discoverable.
