### ISSUE TITLE
v0.4 with glow: panic on start on Linux and Windows due to glow_glyph issue. PR available with fix 

### ISSUE THREAD

**Issue by greatest-ape** [iced-rs/iced#1336]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Because of issue https://github.com/hecrj/glow_glyph/issues/6, [OctaSine](https://github.com/greatest-ape/OctaSine) crashes on start for three users, for instance with commit [3076ddb](https://github.com/greatest-ape/OctaSine/commit/3076ddb148a03aa02dc71a25acdce265996f0f9a), which uses iced 0.4.

The crash is avoided for all three users by building OctaSine with branch used in my PR https://github.com/hecrj/glow_glyph/pull/7. There is more info in the PR description.

I'm not including a SSCCE for the time being, since the source of the problem seems to be quite clear.

### What is the expected behavior?

No panic on start.

### Version

master

### Operative System

Windows

### Do you have any log output?

```shell
08:17:31 [INFO] Version: 3.2.14800, Core Profile Context 22.3.1 30.0.15002.1004
08:17:31 [INFO] Embedded: false
08:17:31 [INFO] Renderer: AMD Radeon RX 6800 XT
08:17:31 [INFO] Mode: core
08:17:31 [INFO] Shader directive: #version 150
thread 'main' panicked at 'Vertex shader failed to compile with the following errors:
ERROR: 0:4: error(#5) Extension: "explicit location is not supported in this version"
ERROR: 0:5: error(#5) Extension: "explicit location is not supported in this version"
ERROR: 0:6: error(#5) Extension: "explicit location is not supported in this version"
ERROR: 0:7: error(#5) Extension: "explicit location is not supported in this version"
ERROR: 0:8: error(#5) Extension: "explicit location is not supported in this version"
ERROR: error(#273) 5 compilation errors.  No code generated
```

**Comment by hecrj** [comment]
I just released `glow_glyph 0.5.1` which includes https://github.com/hecrj/glow_glyph/pull/7 and should fix the issue: https://github.com/hecrj/glow_glyph/releases/tag/0.5.1

Thanks for the detailed report and the fix!
