### ISSUE TITLE
No way to access `menu::Stylesheet`

### ISSUE THREAD

**Issue by Andrew-Schwartz** [iced-rs/iced#1406]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

On the current master branch, there is no way to access the `menu::StyleSheet` from `iced` itself, so you can't implement theming for a picklist without pulling in `iced_style` manually.

### What is the expected behavior?

There should be a `menu` mod or something in `iced`. 

### Version

master

### Operative System

Windows

**Comment by Andrew-Schwartz** [comment]
I've just noticed there is also no way to access the `rule` mod.

**Comment by aerosabe** [comment]
I just recently figured out how to do styling. Rust nearly walked me through it after I realized That I just needed the Trait implemented. Here is an outline of my impl:

#[derive(Clone, Copy)]
pub struct Theme {}

impl **iced::pick_list::StyleSheet** for Theme {
    fn menu(&self, ) -> **iced::pick_list::Menu** {... }

    fn active(&self) -> iced::pick_list::Style {... }

    fn hovered(&self) -> iced::pick_list::Style {...}
}

**Comment by hecrj** [comment]
@Andrew-Schwartz The `rule` module should be accessible: https://docs.iced.rs/iced/widget/rule/index.html
