### ISSUE TITLE
No window appears on Windows with recent window mode changes

### ISSUE THREAD

**Issue by mtkennerly** [iced-rs/iced#1419]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

This happens on da7e8598406fcde2a33ea749d561a2f10dbb5407, but works correctly 3 commits earlier on 07cbed106467097543ff33d3b34e0e1ca6f695ae. It only happens on Windows, but Linux and Mac work fine.

In this demo, I try it first on master (and ctrl-C out of it since nothing happens), then try on the earlier commit:

> https://user-images.githubusercontent.com/4934192/186039006-f01711d9-175d-4ca7-8e08-1d0ad7942c1d.mp4

### What is the expected behavior?

Window should appear.

### Version

master

### Operative System

Windows

**Comment by JPGygax68** [comment]
I'm a Rust beginner but have run into the same issue and  tried to look into it.

The change that triggers this behavior seems to be that `iced_winit` now tries to create the window as initially invisible and make it visible only when it is ready.

This is apparently done via a call to the `winit::Window::request_redraw()` method. On Windows, that method calls the WinUser function `RedrawWindow()`, which is supposed to trigger a `WM_PAINT` message, which would in turn queue a `RedrawRequested` event to the Winit message queue, which would, after redrawing, call the `compositor.present()` and make the window visible. (Here's the code excerpt from `iced/winit/src/application.rs`:)
````Rust
                match compositor.present(
                    &mut renderer,
                    &mut surface,
                    state.viewport(),
                    state.background_color(),
                    &debug.overlay(),
                ) {
                    Ok(()) => {
                        debug.render_finished();

                        if !visible && should_be_visible {
                            window.set_visible(true);

                            visible = true;
                        }
````
However, as is stated in an in-source comment in a source file for the Windows implementation of the winit event loop (`platform_impl/windows/event_loop.rs`), "The window technically has to be visible to receive WM_PAINT messages". This optimization that Windows does seems to be responsible for WM_PAINT never being sent to the window, and thus the `if !visible && should_be_visible` block never being executed.

I am not sure how to properly fix this problem; I hope the author does :-)

**Comment by JPGygax68** [comment]
I have committed a workaround to my fork https://github.com/JPGygax68/iced.git 

I don't think it deserves a pull request, as I suspect it would defeat the purpose of the improvement introduced after https://github.com/iced-rs/iced/commit/07cbed106467097543ff33d3b34e0e1ca6f695ae, by again making the window visible before it is fully ready.
