### ISSUE TITLE
Unexpected space between Button and Canvas in a row

### ISSUE THREAD

**Issue by IohannRabeson** [iced-rs/iced#1436]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

I have an unexpected space when creating a Button in a row with a Canvas. It's bizarre because if I put the canvas first and the button after, then there is no space between. 
I first thought it was because of a mistake I did, so I started a new app but I managed to reproduce the issue so I'm fairly confident it's an issue in Iced.

You can see this issue in this screenshot:
<img width="1047" alt="Screenshot 2022-09-10 at 14 21 59" src="https://user-images.githubusercontent.com/685196/189496695-b013b8ad-fd77-4fd9-9bb1-14cdf4c26b1c.png">

My SSCCE does the following:

1. create a button
2. create a canvas with a black background and a red line for border
3. create a row with the button and the canvas as content

I expect the button and the canvas without any space between.
But the result is a button, a space (which suspiciously seems exactly equal to the width of the button or whatever is the widget I tried), and the canvas.
Here is the complete code:
```rust
use iced::{Sandbox, widget::{button, row, text, column, canvas, canvas::{Cache, Path, Stroke}}, Theme, Point, Size, Color};

#[derive(Debug, Clone)]
enum Message {}

struct TestApp { cache: Cache, }

impl Sandbox for TestApp {
    type Message = Message;

    fn new() -> Self { Self { cache: Cache::new() } }
    fn title(&self) -> String { "Test".into() }
    fn update(&mut self, _message: Self::Message) {}
    fn view(&self) -> iced::Element<Self::Message> {
        row![button("Hello"), canvas(self).width(iced::Length::Fill).height(iced::Length::Fill)].into()
        
        // With a column, I also reproduce the same behavior but vertically
        // column![text("Hello"), canvas(self).width(iced::Length::Fill).height(iced::Length::Fill)].into()

        // If I add the canvas first, the issue can't be reproduced!! There is no space between the canvas and the button as expected.
        // row![canvas(self).width(iced::Length::Fill).height(iced::Length::Fill), button("Hello")].into()
    }
}

impl canvas::Program<Message> for TestApp {
    type State = ();
    fn draw(&self, _state: &Self::State, _theme: &Theme, bounds: iced::Rectangle, _cursor: canvas::Cursor) -> Vec<canvas::Geometry> {
        let background = Path::rectangle(Point::new(bounds.x, bounds.y), Size::new(bounds.width, bounds.height));
        let frame_stroke = Stroke::default().with_color(Color::from_rgb8(255, 0, 0)).with_width(2f32);
        let waveform = self.cache.draw(bounds.size(), |frame| {
            frame.fill(&background, Color::BLACK);
            frame.stroke(&background, frame_stroke);
        });
        vec![waveform]
    }
}
fn main() -> Result<(), iced::Error> { TestApp::run(Default::default()) }
```
My Cargo.toml:
```
[package]
name = "iced_canvas_bug"
version = "0.1.0"
edition = "2021"
[dependencies]
iced = { git = "https://github.com/iced-rs/iced", features = ["default", "canvas"] }
```
I added few commented lines in TestApp::view() to illustrate the following cases:
 - the issue is also present when using a column layout
 - I can reproduce if I use a Text widget instead of a button
 - if I add the canvas first (instead of the button first), then I can't reproduce the issue!

### What is the expected behavior?

The expected behavior is the application displays a row with a button and a canvas tightly packed with the canvas filling all the space on the right.

### Version

master

### Operative System

macOS and Windows

**Comment by hecrj** [comment]
The coordinate system in a `Canvas` has its origin at `(0, 0)` not `(bounds.x, bounds.y)` (i.e. the coordinates are relative to the position of the widget, not absolute window coordinates).
