### ISSUE TITLE
Column puts spacing all to the bottom

### ISSUE THREAD

**Issue by FlixCoder** [iced-rs/iced#1498]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

When attempting to make a grid using column and row, with each item having spacing in between, I encountered that the column seems to put all spacing to the bottom instead of in between elements. Here is an example:

```rust
use iced::{
	pure::{
		widget::{self, Column, Container, Row},
		Application,
	},
	Background, Color, Length, Space,
};

fn main() {
	Bug::run(Default::default()).unwrap();
}

struct Bug;

impl iced::pure::Sandbox for Bug {
	type Message = ();

	fn new() -> Self {
		Self
	}

	fn title(&self) -> String {
		"Bug".to_owned()
	}

	fn update(&mut self, _message: Self::Message) {}

	fn view(&self) -> iced::pure::Element<'_, Self::Message> {
		let mut board_column = Column::new().spacing(2);
		for _ in 0..20 {
			let mut board_row = Row::new().spacing(2);
			for _ in 0..20 {
				let item = Container::new(Space::new(Length::Shrink, Length::Shrink))
					.width(Length::Fill)
					.height(Length::Fill)
					.style(BoxStyle);
				board_row = board_row.push(item);
			}
			board_column = board_column.push(board_row);
		}

		Container::new(board_column).padding(2).style(BoardStyle).into()
	}
}

struct BoardStyle;
impl widget::container::StyleSheet for BoardStyle {
	fn style(&self) -> widget::container::Style {
		widget::container::Style {
			text_color: None,
			background: None,
			border_radius: 0.0,
			border_width: 2.0,
			border_color: Color::from_rgb8(255, 0, 0),
		}
	}
}

struct BoxStyle;
impl widget::container::StyleSheet for BoxStyle {
	fn style(&self) -> widget::container::Style {
		widget::container::Style {
			text_color: None,
			background: Some(Background::Color(Color::BLACK)),
			border_radius: 0.0,
			border_width: 0.0,
			border_color: Color::TRANSPARENT,
		}
	}
}
```

### What is the expected behavior?

I would expect the spacing to be between the items, such that the layout becomes a grid with equal spacing.

### Version

0.4

### Operative System

Linux

**Comment by FlixCoder** [comment]
> This isn't a bug with iced, your logic is incorrect
> 
> But, there is an even better way to do a space between items in a column! Push all of your widgets into the column, then add spacing on the column. A column's spacing is in between each widget. https://github.com/iced-rs/iced/blob/master/examples/todos/src/main.rs#L373 Same rules apply for rows

Isn't that what I am doing? Ok I am setting the spacing before pushing items, but there is no change when I do it afterwards. The `Space` widget ist just used to have something in the `Container`, could also just be text or something.

**Comment by hecrj** [comment]
You need to set the `height` of the `board_row` to `Length::Fill` as well.

**Comment by FlixCoder** [comment]
Aah I see, thank you, that solves it yeah..
