### ISSUE TITLE
Gradient implementation does not work in Wasm

### ISSUE THREAD

**Issue by sergiyprotsiv** [iced-rs/iced#1523]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Trying to run Iced with `wgpu` compiled in `webgl` mode (e.g. in `wasm` or in the `integration_wgpu` example) results in an error

`thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `iced_wgpu::triangle::gradient pipeline`
    Internal error in VERTEX | FRAGMENT | VERTEX_FRAGMENT shader: new_render_pipeline_state: "Compiler encountered an internal error"`

This is related to the new gradient pipeline employing Storage Buffers in a fragment shader (which `webgl` does not support).

### What is the expected behavior?

I expected the app to compile and run, and either take a performance hit (due to "faking" storage buffers using uniforms or textures) or at least only break when the gradients are actually used. As is, Iced does not compile the `counter` example nor the `integration_wgpu`. It could be that the gradients are now used in some default widgets that causes this.

### Version

master

### Operative System

macOS

**Comment by sergiyprotsiv** [comment]
Thanks @bungoboingo, can confirm that the Wasm version of `integration_wgpu` works in your branch. I still cannot compile it for native using `cargo run` since this example itself imports `wgpu` with `webgl` flag (without the target being Wasm). So perhaps a medium-term solution would choose to include gradients based on the `wgpu` feature set, if that is possible.

**Comment by sergiyprotsiv** [comment]
Can't run it natively using plain old `cargo run`. I thought it was due to `iced_wgpu = { path = "../../wgpu", features = ["webgl"] }` in `Cargo.toml`, but removing the explicit `webgl` does not help. The example used to work in 0.4.

**Comment by sergiyprotsiv** [comment]
I checked on a Linux machine and it runs there, so the issue is likely with my Mac's graphics configuration. In any case, Wasm works on both platforms, so I am closing the issue. Would be great for your fix to be integrated back into the master!

**Comment by YI--** [comment]
Hi , I had a similar problem on mac

`thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_render_pipeline
      note: label = `iced_wgpu::triangle::gradient pipeline`
    Internal error in VERTEX | FRAGMENT | VERTEX_FRAGMENT shader: new_render_pipeline_state: "Compiler encountered an internal error"

', /xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.14.0/src/backend/direct.rs:2403:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by YI--** [comment]
> On macos? Is it a m1 or an intel chip?

Hi

Sorry 😅, I provided too little information;

OS: 
macOS: 12.6 (21G115)
CPU/GPU: Intel

Rust:
cargo 1.65.0 (4bc8f24d3 2022-10-20)
rustc 1.65.0 (897e37553 2022-11-02)
rustup 1.25.1 (bb60b1e89 2022-07-12)

eg:
I used the program from the example directly and had the same problem;
 https://github.com/iced-rs/iced/tree/master/examples/tour

For reference only:
I also searched the issues of wgpu and found a related issue;
https://github.com/gfx-rs/wgpu/issues/3136


I haven't verified it works in Linux or Windows
