### ISSUE TITLE
Could not compile iced_graphics

### ISSUE THREAD

**Issue by artemromaniv** [iced-rs/iced#1540]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Error [E0658] appeared after running 
$cargo build
Tried with master version and older versions

### What is the expected behavior?

The program compiles

### Version

master

### Operative System

Linux

### Do you have any log output?

```shell
Compiling iced_graphics v0.4.0
error[E0658]: generic associated types are unstable
  --> /home/jeff/.cargo/registry/src/github.com-1ecc6299db9ec823/iced_graphics-0.4.0/src/image/storage.rs:12:5
   |
12 |     type State<'a>;
   |     ^^^^^^^^^^^^^^^
   |
   = note: see issue #44265 <https://github.com/rust-lang/rust/issues/44265> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `iced_graphics` due to previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by carl-anders** [comment]
You should update Rust.

Maybe the version tag in cargo manifest should be added to make this error more clear.

**Comment by t18b219k** [comment]
GATs is not stabilized under rust 1.65 .
You need to update rust to 1.65 or later.

**Comment by artemromaniv** [comment]
> Have you tried updating the rust compiler? `rustup update`

Oh,my bad,yes, i forgot to update rust,sorry for silly mistake,now it's workiig,i'm closing the issue

**Comment by flomang** [comment]
I just did and update. I'm currently at  "rustc 1.65.0 (897e37553 2022-11-02)" .  I'm still getting this error. Is there something else I'm forgetting to do?

**Comment by DanielMSchmidt** [comment]
For anyone running into this issue as well on OSX: If you happen to have rust installed via homebrew and via rustup the homebrew version might overwrite the rustup version. Took me a while to figure out :)
