### ISSUE TITLE
ContentFit::Cover and ContentFit::None do not work for images when using glow backend

### ISSUE THREAD

**Issue by ben-wallis** [iced-rs/iced#1564]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

When using either `ContentFit::None` or `ContentFit::Cover`, images overflow the bounds of their parent container when using the `glow` backend.

`wgpu` - working as intended:
![image](https://user-images.githubusercontent.com/11904214/204641347-2614d0b6-202b-44ea-86f2-e0480203b1b7.png)

`glow` - not working as intended:
![image](https://user-images.githubusercontent.com/11904214/204641448-73113ce9-5598-46e8-bfa4-c59845394ab9.png)

Minimal reproduction repository available here: https://github.com/ben-wallis/iced-glow-image-bug  - just switch between the `glow` and `wgpu` features for the `iced` dependency

### What is the expected behavior?

Image rendering behaves the same on all rendering backends

### Version

master

### Operative System

Windows

**Comment by hecrj** [comment]
This may have just been fixed by #1557.

**Comment by ben-wallis** [comment]
That does indeed fix the issue - this can be closed then :)
