### ISSUE TITLE
Unable to access `event_loop` or `Window` to get `MonitorHandler`

### ISSUE THREAD

**Issue by yongDataScince** [iced-rs/iced#1566]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

When creating an application, I need to set the window width to a quarter of the width of the monitor. And also move to the corner of the screen regardless of the screen size.

### What is the expected behavior?

set the window size to a quarter of the monitor width

### Version

master

### Operative System

macOS

**Comment by hecrj** [comment]
This isn't a bug! Please, open a discussion instead.
