### ISSUE TITLE
Scroller in scrollable is no longer visible when hovering its content

### ISSUE THREAD

**Issue by ben-wallis** [iced-rs/iced#1573]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

In iced `0.4` the scroller within the scrollbar is only visible when mousing over the content - in `0.5` the scroller is permanently visible with seemingly no way to recreate the behavior of `0.4`. This is demonstrable by running the `scrollable` example for both versions.

### What is the expected behavior?

Either the default behavior of 0.4 is restored, or it is possible to optionally specify this behavior for a `scrollable`.

### Version

master

### Operative System

Windows

**Comment by ben-wallis** [comment]
Thanks for the quick fix!

**Comment by GyulyVGC** [comment]
I just want to add that now the scroller is not visible at all when the scrollable area is not hovered (I'm using v0.6.0).

Could this be solved? I feel it's useful to see the scroller even when not hovering the scrollable content.
