### ISSUE TITLE
iced 0.6.0 requires iced_lazy 0.3.0

### ISSUE THREAD

**Issue by ArtHome12** [iced-rs/iced#1581]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

iced 0.6.0 requires iced_lazy 0.3.0, but but officially available only 0.2.0

### What is the expected behavior?

For pane_grid example replace cargo.toml 
===
[dependencies]
# iced = { path = "../..", features = ["debug"] }
# iced_native = { path = "../../native" }
# iced_lazy = { path = "../../lazy" }

iced = { version = "0.6.0",  features = ["debug"] }
iced_native = "0.7.0"
iced_lazy = "0.2.0"
===
And get two errors:
the trait bound `iced_native::Element<'_, _, _>: From<Responsive<'_, _, _>>` is not satisfied
the following other types implement trait `From<T>`:
  <iced_native::Element<'a, Message, Renderer> as From<&'a str>>
...

mismatched types
expected struct `iced_native::element::Element<'_, _, _>`
   found struct `iced_native::Element<'_, Message, iced_graphics::renderer::Renderer<iced_wgpu::backend::Backend, Theme>>`
perhaps two different versions of crate `iced_native` are being used?

### Version

master

### Operative System

Windows

**Comment by hecrj** [comment]
Forgot to push that one! It should be released now.
