### ISSUE TITLE
`Lazy` example broken

### ISSUE THREAD

**Issue by torsteingrindvik** [iced-rs/iced#1583]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

I ran `cargo r` in `examples/lazy`.

I then get:

```text
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', C:\<path>\iced\lazy\src\lazy.rs:221:22
```

I tried the current `main` @ 7ceb8b8d406cb72ea0e0c341ad755d69165d95f9 ,
as well as using iced 0.6 + iced_lazy 0.3 in a standalone project (copy pasting the lazy example).

### What is the expected behavior?

The example to run.

### Version

master

### Operative System

Windows

**Comment by nowzdev** [comment]
One simple solution is to use  iced 0.5 + iced_lazy 0.2

**Comment by torsteingrindvik** [comment]
I did a git bisect and found it the issue was introduced in this commit: https://github.com/iced-rs/iced/commit/f1ada7a803998ac3fb2c1bedc6d6650264f3e603
The panic happens in the `Rc::get_mut(...).unwrap()` part of `fn overlay(...)`.

@tarkah maybe you know what's going on in this part?

**Comment by hecrj** [comment]
@torsteingrindvik I took a quick glance a couple weeks ago and I wasn't able to please the borrow checker. `ouroboros` makes debugging errors rather difficult.

**Comment by tarkah** [comment]
Issue is we hold an RC in two places when trying to RC::get_mut which panics.

I took a look a couple weeks back but couldn't get the compiler happy. I tried dropping the RC before the overlay is built and then manually implementing Drop for the overlay to reclone the RC, but ouroboros doesn't like manual Drop implementations.

I'll try to take another look tomorrow.

**Comment by rs017991** [comment]
Sounds like the same thing I ran into with Modal: https://github.com/iced-rs/iced_aw/issues/73
