### ISSUE TITLE
Only first overlay element is being rendered

### ISSUE THREAD

**Issue by ThisIsRex** [iced-rs/iced#1591]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

When trying to add multiple overlay elements, it renders the only first. I took a Floating Button example and got this bug. I also tried to implement my own overlay container but got the same result. For the second overlay even doesn't call an `overlay` function and the layout isn't being calculated.

Iced version is 0.5, but it can't be chosen from the version dropdown list.

Screenshot:
![image](https://user-images.githubusercontent.com/49415741/206567234-26154383-a80d-4cfa-8857-f5983a05ef61.png)

The code:
```rust
use iced::widget::Row;
use iced::{
    widget::{Button, Column, Container},
    Element, Length, Sandbox, Settings,
};

use iced_aw::floating_element::{Anchor, FloatingElement};
use iced_aw::Badge;

fn main() -> iced::Result {
    FloatingElementExample::run(Settings::default())
}

#[derive(Debug, Clone)]
enum Message {
    ButtonPressed,
}

struct FloatingElementExample {
    lines: Vec<String>,
}

impl Sandbox for FloatingElementExample {
    type Message = Message;

    fn new() -> Self {
        FloatingElementExample { lines: Vec::new() }
    }

    fn title(&self) -> String {
        String::from("FloatingButton example")
    }

    fn update(&mut self, message: Message) {
        match message {
            Message::ButtonPressed => self.lines.push("This is a newly added line.".into()),
        }
    }

    fn view(&self) -> Element<Message> {
        let row = Row::new()
            .spacing(8)
            .push(
                FloatingElement::new(
                    Button::new("Underlay1").on_press(Message::ButtonPressed),
                    || Badge::new("Ovr1").into(),
                )
                .anchor(Anchor::NorthEast),
            )
            .push(
                FloatingElement::new(
                    Button::new("Underlay2").on_press(Message::ButtonPressed),
                    || Badge::new("Ovr2").into(),
                )
                .anchor(Anchor::NorthEast),
            );

        Container::new(Column::new().push(row))
            .width(Length::Fill)
            .height(Length::Fill)
            .padding(10)
            .center_x()
            .center_y()
            .into()
    }
}
```

### What is the expected behavior?

I expect the all overlay elements to be rendered

### Version

0.4

### Operative System

Windows

**Comment by zopu** [comment]
I'm hitting this issue too on iced 0.5.0, iced_native 0.7.0. A quick scan of the iced_native source and I *think* I can maybe see the problem.

In the [implementation of Widget::Overlay for Row](https://github.com/iced-rs/iced/blob/cdc9b358190574c8ab69670ffeeeddfda3ce3b2c/native/src/widget/row.rs#L237) there's a call to overlay::from_children, but looking at the source of overlay::from_children, that function's description is "Obtains the first overlay [`Element`] found in the given children."

This is my first time looking at iced source, so I might be missing something. Would someone who knows this area be able to sanity-check that?

**Comment by zopu** [comment]
I think @hecrj wrote this code and could probably clue us in.

**Comment by 13r0ck** [comment]
Iced only supports one at the current moment

**Comment by zopu** [comment]
In case it helps anyone else, they way I worked around this was to use renderer.with_layer in my custom widget's draw function.

`

        if layout.bounds().contains(cursor_position) {
            renderer.with_layer(layout.bounds(), |r| {
                self.my_overlay.as_widget().draw(
                    &state.children[1],
                    r,
                    theme,
                    style,
                    layout_children.next().unwrap(),
                    cursor_position,
                    viewport,
                );
            });
        }
    }
`
