### ISSUE TITLE
Examples pane_grid does not work

### ISSUE THREAD

**Issue by valerii15298** [iced-rs/iced#1598]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

pane_grid example from examples folder does not compile with the latest version of iced(0.6)

### What is the expected behavior?

It should compile

### Version

master

### Operative System

Windows

**Comment by hecrj** [comment]
`cargo run --package pane_grid` works fine for me!
