### ISSUE TITLE
Can't nest col! and row!

### ISSUE THREAD

**Issue by patientplatypus6** [iced-rs/iced#1604]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

I would expect that there would be a way to nest `row!` and `col!` in order to make a UI library be useful, but I can't seem to make it work. Please find a working repo with an example of the issue here: https://github.com/patientplatypus6/icedrustplay

### What is the expected behavior?

I would expect that `col!` and `row!` would work.

### Version

master

### Operative System

Windows

### Do you have any log output?

```shell
See repo
```

**Comment by 13r0ck** [comment]
A compile error is not a bug, your code is incorrect. Rows and columns absolutely can be nested. I recommend looking at the [examples folder](https://github.com/iced-rs/iced/tree/master/examples) to see proper implementations.

**Comment by patientplatypus6** [comment]
I'm an idiot I apologize. I didn't import "column". Le sigh.

**Comment by 13r0ck** [comment]
No worries! 😊
