### ISSUE TITLE
Outline links of Website https://book.iced.rs/  can not click, we can not "get started"

### ISSUE THREAD

**Issue by jackiealex** [iced-rs/iced#1612]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

when click "get started", it jumps to https://book.iced.rs/, and the outline links can not click and are all disabled

### What is the expected behavior?

Expect to be clickable

### Version

master

### Operative System

macOS

### Do you have any log output?

```shell
~😂
```

**Comment by emann** [comment]
You'll notice the sections/chapters also all have `TODO:` infront of them - the book has yet to be written (AFAIK) and the site is simply a placeholder.

A great way to get started is to check out the [examples in the repo](https://github.com/iced-rs/iced/tree/master/examples) or the [project showcase](https://github.com/iced-rs/iced/issues/355). FYI, I don't think any of the projects showcased are using the latest and greatest version of Iced (most use 0.3 or 0.4), but they're a good start! [The discord](https://discord.com/invite/3xZJ65GAhd) is also full of people willing to help.

**Comment by hecrj** [comment]
I think you missed this huge warning in the link you mentioned:

![image](https://user-images.githubusercontent.com/518289/209142694-5126e212-f61b-4f52-82d5-b136082da912.png)

In any case, bug reports are for existing functionality of the library. Closing!
