### ISSUE TITLE
Can't close an Application that listenes to an stdin-subscription

### ISSUE THREAD

**Issue by riscygeek** [iced-rs/iced#1680]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

I am trying to listen to stdin and send a Message every time a line is read.
It works, but I can't close the program. I have to send an SIGINT (Ctrl+C) to kill the program.

I am unsure if this issue is related to #1670.

Example code:
```rust
use tokio::io::{stdin, AsyncReadExt};
use iced::{
    widget::{Text, Button, column},
    Application, Element, Settings, Theme, Command, Subscription,
};

struct App {
    s: String,
}

#[derive(Debug, Clone)]
enum Message {
    Update(String),
    Pressed,
}

impl Application for App {
    type Message = Message;
    type Theme = Theme;
    type Executor = iced::executor::Default;
    type Flags = ();

    fn new(_flags: Self::Flags) -> (Self, Command<Message>) {
        (Self { s: "No Content".to_owned() }, Command::none())
    }

    fn title(&self) -> String {
        "Test".to_owned()
    }

    fn update(&mut self, msg: Message) -> Command<Self::Message> {
        use Message::*;
        match msg {
            Update(s) => self.s = s,
            Pressed => println!("pressed"),
        }
        Command::none()
    }

    fn view(&self) -> Element<'_, Message> {
        column![
            Text::new(&self.s),
            Button::new("Wallah").on_press(Message::Pressed),
        ].into()
    }

    fn subscription(&self) -> Subscription<Message> {
        some_worker()
        //Subscription::none()
    }
}

fn some_worker() -> Subscription<Message> {
    struct SomeWorker;
    iced::subscription::unfold(
        std::any::TypeId::of::<SomeWorker>(),
        (),
        |_| async move {
            let mut stdin = stdin();
            let mut buf = [0; 100];
            stdin.read(&mut buf).await.unwrap();
            (Some(Message::Update(String::from_utf8(buf.to_vec()).unwrap())), ())
        }
    )
}

fn main() -> iced::Result {
    App::run(Settings {
        exit_on_close_request: true,
       ..Default::default()
    })
}

```

### What is the expected behavior?

Clicking on the close button closes the program.
Pressing Super+Q (shortcut to close a window) closes the program.

### Version

0.7

### Operative System

Linux

**Comment by schctl** [comment]
I encountered a similar issue a while ago.

After some digging, it looks like this is caused by `tokio::Runtime`'s behavior to wait for all blocking tasks to finish before it drops. And looking at `Stdin`'s implementation, it [does](https://github.com/tokio-rs/tokio/blob/1f50c57185d28a1d118adc22bf587541e3b7edcc/tokio/src/io/blocking.rs#L73-L76) spawn a blocking thread. Alternatively, as an example, using `async_std` in your case seems to work.

```rust
fn some_worker_async_std() -> Subscription<Message> {
    use async_std::io::stdin;
    use async_std::prelude::*;

    struct SomeWorker;
    iced::subscription::unfold(
        std::any::TypeId::of::<SomeWorker>(),
        (),
        |_| async move {
            let mut stdin = stdin();
            let mut buf = [0; 100];
            stdin.read(&mut buf).await.unwrap();
            (Some(Message::Update(String::from_utf8(buf.to_vec()).unwrap())), ())
        }
    )
}
```

I think one possible solution is to add a [`shutdown`](https://github.com/iced-rs/iced/compare/master...schctl:iced:shutdown-runtime) method to `Executor`, but I'm not sure what the go is here.

**Comment by riscygeek** [comment]
> I encountered a similar issue a while ago.
> 
> After some digging, it looks like this is caused by `tokio::Runtime`'s behavior to wait for all blocking tasks to finish before it drops. And looking at `Stdin`'s implementation, it [does](https://github.com/tokio-rs/tokio/blob/1f50c57185d28a1d118adc22bf587541e3b7edcc/tokio/src/io/blocking.rs#L73-L76) spawn a blocking thread. Alternatively, as an example, using `async_std` in your case seems to work.
> 
> ```rust
> fn some_worker_async_std() -> Subscription<Message> {
>     use async_std::io::stdin;
>     use async_std::prelude::*;
> 
>     struct SomeWorker;
>     iced::subscription::unfold(
>         std::any::TypeId::of::<SomeWorker>(),
>         (),
>         |_| async move {
>             let mut stdin = stdin();
>             let mut buf = [0; 100];
>             stdin.read(&mut buf).await.unwrap();
>             (Some(Message::Update(String::from_utf8(buf.to_vec()).unwrap())), ())
>         }
>     )
> }
> ```
> 
> I think one possible solution is to add a [`shutdown`](https://github.com/iced-rs/iced/compare/master...schctl:iced:shutdown-runtime) method to `Executor`, but I'm not sure what the go is here.

Thanks @schctl, now it works.
