### ISSUE TITLE
Cannot compile. "Generic types are unstable"

### ISSUE THREAD

**Issue by DelPyth** [iced-rs/iced#1683]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

When attempting to compile an example, `iced_graphics 0.6.0` within `src\image\storage.rs` on line 12, the compiler states `error[E0658]: generic associated types are unstable`. Attempting to compile will always lead to this error.

### What is the expected behavior?

I expect the error to not happen. Don't really know what else to say.

### Version

master

### Operative System

Windows

### Do you have any log output?

```shell
File path modified for confidentiality.

   Compiling iced_graphics v0.6.0
error[E0658]: generic associated types are unstable
  --> ...\iced_graphics-0.6.0\src\image\storage.rs:12:5
   |
12 |     type State<'a>;
   |     ^^^^^^^^^^^^^^^
   |
   = note: see issue #44265 <https://github.com/rust-lang/rust/issues/44265> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `iced_graphics` due to previous error
```

**Comment by manokara** [comment]
You seem to have an older compiler. GATs where added in [1.65.0](https://blog.rust-lang.org/2022/11/03/Rust-1.65.0.html). Iced is generally being developed on the latest stable Rust version.

**Comment by DelPyth** [comment]
That did fix it and now it is able to compile.


_Side note, holy sh#t this thing is bulky._
