### ISSUE TITLE
Animation bug for text_input in component

### ISSUE THREAD

**Issue by HMingtk** [iced-rs/iced#1684]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

When I run the [example,](https://github.com/iced-rs/iced/tree/master/examples/component) I find that text_input is not animated.

### What is the expected behavior?

text_input should have animation

### Version

0.7

### Operative System

Windows

### Do you have any log output?

```shell
no
```

**Comment by hecrj** [comment]
Thanks for the report!

I just fixed it in #1685.
