### ISSUE TITLE
Access window properties with Command's

### ISSUE THREAD

**Issue by thunderstorm010** [iced-rs/iced#1687]
### Is there an existing issue for this?

- [x] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

For some apps, there's possibly a need to access the window properties at runtime, like window size, position, etc.

Currently, for some properties (like window size and position), you can just assume that the implementation of Default for `iced::window::Settings` is the initial size. This works if you're, for example, using `Application::run(Settings::default())`, but when you need to change the settings, you need to also change them on your application code, and this can cause bugs.

### What is the expected behavior?

There could be an extra action to fetch the current window properties.

### Version

0.7

### Operative System

Linux

**Comment by hecrj** [comment]
This is not a bug. Please, open a discussion instead.
