### ISSUE TITLE
why so huge spacing size between text and toggler

### ISSUE THREAD

**Issue by lost22git** [iced-rs/iced#1752]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

![Screenshot 2023-03-12 092348](https://user-images.githubusercontent.com/65008815/224519441-b277f9a2-b5a8-426e-aab1-3398182b4338.png)

### code
```rust
let content = row(vec![
  toggler(
    Some("dark_mode".to_string()),
    self.dark_mode.unwrap(),
    Message::DarkMode,
  )
  .into()
])
.align_items(iced::Alignment::Center)
.spacing(8);

container(content)
    .style(theme::Container::Transparent)
    .height(Length::Fill)
    .width(Length::Fill)
    .center_x()
    .center_y()
    .into()
```

### What is the expected behavior?

normal spacing size

### Version

master

### Operative System

Windows

**Comment by 13r0ck** [comment]
This is not a bug. The toggler widget fills it's parent. So the space between them expands until it the text and the toggler are touching each side of the parent. If you want to shrink the space, set the parent to be smaller.

```rust
let content = row![
  toggler(
    Some("dark_mode".to_string()),
    self.dark_mode.unwrap(),
    Message::DarkMode,
  )
  .into()
]
.width(Length::Units(30))
.align_items(iced::Alignment::Center)
.spacing(8);
```

**Comment by lost22git** [comment]
@13r0ck  What is the reason for the design of toggler to automatically fill the parent instead of the default size, and which widgets also automatically fill the parent?

**Comment by 13r0ck** [comment]
It depends on the widget. For the toggler, be default width just happens to be [`Length::Fill`](https://github.com/iced-rs/iced/blob/0.8/native/src/widget/toggler.rs#L77)
It's an [easy enough fix](https://github.com/iced-rs/iced/blob/0.8/native/src/widget/toggler.rs#L94).

**Comment by lost22git** [comment]
thanks a lot
