### ISSUE TITLE
Version 0.6.0 fails to build

### ISSUE THREAD

**Issue by blackbit42** [iced-rs/iced#1756]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

I am trying to build https://github.com/0x192/universal-android-debloater which pulls in iced_graphics in version 0.6.0 as a dependency.
```
$ rustc -V
rustc 1.63.0
$ cargo -V
cargo 1.65.0
$ cargo build
   Compiling iced_graphics v0.6.0 (https://github.com/iced-rs/iced.git#18552f96)
   Compiling static_init v1.0.3
   Compiling rustls v0.20.8
   Compiling static_init_macro v1.0.2
   Compiling num-integer v0.1.45
error[E0658]: generic associated types are unstable
  --> /home/blackbit/.cargo/git/checkouts/iced-f01cba4d5e61fd0a/18552f9/graphics/src/image/storage.rs:12:5
   |
12 |     type State<'a>;
   |     ^^^^^^^^^^^^^^^
   |
   = note: see issue #44265 <https://github.com/rust-lang/rust/issues/44265> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `iced_graphics` due to previous error
warning: build failed, waiting for other jobs to finish...
$ 
```

I do not control which version of iced_graphics upstream depends on.

### What is the expected behavior?

It's supposed to build successfully.

### Version

0.7

### Operative System

Linux

### Do you have any log output?

```shell
See above.
```

**Comment by hecrj** [comment]
Can you update Rust? Try `rustup update`.

**Comment by hecrj** [comment]
https://blog.rust-lang.org/2022/10/28/gats-stabilization.html
