### ISSUE TITLE
Suggestion: mouse::Event::Focus, mouse::Event::Blur

### ISSUE THREAD

**Issue by sowbug** [iced-rs/iced#1759]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

I was invited to file an issue by the language at https://docs.rs/iced/latest/iced/mouse/enum.Event.html.

It would be very nice to get focus/blur events for a widget (not for the window). There are `CursorEntered`, `CursorLeft`, and `CursorMoved`, but those are all for the window containing all the widgets. I think I can synthesize the desired logic by tracking mouse movements relative to an in/out widget-boundary test, but it seems like something more people than just me would also use. That's why I'm suggesting these events as a platform feature.

My use case is dragging and dropping one widget onto another. I have enough to get the job done with mouse up/down and boundary in/out, but the focus/blur idiom is a great fit for the UI polish -- highlighting the target when hovering over it, etc.

### What is the expected behavior?

See above.

### Version

master

### Operative System

Linux

**Comment by sowbug** [comment]
I may have just learned something about Iced while prototyping this. "focus" and "blur" imply that the widget retains some state. But I forgot that they're re-created on every `view()`, so they wouldn't have any idea whether the mouse entered or left their boundary; they'd know (at best) only whether it was currently in or out. So maybe this kind of event doesn't make sense in the Iced world.

**Comment by davidclevenger** [comment]
This is something that I would also like to use. My use case may be similar but essentially I would like to be able to show/hide certain elements on hover/exit.


```rust

fn view() -> ... {
...
    text("my text").on_hover(Message::TextHovered);
...
    if self.text_hovered {
        ... add more elements
    }
...
}

```

**Comment by hecrj** [comment]
@davidclevenger This can now be achieved with [the `mouse_area` widget](https://docs.rs/iced/latest/iced/widget/struct.MouseArea.html).
