### ISSUE TITLE
Picklist menu items hide menu border when hovered

### ISSUE THREAD

**Issue by GyulyVGC** [iced-rs/iced#1768]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

The title basically says it all; when hovering on an item from the picklist menu, the menu's border gets covered:

<div align="center">
<img src="https://user-images.githubusercontent.com/100347457/227732047-1bac3238-6401-4b6a-8517-33d8fca17631.png"/>)
</div>

### What is the expected behavior?

The menu border remains visible.

### Version

master

### Operative System

macOS

**Comment by GyulyVGC** [comment]
I think I've found the code lines responsible of this behaviour: https://github.com/iced-rs/iced/blob/c6218cbc5532551456c0491eb5aa66dfc5f36879/native/src/overlay/menu.rs#L478

And it seems made on purpose. 
Any reasons for that?

**Comment by hecrj** [comment]
We are just not accounting for the border width of the background of the menu when rendering the background of the selected option.

I can try to come up with a fix.

**Comment by GyulyVGC** [comment]
Awesome, thanks!

**Comment by hecrj** [comment]
#1831 should fix it.
