### ISSUE TITLE
cursor position is offset

### ISSUE THREAD

**Issue by ua-kxie** [iced-rs/iced#1787]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

drawing a point at the cursor location results in the point being drawn to the lower right of the cursor.

```rust
let c = Path::line(_cursor.position().unwrap_or_default(), _cursor.position().unwrap_or_default());
frame.stroke(&c, thin_stroke());
```
![Capture1](https://user-images.githubusercontent.com/56177821/231331045-2800d93a-4d16-472c-97ef-ce1c988062c8.PNG)

scaling the canvas by changing the window size does not appear to affect the offset amount measured in pixels. Easiest way to replicate this is to paste the code snippet above into the clock example around l128. The code snippet below seems to fix the problem: 

```rust
frame.translate(Vector::new(-20., -20.));
```

using iced version 0.8

### What is the expected behavior?

The point should be drawn at the upper left tip of the cursor pointer by default. 

### Version

master

### Operative System

Windows

**Comment by hecrj** [comment]
Do you have an SSCCE? The coordinates of the mouse cursor are absolute window coordinates, while a `Canvas` uses relative coordinates.

In order to get the proper position, you can use `cursor.position_in(bounds)` where `bounds` are the `bounds` provided to `Program::draw`.

**Comment by hecrj** [comment]
The `clock` example has a `padding` of `20`, which would explain the offset you are experiencing.
