### ISSUE TITLE
Certificate expired for the demo applications

### ISSUE THREAD

**Issue by vn971** [iced-rs/iced#1862]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

certificates (https) is broken for the demo web pages (part of iced README):

- https://gfycat.com/politeadorableiberianmole
- https://gfycat.com/littlesanehalicore

### What is the expected behavior?

https certificates working

### Version

master

### Operative System

Linux

**Comment by hecrj** [comment]
Gfycat fixed the issue.
