### ISSUE TITLE
Excess CPU usage when idle

### ISSUE THREAD

**Issue by adrian5** [iced-rs/iced#1867]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Using the basic ["Hello, world!"](https://docs.rs/iced/latest/iced/trait.Sandbox.html#a-simple-hello-world) example, the iced application frequently engages the CPU despite being idle. This even happens when the window is minimized.

```rust
use iced::{Element, Sandbox, Settings};

pub fn main() -> iced::Result {
    Hello::run(Settings::default())
}

struct Hello;

impl Sandbox for Hello {
    type Message = ();

    fn new() -> Hello {
        Hello
    }

    fn title(&self) -> String {
        String::from("A cool application")
    }

    fn update(&mut self, _message: Self::Message) {
        // This application has no interactions
    }

    fn view(&self) -> Element<Self::Message> {
        "Hello, world!".into()
    }
}
```
###### NOTE: both applications run minimized here
![hello-gui](https://github.com/iced-rs/iced/assets/5426924/a3e5fefd-d35b-46e3-aef5-371f096a9de4)

This doesn't happen with the (now deprecated) `glow` renderer, which behaves like other GUI frameworks (e.g. Qt).

I tried looking into `wgpu` but apparently the examples [aren't coded](https://github.com/gfx-rs/wgpu/issues/3788#issuecomment-1557867533) for efficient idling, whereas I would hope `iced` is.

### What is the expected behavior?

An idle **iced** application shouldn't do any measurable work at cpu-second (down to `0.01`s in `top`) resolution.

### Version

master

### Operative System

Linux

**Comment by hecrj** [comment]
Again, this doesn't seem like an `iced` issue since the `hello-triangle` in `wgpu` exhibits the same behavior for you.
