### ISSUE TITLE
Examples panic in glyphon code

### ISSUE THREAD

**Issue by kaimast** [iced-rs/iced#1876]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

On the master branch, the tour example crashes with the following error: 
```thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/kai/.cargo/git/checkouts/glyphon-70ff9ac92aaa9d8a/f145067/src/text_render.rs:105:30```

### What is the expected behavior?

The example should run.

### Version

master

### Operative System

Linux

### Do you have any log output?

```shell
wgpu examples run fine.

Git bisect tells me that this is the first bad commit: 9b4bcd287a7f4822314e158990d1dc023d5aab51

I am also attaching a full log file.
```

**Comment by kaimast** [comment]
[out.log](https://github.com/iced-rs/iced/files/11575445/out.log)

**Comment by hecrj** [comment]
I believe #1883 should fix the issue.

**Comment by kaimast** [comment]
Thanks! It did fix the problem for me.

(Seems like `cosmic_text` does not find any fonts on my system, which might be why some/all glyphs are missing)
