### ISSUE TITLE
no align text with button on Y axis

### ISSUE THREAD

**Issue by amirhossein-fzl** [iced-rs/iced#1887]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Pay attention to the buttons in the picture. The text inside the button is not in the middle of the Y axis inside the button. Even the placeholder behaves like this with text input.

![image](https://github.com/iced-rs/iced/assets/53816722/04e374f5-031b-4779-8f67-f2d46e0c86f6)

and codes ...

```rust
fn view(&self) -> Element<'_, Self::Message> {
    container(
        column![
            text("Password Generator").size(24).width(Length::Fill),
            column![
                text("Length: "),
                NumberInput::new(self.length, 50, Message::ChangeLength)
                    .style(NumberInputStyles::Default),
            ]
            .spacing(8),
            row![
                text_input(
                    &String::from("password"),
                    &self.password,
                    Message::PassChange
                ),
                button("Copy").on_press(Message::Copy),
            ],
            button("Generate").on_press(Message::Generate)
        ]
        .spacing(30),
    )
    .center_x()
    .center_y()
    .width(Length::Fill)
    .height(Length::Fill)
    .padding(10)
    .into()
}
```

### What is the expected behavior?

I expect the text to be in the middle of the Y axis inside the widget. If it doesn't happen like this, at least functions to personalize this topic should be added to the library...

### Version

master

### Operative System

Linux

### Do you have any log output?

```shell
-
```

**Comment by hecrj** [comment]
Most likely caused by https://github.com/pop-os/cosmic-text/issues/123.

In the meanwhile, you may be able to fix the issue by using a different font or [manually setting the `line_height` of the `Text`](https://docs.iced.rs/iced_core/text/struct.Text.html#structfield.line_height).

**Comment by hecrj** [comment]
Or simply use the latest release `0.9` for now!

**Comment by amirhossein-fzl** [comment]
> Or simply use the latest release `0.9` for now!



> Or simply use the latest release `0.9` for now!

I use version 9. I also told you the reason for the problem ...

**Comment by hecrj** [comment]
> I use version 9

Try `master` then!

> I also told you the reason for the problem ...

You did? Maybe you can fix it yourself as well? PRs welcome!

**Comment by amirhossein-fzl** [comment]
> > I use version 9
> 
> Try `master` then!
> 
> > I also told you the reason for the problem ...
> 
> You did? Maybe you can fix it yourself as well? PRs welcome!

😐
