### ISSUE TITLE
Tooltip's text rendered behind cropped text of neighbouring TextInput

### ISSUE THREAD

**Issue by earshinov** [iced-rs/iced#1891]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

![image](https://github.com/iced-rs/iced/assets/52021/060ae3e6-735d-4530-b520-aab71d808e3d)

The problem occurs only if text of the TextInput is cropped due to this:
https://github.com/iced-rs/iced/blob/ce64dcbfd44b59db36575e92428a7cf9c6f58fc7/widget/src/text_input.rs#L1146

So when TextInput's text is cropped, there are two layers: one with the tooltip and another with TextInput's text. As I see, iced do not order layers (there is no `z-index` in HTML terms), so whichever widget occurs last in the widget tree wins.

I understand that this issue might be just an example of a more general problem with tooltip rendering, see also this: https://github.com/iced-rs/iced/issues/749. However, I think it is is worthy of documenting separately so that people could find it and not spend time wondering if they do something wrong in their own code.

### What is the expected behavior?

Tooltips should be rendered above main window content.

### Version

master

### Operative System

Windows

**Comment by hecrj** [comment]
Fixed by #1692.
