### ISSUE TITLE
Sometimes the last word of a text is not rendered

### ISSUE THREAD

**Issue by blazra** [iced-rs/iced#1933]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Commit [Merge pull request](https://github.com/iced-rs/iced/commit/ef18ecf4ef0fe654578380059b467fe2fb34aa0a) https://github.com/iced-rs/iced/pull/1921 [from iced-rs/subpixel-glyph-positioning](https://github.com/iced-rs/iced/commit/ef18ecf4ef0fe654578380059b467fe2fb34aa0a) introduced a regression where sometimes the last word of a text is not rendered - for example see the last page of the Tour example ("end!" is missing). 
![image](https://github.com/iced-rs/iced/assets/511953/79544cfe-d3f8-4830-bd21-b6b5166d050d)

### What is the expected behavior?

The text is rendered completely.

### Version

master

### Operating System

Linux

**Comment by blazra** [comment]
For another example check the download_progress example: 
![image](https://github.com/iced-rs/iced/assets/511953/650dab99-945a-40db-ae36-453f86fa5402)

**Comment by hecrj** [comment]
I just opened #1933 which should fix the issue. Let me know!

**Comment by blazra** [comment]
https://github.com/iced-rs/iced/pull/1934 fixes the issue for me. Thanks! That was fast.

**Comment by lufte** [comment]
Was this the same as #782?

**Comment by hecrj** [comment]
@lufte Yes.
