### ISSUE TITLE
Multiline text input

### ISSUE THREAD

**Issue by fenhl** [iced-rs/iced#197]
It should be possible to allow line breaks in a text input (probably not by default though).

**Comment by teymour-aldridge** [comment]
That would be cool.

**Comment by aisq2008** [comment]
TextArea

**Comment by teymour-aldridge** [comment]
?

**Comment by dhardy** [comment]
FYI: https://www.reddit.com/r/rust/comments/i9q5nt/kas_gui_toolkit_v05/

Hopefully `kas-text` is suitable for integration into other GUI toolkits too. Though @hecrj may already be working on something?

**Comment by hecrj** [comment]
Closing in favor of #320.
