### ISSUE TITLE
[Native+wgpu] Text not rendered

### ISSUE THREAD

**Issue by Hero9909** [iced-rs/iced#1975]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

switching from 0.9 to master branch results into no rendered text

### What is the expected behavior?

text visible as before or in 0.9

### Version

master

### Operating System

Linux

**Comment by Hero9909** [comment]
might have the same origin as #1974 , but as #1974 is describing the issues on wasm i thought it would be better to create another report as the environments are very different.

**Comment by genusistimelord** [comment]
can you please Give us a source that has the issue being recreated inside of it? As id like to see if this is iced or if its something else.

**Comment by stappersg** [comment]
_there might be dragons_    I seemed to have this issue reproducable and started `git bisect`.  Roughly an hour later I could **not** reproduce the issue.

I think that it is _build_ related.

Those who also want to do a _git bisect_, consider to do more a just `cargo run` between the `git bisect {good|bad}` commands.  Probably `cargo clean`.     I hope this helps others.

**Comment by genusistimelord** [comment]
if you are having any issues I always suggest a cargo clean + cargo update and a rebuild to see if that fixes the issue first. as it could just be lingering build issues.

**Comment by Hero9909** [comment]
Ok, i did a clean build on a minimal example, without components. Works good so far, everything as expected.

Ill expand the code to include a Component implementation. If it still works, ill close this as not reproducable with clean build.

Thanks for the hint so far

**Comment by Hero9909** [comment]
Did a run from latest 0.10 branch with feature lazy.

Everything fine in simple environment. So closed as stated.
