### ISSUE TITLE
Most text characters not rendering

### ISSUE THREAD

**Issue by christofferaakre** [iced-rs/iced#2005]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Most characters do not render when trying to render text. It happens with text widgets, button widgets, etc. The only thing I've been able to find that correctly renders text is the text input. I tried to render just a simple text widget:
```rust
    fn view(&self) -> iced::Element<'_, Self::Message> {
        text("asd123+-=';*").into()
    }

```
, and here is what I get:
![image](https://github.com/iced-rs/iced/assets/31142852/e44b8d7f-4a7b-4877-9f56-8cb12b1af790)

When running the todos example, I get this:
![image](https://github.com/iced-rs/iced/assets/31142852/6e5cae54-6614-450c-85b9-07577b72c414)
As you can see, the button has no text and the spacing looks weird for the text input. If I type into the text input, I see this:
![image](https://github.com/iced-rs/iced/assets/31142852/d44638de-c3f6-4b83-9d0a-ecca0c1ceccc)
Suspiciously, those same characters that actually render for me show up weird here, with what looks like a different font, colour, and spacing. I tried playing around with changing the font, but to no avail.

### What is the expected behavior?

I expected text to render correctly with no problems. I have successfully used iced 0.9 in the past and it worked fine, but 0.10 is broken for me.

### Version

crates.io release

### Operating System

Linux

**Comment by christofferaakre** [comment]
Update: switching to 0.9 fixes the issue, but I want to use 0.10 because I need the new font-shaping capability. Anyone have any pointers on how to troubleshoot this?

**Comment by genusistimelord** [comment]
have you tried to see if this renders correctly with the master branch?

**Comment by christofferaakre** [comment]
@genusistimelord Thank you for the suggestion; it doesn't unfortunately. I see the issue both on master and the 0.10 tag, but the 0.9 tag works as expected

**Comment by genusistimelord** [comment]
what font size do you have it set as and can you try reducing it? or what Font do you have set is it default or did you set one yourself.

**Comment by christofferaakre** [comment]
in my hello world example, I was uing the default font/size. I tried setting the font size to 5, and then 100, but nothing changed (other than the text being bigger obviously). I tried using a font like this:
```rust
Font {
            family: iced::font::Family::SansSerif,
            monospaced: false,
            ..Default::default()
     }
```
, also with `monospaced: true`, and with `Serif` and `Monospace` for the family, same result for all of them. As for the todos example I have tried, as far as I can tell it uses the default font as well as an icons.ttf for icons.

**Comment by genusistimelord** [comment]
ok thank you this should give some more details for Hector to look into closer.

**Comment by kaimast** [comment]
I have had this issue on Arch Linux as well since iced moved to `cosmic-text`.

**Comment by turai** [comment]
I can also confirm. Capture attached.

[font_issue.zip](https://github.com/iced-rs/iced/files/12327324/font_issue.zip)

**Comment by genusistimelord** [comment]
this one had a Error in the draw call of no vertex shader bound at a draw call. hmm

**Comment by turai** [comment]
I was investigating the misaligned '3' I shown on discord yesterday, turns out using Font::MONOSPACE makes it all disappear.
![Screenshot from 2023-08-13 06-37-46](https://github.com/iced-rs/iced/assets/1094872/e5a15911-0d49-44ba-ac98-db66f9f9feb2)
![image](https://github.com/iced-rs/iced/assets/1094872/76bae303-9da2-47c1-9905-81e4a433f43c)
[captures.zip](https://github.com/iced-rs/iced/files/12328824/captures.zip)

**Comment by genusistimelord** [comment]
OK so I know there was a issue with the wgpu crate and it did have a patch release. So can you try to run cargo update OR use the master branch and see if these issue's still occur?

**Comment by turai** [comment]
Nothing changed, still broken.

**Comment by realDelta2** [comment]
Yep, I am having this exact issue too. I thought it was a nixos issue at first.

**Comment by turai** [comment]
No, it's related to swash failing to parse the font: https://discord.com/channels/628993209984614400/1136639744890114128
Use a different one, preferably ttf as a workaround.

**Comment by genusistimelord** [comment]
@christofferaakre  have you tried enforcing the font to be of one that is a TTF font in the system? Just curious if that fixes the issues. as we found out the GTK fonts have loading issues which cause things to not work right due to them not being supported. So was thinking maybe the rendering issues or missing characters could also be caused by something similar.

**Comment by martinhalford** [comment]
Hi team,  FYI... I'm having the same issue too, using 0.10.0.  The UI renders fine when deployed as a desktop app but I get the same issue when deploying as a web app.

Try replicating this for the "todos" example in the iced repo

```
cd iced/
cargo run --package todos
```
You get this...
![image](https://github.com/iced-rs/iced/assets/970336/b871a7fd-bddc-4626-9e54-8033e950cfb4)

Now try this...

```
cd iced/examples/todos
trunk build
trunk serve --open
```
You get this...
![image](https://github.com/iced-rs/iced/assets/970336/00c035b5-60f5-464c-ad55-964f7476e449)

```
cat cargo.toml
[package]
name = "todos"
version = "0.1.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
iced = { path = "../..", features = ["async-std", "debug"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.15"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-std = "1.0"
directories-next = "2.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["Window", "Storage"] }
wasm-timer = "0.2"

[package.metadata.deb]
assets = [
    ["target/release-opt/todos", "usr/bin/iced-todos", "755"],
    ["iced-todos.desktop", "usr/share/applications/", "644"],
]
```

**Comment by genusistimelord** [comment]
it might be loading a default font that cant be used due to not being supported. Also when you have these issues Please try to force tiny_skia rendering to see if it fixes the issue or not.

**Comment by martinhalford** [comment]
@genusistimelord - I forced `tiny_skia` and got the following render.

![image](https://github.com/iced-rs/iced/assets/970336/8a2d91a5-8ba3-48e1-88b8-1ef59db145e9)

This is the cargo.toml used:
```
[package]
name = "todos"
version = "0.1.0"
authors = ["Héctor Ramón Jiménez <hector0193@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
iced = { path = "../..", features = ["async-std", "debug"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.15"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-std = "1.0"
directories-next = "2.0"

[dependencies.iced_tiny_skia]
version = "0.1"
path = "../../tiny_skia/"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["Window", "Storage"] }
wasm-timer = "0.2"

[package.metadata.deb]
assets = [
    ["target/release-opt/todos", "usr/bin/iced-todos", "755"],
    ["iced-todos.desktop", "usr/share/applications/", "644"],
]

```

**Comment by kaimast** [comment]
Can we use a separate issue for WebAssembly?  It seems to be related but is not the same bug.

[This issue](https://github.com/iced-rs/iced/issues/1900) was already reported a while ago.

**Comment by martinhalford** [comment]
@kaimast @genusistimelord - it certainly seems to be a web assembly issue, since it works fine in desktop. 

However, I'm a bit perplexed as to why the fixation on fonts? It looks more widespread than just a font issue. (Might be wrong. Just looks to be affecting other components too.)

**Comment by genusistimelord** [comment]
its hard to tell really. not sure what fonts its using on the web side nor what OS its affected on since each OS has its own set of fonts. We just have had issues with loading certain fonts which have caused rendering issues. Generally why I asked. so if the Web side is loading these certain fonts then it could prevent it from rendering. 

Also the other thing is to make sure your Iced wgpu and tiny-skia libs are fully up to date as in the first release there was a issue that got fixed due to layering.  So if you could do a Cargo clean + Cargo update and then try it that also would be nice since it guarantees its all up to date.

**Comment by martinhalford** [comment]
@genusistimelord - I've done a `cargo clean` and a `cargo update`. I've even done a `cargo install trunk --force` and tried compiling the code using both the stable `rustc 1.71.0 (8ede3aae2 2023-07-12)` and nightly `rustc 1.73.0-nightly (07438b092 2023-08-16)` builds.  The issue still remains.

I tested using Microsoft Edge and Safari - the bug presents slightly differently in each browser.  However, it does look more like a font issue on Safari, whereas Edge has more challenges.

See video for details: [Loom video](https://www.loom.com/share/6355163a06ea476d8b3aea3c9edb3cdf)

```
cargo 1.71.0 (cfd3bbd8f 2023-06-08)
trunk 0.17.3
rustc 1.71.0 (8ede3aae2 2023-07-12)
macOS 13.5 (22G74)
```

**Comment by kaimast** [comment]
For people who have this issue, could you test whether cosmic-text works fine for you? I reported a while ago [here](https://github.com/pop-os/cosmic-text/issues/148) that even their examples do not find any fonts for me.

**Comment by martinhalford** [comment]
@genusistimelord @kaimast - I've added a [comment](https://github.com/iced-rs/iced/issues/1900#issuecomment-1684718196) to issue 1900.

**Comment by ph** [comment]
Hello, I've been hit by the invisible text mentioned above using either the master or the stable release of this crate.
I've investigated the issue and I was able to find why it doesn't work for everyone, at least why it doesn't work for me.
Some context, I am running Guix Linux which is a transactional distribution, you might be more familliar to NixOS,
which uses the same concepts.

In simplier terms, both distribution uses a different file structures than the common HFS, multiples symlinks are used
to make application or support file font available to the end user. The system mainly relies on fontconfig to ensure
that all the fonts are picked up correctly by GUI application.

Looking at the history of this project, it was recently updated to use cosmic-text, that library uses the crate `fontdb`
to generalize the access of the fonts on the different operating system. By default the libary on Linux based system 
look for font in the following directories:

-  /usr/share/fonts/
- /usr/local/share/fonts/
- $HOME/.fonts
- $HOME/.local/share/fonts

On the other hand Guix (I don't remember NixOS' installation path) install them in `~/.guix-home/profile/share/fonts/` 
and it updates fontconfig configuration with the path.

By default fontdb doesn't use fontconfig, see https://github.com/RazrFalcon/fontdb/blob/master/src/lib.rs#L392-L407, there an open issue https://github.com/RazrFalcon/fontdb/issues/56 that suggest enabling it by default.

Looking at the `cosmic-text` repository, the `fontconfig` feature was just enabled in https://github.com/pop-os/cosmic-text/pull/174 but
there are no official release of the library that include the change.


If you update iced to use the `main` branch of `cosmic-text`, it correctly find the font to render.

So for now the possible solution are:

- Pin iced-rs' to a commit that include the fix.
- Ask the cosmic's team to push a new official release and update this project dependencies.

I hope it help other people.

**Comment by genusistimelord** [comment]
They did get the changes requested though but have not updated the crate yet. the fixes do help with any none wasm based applications to load fonts correctly.  If you are using WASM with iced just note that you must manually load all the fonts you need.

**Comment by rijkvp** [comment]
Thanks @ph, I fixed this on NixOS by changing the `cosmic-text` dependency to the following in `tiny_skia/Cargo.toml`:
```toml
cosmic-text = { git = "https://github.com/pop-os/cosmic-text", branch = "main" }
```

**Comment by gurinderu** [comment]
Still have the same issue in the main branch
