### ISSUE TITLE
Two buttons placed next to each other can both be clicked at the same time

### ISSUE THREAD

**Issue by veniamin-ilmer** [iced-rs/iced#2010]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

If you place two buttons next to each other, you can place the cursor in between the two, and both will be highlighted. If you click, both buttons will receive the `on_press` command. This happens in both GPU and CPU rendering.

This is problematic for my minesweeper game, composed of many buttons touching each other.

My current workaround is to place a space between each button.

### What is the expected behavior?

It should not be possible for the cursor to be touching both buttons at the same time. It should be either one or the other.

### Version

crates.io release

### Operating System

Windows

**Comment by genusistimelord** [comment]
sounds like the bounds of the buttons are overlapping somehow? could you display a photo of this occurring or a video? any example code that can recreate the problem in a small test that we could run?

**Comment by veniamin-ilmer** [comment]
Take a look:

![Screen recording](https://github.com/iced-rs/iced/assets/39828997/3fb53a47-dd7c-4d99-8653-3dca848332b6)

You can feel free to test it out with an old version of my code here:

https://github.com/veniamin-ilmer/minesweeper/tree/801a78513b7b3b1871c0c2e80f250b86230bbbc5

The buttons are just lined up next to each other with columns and rows.

**Comment by genusistimelord** [comment]
ok I have pushed a PR that fixes this issue. Please give it a try. it is located here https://github.com/iced-rs/iced/pull/2017
