### ISSUE TITLE
button::StyleSheet trait has a docs problem

### ISSUE THREAD

**Issue by solaris5000** [iced-rs/iced#2012]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Cannot change style of button

   ```
 let disabled = Color {r : 1.0, g:0.0, b:0.0, a: 1.0};
let enabled = Color {r : 0.0, g:1.0, b:0.0, a: 1.0};
let disabled_button_style = ButtonColor {color : disabled};

button_disconnect = button_disconnect.style(disabled_button_style);
```

and implementing trait for ButtonColor

```
struct ButtonColor {
    color : iced::Color,
}

impl iced::widget::button::StyleSheet for ButtonColor 
{
    type Style = iced::widget::button::Appearance;
    fn active(&self, style: &Self::Style) -> widget::button::Appearance {
        widget::button::Appearance { background : Some(Background::Color(self.color)), ..Default::default() }
    }
}
```

### What is the expected behavior?

as i saw in [https://docs.iced.rs/iced/widget/button/trait.StyleSheet.html](https://docs.iced.rs/iced/widget/button/trait.StyleSheet.html) i must impl this trait for some color struct to pass style into button

### Version

crates.io release

### Operating System

Windows

**Comment by genusistimelord** [comment]
so yeah the way you would do this is exactly how we do it for the custom scroll bar colors in the iced_aw example for split scroller 
https://github.com/iced-rs/iced_aw/blob/main/examples/split_scroller/src/main.rs#L495

you create the new color Appearance for the widget and then apply it like
https://github.com/iced-rs/iced_aw/blob/main/examples/split_scroller/src/main.rs#L454
using the custom of the widgets style enum. practically all widgets in iced have a custom setting. 

The other way to do this is to just use the predefined Styles in the buttons style enum which are located in the theme.rs
https://github.com/iced-rs/iced/blob/master/style/src/theme.rs#L126

each of these are predefined colors and shift when in dark or light mode too.

**Comment by hecrj** [comment]
Not a bug. Plenty of examples use custom button colors.
