### ISSUE TITLE
[feat] inspect UI elements information and work for UI automation testing frameworks

### ISSUE THREAD

**Issue by lost22git** [iced-rs/iced#2023]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

I want to  use [appium-inspector](https://github.com/appium/appium-inspector)  to inspect iced app elements to get xpath, but it can not get them. (both glow and wgpu example)

![Screenshot 2023-08-14 133819](https://github.com/iced-rs/iced/assets/65008815/cd8c6a3b-388e-4b10-b406-153c5df0787c)

### What is the expected behavior?

can get elements info and work for UI automation frameworks (like [appium](https://github.com/appium/appium) with [WinAppDriver](https://github.com/microsoft/WinAppDriver))

### Version

crates.io release

### Operating System

Windows

**Comment by hecrj** [comment]
Not a bug, simply not supported. See #552.
