### ISSUE TITLE
Update to wgpu 0.17

### ISSUE THREAD

**Issue by kaimast** [iced-rs/iced#2053]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Wgpu 0.17 has been out for [over a month](https://github.com/gfx-rs/wgpu/releases/tag/v0.17.0).

### What is the expected behavior?

It would be great if the parts of iced using it could be upgraded.

### Version

master

### Operating System

Linux

**Comment by dtzxporter** [comment]
+1 I would like to see patch updates start to update deps at the least. A release+lto build in rust fails to load wgpu bitcode when you have conflicting versions of wgpu in your dep tree, so it forces all packages to manually downgrade to the lowest version.
