### ISSUE TITLE
Can't use backend-agnostic third party libraries since version 0.10

### ISSUE THREAD

**Issue by Davidster** [iced-rs/iced#2061]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

I am writing a wgpu app with an iced overlay. In order to achieve this, I followed the same setup as the integration example. This worked fine under iced 0.9 and I was able to integrate the `plotters-iced` crate, but since 0.10 this integration failed.

I have already discussed this with `plotters-iced` as can be seen here: https://github.com/Joylei/plotters-iced/issues/29.

I created a [repo](https://github.com/Davidster/plotters-iced-repro-case) that reproduces the issue by simply copying the integration example and adding `plotters-iced`, just uncomment [line 65 in chart.js](https://github.com/Davidster/plotters-iced-repro-case/blob/82531bbed53c6d93a61c9907fdd117abcb5ad39a/src/chart.rs#L65) to see the compiler error that is produced.

Since the `impl Program` setup used in the integration example requires the user to specify which backend you're using (wgpu in my case), it will naturally fail with any third party libraries that rely on traits that they implement for the general `iced::Renderer` type, rendering them unusable.

Obviously, this issue is preventing me from upgrading iced in my project, which also means I cannot upgrade winit nor wgpu until it is fixed unless I drop `plotters-iced`.

### What is the expected behavior?

We should be able to use such libraries with the `impl Program` flow

### Version

crates.io release

### Operating System

Linux

**Comment by MartensCedric** [comment]
I am affiliated with this individual and experience the same issue

**Comment by Davidster** [comment]
I was able to get it working by using this approach: https://github.com/Joylei/plotters-iced/issues/29#issuecomment-1703388377
