### ISSUE TITLE
scrollable set to Both, the horizontal bar doesn't compensate for the width of the vertical bar, and vertical doesn't compensate for the height. rendering outside the left bounds.

### ISSUE THREAD

**Issue by dtzxporter** [iced-rs/iced#2083]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

See the title, and this gif from another widget where you can see the horizontal bar being broken.

(Set scrollable to both, 16.0 width on each, and watch it fail to compensate)

(Broken on any version as far as I can tell)
![demo1](https://github.com/iced-rs/iced/assets/22282241/d11d3f84-4852-4ea8-b144-32378d260f1e)

### What is the expected behavior?

Scrollbar logic should work on both.

### Version

crates.io release

### Operating System

macOS

### Do you have any log output?

```shell
N/A
```

**Comment by dtzxporter** [comment]
To add: the vertical bar also isn't compensated (overflows top)

Which means the end of the scrollable contents is not visible when scrolled to bottom:

![image](https://github.com/iced-rs/iced/assets/22282241/32547d32-b69e-4b35-9bc0-90daba68aa55)

**Comment by hecrj** [comment]
> Which means the end of the scrollable contents is not visible when scrolled to bottom:

The bars are overlaid on top of the content, so you need to add some `Padding` on the content to avoid that issue.

**Comment by dtzxporter** [comment]
> > Which means the end of the scrollable contents is not visible when scrolled to bottom:
> 
> The bars are overlaid on top of the content, so you need to add some `Padding` on the content to avoid that issue.

That's fine, it does add a lot of extra logic the user has to implement, but that is easily to work around.

My final response is: 
![image](https://github.com/iced-rs/iced/assets/22282241/17cc14f0-bdf0-44a7-b636-300858d3058b)

The empty space between the two scroll bars _needs_ to be a filled quad. Ideally, one the user can provide in Theme, because otherwise the content bleeds through and looks bad :)
