### ISSUE TITLE
The URL of an image in `PaneGrid` docs is broken

### ISSUE THREAD

**Issue by TonalidadeHidrica** [iced-rs/iced#2094]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

The URL of an image in `PaneGrid` docs is broken.

<img width="1024" alt="image" src="https://github.com/iced-rs/iced/assets/47710717/c51bdbb5-c54c-46c9-9424-c6d70abb743b">

### What is the expected behavior?

There should be an image.

### Version

crates.io release

### Operating System

Windows

**Comment by hecrj** [comment]
This is fixed in `master`: https://docs.iced.rs/iced/widget/pane_grid/struct.PaneGrid.html
