### ISSUE TITLE
iced_lazy 0.6 incompatible with latest iced 0.10

### ISSUE THREAD

**Issue by OBorce** [iced-rs/iced#2097]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Tried updating iced from 0.9 to 0.10 and there is no newer version of iced_lazy

### What is the expected behavior?

to have a new version of iced_lazy that is compatible with iced 0.10

### Version

crates.io release

### Operating System

Windows

**Comment by hecrj** [comment]
`iced_lazy` is included in `iced` now; simply enable the `lazy` feature.
