### ISSUE TITLE
Migrate to Tao, a fork of winit that's better supported.

### ISSUE THREAD

**Issue by dtzxporter** [iced-rs/iced#2098]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Winit has some bugs on certain platforms that have been open for years, Tao is a fork of winit that is better maintained.

### What is the expected behavior?

Window logic just works & is panic free.

### Version

master

### Operating System

Windows

### Do you have any log output?

```shell
N/A
```

**Comment by hecrj** [comment]
Issues are for bug reports!

We have plans to explore [`glazier`](https://github.com/linebender/glazier). It's in the roadmap.
