### ISSUE TITLE
Game of Life example does not compile

### ISSUE THREAD

**Issue by sdasda7777** [iced-rs/iced#2112]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

I don't think this is an issue with the example, but rather it's dependency, but since it doesn't seem to have GitHub repo, I'm not sure what else to do.

I wanted to run the Game of Life example using `cargo run --package game_of_life`. Looked promising, but after some time I got:

```
   Compiling tracing-attributes v0.1.26
error[E0659]: `palette` is ambiguous
 --> style\src\theme.rs:4:9
  |
4 | pub use palette::Palette;
  |         ^^^^^^^ ambiguous name
  |
  = note: ambiguous because of multiple potential import sources
  = note: `palette` could refer to a crate passed with `--extern`
  = help: use `::palette` to refer to this crate unambiguously
note: `palette` could also refer to the module defined here
 --> style\src\theme.rs:2:1
  |
2 | pub mod palette;
  | ^^^^^^^^^^^^^^^^
  = help: use `self::palette` to refer to this module unambiguously

For more information about this error, try `rustc --explain E0659`.
error: could not compile `iced_style` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
PS iced>
```

### What is the expected behavior?

I would expect the example to compile, perhaps even run.

### Version

master

### Operating System

Windows

**Comment by hecrj** [comment]
Update your Rust toolchain!

**Comment by lufte** [comment]
I just want to add that this single line (`pub use palette::Palette;`) is the only thing preventing iced from compiling under rust 1.70.0, which is the latest version available in Debian right now. I no other breaking change is going to be introduced, could this one be reverted for the sake of Debian users?
