### ISSUE TITLE
The Cargo.toml file is broken

### ISSUE THREAD

**Issue by pjc5712** [iced-rs/iced#2114]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

I cloned the repository, moved it to my desktop, and ran cargo run --package tour. Here is the output:
error: failed to parse manifest at `/home/jet_mouse/Desktop/iced/Cargo.toml`

Caused by:
  invalid type: map, expected a sequence for key `package.authors`

Then I tried running cargo run, and I got the same output

### What is the expected behavior?

I expected a gui to show up so I could mess around with it and see if it'll work for my project

### Version

master

### Operating System

Linux

### Do you have any log output?

```shell
error: failed to parse manifest at `/home/jet_mouse/Desktop/iced/Cargo.toml`

Caused by:
  invalid type: map, expected a sequence for key `package.authors`
```

**Comment by pjc5712** [comment]
I realized I should have mentioned, after doing a simple "sudo apt install cargo" I have version 1.46.0, and I'm using Debian 11

**Comment by aylamz** [comment]
That's quite old. You should try using a more up to date Cargo version. Using https://rustup.rs/ is recommended to get up to date versions of Rust tools.
