### ISSUE TITLE
pane_grid::content::Content::title_bar requires argument to be Copy

### ISSUE THREAD

**Issue by nacl42** [iced-rs/iced#2127]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

I tried to implement a PaneGrid into my application using the example code (`pane_grid/src/main.rs`).

The relevant code snippet from the iced pane grid example looks like this:

```rust
            let title_bar = pane_grid::TitleBar::new(title)
                .controls(view_controls(
                    id,
                    total_panes,
                    pane.is_pinned,
                    is_maximized,
                ))
                .padding(10)
                .style(if is_focused {
                    style::title_bar_focused
                } else {
                    style::title_bar_active
                });

           pane_grid::Content::new(responsive(move |size| {
                view_content(id, total_panes, pane.is_pinned, size)
            }))
            .title_bar(title_bar)
            .style(if is_focused {
                style::pane_focused
            } else {
                style::pane_active
            })
```

The corresponding Message enum is both Copy + Clone.

Up to now I had the impression that any Message enum must be only Cloneable. However, the title_bar function requires its argument to be Copy as well.

The corresponding code from `widget::pane_grid::content`, which is responsible for this behaviour, looks like this:

```
    /// Sets the [`TitleBar`] of this [`Content`].
    pub fn title_bar(
        mut self,
        title_bar: TitleBar<'a, Message, Renderer>,
    ) -> Self {
        self.title_bar = Some(title_bar);
        self
    }
```

Is that really the expected behaviour? This would imply that it is not possible to have a Message enum with a String, such as the following:

```rust
#[derive(Debug, Clone)]
pub enum Message {
    TitleChanged(String),
}
```

Would it be possible to change the above code for `title_bar` to simply clone the function parameter?

### What is the expected behavior?

Message must only be Clone-able, i.e. `#[derive(Debug, Clone)` should be sufficient for any Message enum.

### Version

master

### Operating System

Linux

### Do you have any log output?

```shell
error[E0507]: cannot move out of `title_bar`, a captured variable in an `Fn` closure
   --> src/main.rs:310:24
    |
305 | ...et title_bar = pane_grid::TitleBar::new(title);
    |       --------- captured outer variable
306 | ...et pane_grid = PaneGrid::new(&self.panes, |id, pane, is_maximized| {
    |                                              ------------------------ captured by this `Fn` closure
...
310 | ...   .title_bar(title_bar)
    |                  ^^^^^^^^^ move occurs because `title_bar` has type `TitleBar<'_, Message>`, which does not implement the `Copy` trait
```

**Comment by hecrj** [comment]
Have you tried using `move`?

```rust
let pane_grid = PaneGrid::new(&self.panes, move |id, pane, is_maximized| {
    // ...
});
```

**Comment by nacl42** [comment]
This was indeed an issue on my side, not an issue of this wonderful library. I had read my own code over and over again, but wasn't able to find it and interpret the error message correctly, even though today it was quite obvious to me. The suggested `move` syntax was not the solution, but it was a good hint: The `title_bar` in my code was actually defined outside the closure. So my issue was actually a (rather obvious) mistake on my side.

Thank you so much for your prompt reply and keep up the good work!
