### ISSUE TITLE
cant convert iced_aw::Element to iced::Element

### ISSUE THREAD

**Issue by Sniper10754** [iced-rs/iced#2128]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

I was trying to use the `iced_aw`'s `MenuBar`, when 
pushing the menubar to a column i got this error: 
```rs
error[E0277]: the trait bound `iced_core::element::Element<'_, _, _>: From<MenuBar<'_, _, _>>` is not satisfied
   --> src/ui.rs:130:9
    |
130 |         column![menu_bar, tabs].into()
    |         ^^^^^^^^^^^^^^^^^^^^^^^ the trait `From<MenuBar<'_, _, _>>` is not implemented for `iced_core::element::Element<'_, _, _>`
    |
    = help: the following other types implement trait `From<T>`: <Cut Garbage from rustc>
```
with the following code: 
```rs
        let menu_bar = menu_bar!();
        let mut tabs = row![];

        for tab in self.tabs.1.iter() {
            let title = match tab.1 {
                Tab::File(title, _) => title
                    .to_str()
                    .unwrap_or("File contains non-utf8 characters"),
                Tab::Buffer(_) => "Title",
            };

            let tab = row![Text::new(title), Button::new("X")];

            tabs = tabs.push(tab);
        }

        column![menu_bar, tabs].into()
```

### What is the expected behavior?

Be able to convert `iced_aw::Element` into `iced::Element`

### Version

master

### Operating System

Linux

**Comment by Sniper10754** [comment]
Previously i had in my cargo.toml ```toml
[dependencies]
iced = { git = "https://github.com/iced-rs/iced", branch = master }
iced-aw = "0.7"
```
Issue can be resolved by ```toml
iced = "0.10"
```,
the main disadvantage in my case is not having the text editor widget in the main branch, looking for solutions

**Comment by genusistimelord** [comment]
I have been looking into promoting a beta branch for iced_aw that will be up to date with the current master branch of iced, But I am having similar issue atm with iced_aw itself not being compatible with the current iced master....
