### ISSUE TITLE
no option to load image from memory with non static live time

### ISSUE THREAD

**Issue by LuckyTurtleDev** [iced-rs/iced#2167]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Because of #2166 I have try to impl my one caching to load images to the memory first, before I using them. But I notify that the [`form_memory` ](https://docs.rs/iced/latest/iced/widget/image/struct.Handle.html#method.from_memory) needs static live time. I would if it would be possible to use at least something like `Arc` here?

### What is the expected behavior?

non static param

### Version

crates.io release

### Operating System

Linux

**Comment by hecrj** [comment]
It should be possible after #1551.

I recommend you to cache handles directly and cloning those in `view`.

**Comment by LuckyTurtleDev** [comment]
Thanks for the fast answer. Apparently I have mistake static type and static live time.
Since `Handle` use `Arc` intern it should be cheap to clone.
