### ISSUE TITLE
How to use skia at runtime?

### ISSUE THREAD

**Issue by wiiznokes** [iced-rs/iced#2176]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

I always forget what env variable need to be set to use tiny_skia at runtime. It would be nice to add it to the readme or somewhere else.

### What is the expected behavior?

*

### Version

crates.io release

### Operating System

Windows

**Comment by GyulyVGC** [comment]
ICED_BACKEND=tiny-skia
