### ISSUE TITLE
examples - todo - palette is ambiguous

### ISSUE THREAD

**Issue by prometheus-8** [iced-rs/iced#2179]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

I've clone the repository `git clone https://github.com/iced-rs/iced.git` and tried to run the **todos** examples with `cargo run --package todos` but I got the following error message: ```error[E0659]: `palette` is ambiguous```.

### What is the expected behavior?

Expectation here was to run the **todos** example without any errors (just like the **tour** example did)

### Version

crates.io release

### Operating System

Linux

### Do you have any log output?

```shell
Compiling iced_wgpu v0.12.0 (/home/my-user/Projects/iced/wgpu)
   Compiling iced_style v0.12.0 (/home/my-user/Projects/iced/style)
   Compiling window_clipboard v0.3.0
   Compiling overload v0.1.1
   Compiling winit v0.28.6 (https://github.com/iced-rs/winit.git?rev=c52db2045d0a2f1b8d9923870de1d4ab1994146e#c52db204)
   Compiling rand_chacha v0.3.1
   Compiling tracing-log v0.2.0
   Compiling sharded-slab v0.1.7
error[E0659]: `palette` is ambiguous
 --> style/src/theme.rs:4:9
  |
4 | pub use palette::Palette;
  |         ^^^^^^^ ambiguous name
  |
  = note: ambiguous because of multiple potential import sources
  = note: `palette` could refer to a crate passed with `--extern`
  = help: use `::palette` to refer to this crate unambiguously
note: `palette` could also refer to the module defined here
 --> style/src/theme.rs:2:1
  |
2 | pub mod palette;
  | ^^^^^^^^^^^^^^^^
  = help: use `self::palette` to refer to this module unambiguously

   Compiling nu-ansi-term v0.46.0
   Compiling dirs-sys-next v0.1.2
For more information about this error, try `rustc --explain E0659`.
error: could not compile `iced_style` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by prometheus-8** [comment]
Should this line https://github.com/iced-rs/iced/blob/master/style/src/theme.rs#L4 be converted to: `pub use self::palette::Palette;` ?

**Comment by hecrj** [comment]
We only offert support the latest Rust stable toolchain! Try updating it with `rustup update`.
