### ISSUE TITLE
Black rectangles instead of images when using the wgpu GLES backend

### ISSUE THREAD

**Issue by blazra** [iced-rs/iced#2180]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

![image](https://github.com/iced-rs/iced/assets/511953/9c2ab02a-3360-41ee-b949-65d3f3cecdd5)

You get black rectangles instead of images if the wgpu GLES backend is used.

Reproduced under Linux with:
- Apple M1 Pro (asahi) - GLES is the default, because there is no Vulkan driver yet
- Intel Xe - by setting `WGPU_BACKEND=gl`
- AMD Radeon Vega - by setting `WGPU_BACKEND=gl`

I have tracked it to this wgpu issue: https://github.com/gfx-rs/wgpu/issues/1614

I have tried this https://github.com/gfx-rs/wgpu/issues/4665#issuecomment-1806012977 workaround - forcing the Atlas to start with 2 layers - and it fixes the issue (at least for the sake of confirming that it's this specific wgpu problem).

Probably the same issues: 

- https://github.com/iced-rs/iced/issues/1898
- https://discord.com/channels/628993209984614400/1188197273339973662 
- https://discourse.iced.rs/t/images-arent-properly-loading/84

### What is the expected behavior?

The images are shown the same way as with other backends.

### Version

master

### Operating System

Linux

**Comment by elevenhsoft** [comment]
I can confirm this bug. Currently I'm running MicroOS Aeon and I noticed that, when I run my app compiled on ubuntu container and run from there, (i guess it's vulkan backend?) it's running fine. But when the same app is running from host OS the images are black. Also I noticed something interesting related. Here is a short video explaining it: 

https://github.com/iced-rs/iced/assets/114903054/f9479cec-b788-4c05-94d3-1d7081c78004
