### ISSUE TITLE
Web/Wasm targetted code does not render text

### ISSUE THREAD

**Issue by moekhalil** [iced-rs/iced#2181]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

I have searched and searched for any reason or fix for this issue with no luck.

Unfortunately, no matter what I try, when targetting wasm32, the application doesn't render any text.

The code for this app is exactly as is the counter example, but no matter what, text isn't rendered.

this is how I build it:

```
cargo build --target wasm32-unknown-unknown;
wasm-bindgen.exe .\target\wasm32-unknown-unknown\debug\rustapp.wasm --out-dir .\dist\ --web;
npx serve -p 8080;
```
When targetting windows, it works fine, but wasm it just looks like this:  [Example is of basic "/examples/Counter" app]

### Windows:
<img width="543" alt="rustapp_Je5WxHBQgt" src="https://github.com/iced-rs/iced/assets/5835530/5f361606-ce66-43c3-89ff-2f2e4acd22fe">

### Web:
<img width="529" alt="msedge_4KpqruqJyd" src="https://github.com/iced-rs/iced/assets/5835530/810d6824-0ccb-4289-af3e-4f489629b4f2">

### Here is all the code for the app:

```rust
use iced::widget::{column, text};
use iced::widget::{Button};
use iced::{Alignment, Element, Sandbox, Settings, Font};

struct Counter {
    // The counter value
    value: i32,
}

#[derive(Debug, Clone, Copy)]
pub enum Message {
    IncrementPressed,
    DecrementPressed,
}

fn button<'a, Message: Clone>(label: &str) -> Button<'a, Message> {
    Button::new(text(label).horizontal_alignment(iced::alignment::Horizontal::Center))
        .padding(12)
        .width(100)
}

impl Sandbox for Counter {
    type Message = Message;

    fn title(&self) -> String {
        String::from("Moes Iced Counter")
    }

    fn new() -> Self {
        Self { value: 0 }
    }

    fn view(&self) -> Element<Message> {
        column![
            button("INCREMENT").on_press(Message::IncrementPressed),
            text("current sum: ").size(50),
            text(self.value).size(50),
            button("DECREMENT").on_press(Message::DecrementPressed),
        ]
        .padding(20)
        .align_items(Alignment::Center)
        .into()
    }

    fn update(&mut self, message: Message) {
        match message {
            Message::IncrementPressed => {
                self.value += 1;
            }
            Message::DecrementPressed => {
                self.value -= 1;
            }
        }
    }
   

}


pub fn main() -> iced::Result {
    println!("Hello, world!");
    println!("format {} arguments", "some");
    let some = "passed-arg!";
    println!("passed arg: {some}");

    let settings = Settings {
        default_font: Font::MONOSPACE,
        ..Settings::default()
    };

    Counter::run(settings)
}

```

### What is the expected behavior?

Text is to be rendered inside the buttons and the counter should show up as it does in Windows.

### Version

crates.io release

### Operating System

Windows

**Comment by brianch** [comment]
I think the reason is explained here https://github.com/iced-rs/iced/issues/1974#issuecomment-1764964311
