### ISSUE TITLE
rust-analyzer never stops scanning the project files

### ISSUE THREAD

**Issue by mschnell1** [iced-rs/iced#2183]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

to investigate iced, I cloned the repository and tried opening it in VSCoed on Windows. 
This does not decently worl, as the rust-analyzer (I did do "rustup update" and restarted VSCode) never stops scanning the project files. 
I was easily able to compile and run the packages provided from the command line. 

### What is the expected behavior?

Rust-analyzer should be available after some minutes. 

### Version

master

### Operating System

Windows

### Do you have any log output?

```shell
I have no idea how to log the behavior of rust-analyzer. It seems to shows messages like "fetching", "fetching metadata", and "building"
```

**Comment by hecrj** [comment]
This should be a `rust-analyzer` bug.

**Comment by mschnell1** [comment]
I found that the problem supposedly  is not "never stops", but takes a VERY long time, due to the fact that the workspace contains a lot of example packages that the analyzer seems to "cargo check". 
When moving an example main in a new  project, the analyzer still takes a long time checking all the dependencies, but it actually stops after some minutes.
