### ISSUE TITLE
Error when trying to use a custom Theme with the `text_editor` widget

### ISSUE THREAD

**Issue by 0x192** [iced-rs/iced#2187]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Contrary to other widgets, there is a trait bound error when trying to style the `text_editor` widget :

```rust
the trait `From<theme::TextEditor>` is not implemented for `iced::theme::TextEditor`
```
[SSCCE](http://sscce.org/) : the official `editor` example with a custom Theme : https://github.com/0x192/iced/tree/fix/text_editor_style/examples/editor. All other widgets can be styled without issue.

I dug into [`widget/src/text_editor.rs`](https://github.com/iced-rs/iced/blob/master/widget/src/text_editor.rs) and [`style/src/theme.rs`](https://github.com/iced-rs/iced/blob/master/style/src/theme.rs#L1181) but I didn't find any differences with other widgets that could explain the problem.

### What is the expected behavior?

No error when using a custom Theme with the widget

### Version

master

### Operating System

Linux

**Comment by DaraJKong** [comment]
I recently encountered the same issue on the same version of Iced (master). I'm on Linux too.
The conditions are the same: I'm trying to use a TextEditor with a custom Theme.

**Comment by 0x192** [comment]
@DaraJKong 

I tested again since https://github.com/iced-rs/iced/pull/2209 has been merged and I managed to make it work by using my custom theme Type on every `Element` (since it's generic now)

```rust
mod theme;

use theme::Theme;

...
fn view(&self) -> Element<Message, Theme> {
...
}
```

Exhaustive example :
https://github.com/0x192/iced/tree/fix/text_editor_style/examples/editor/src
