### ISSUE TITLE
Custom components sometimes do not render when used in columns/rows.

### ISSUE THREAD

**Issue by ion0658** [iced-rs/iced#2201]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

- Source
[https://github.com/ion0658/iced-component-not-rendered](https://github.com/ion0658/iced-component-not-rendered)

1. Copy the "compoent" from the examples.([https://github.com/iced-rs/iced/tree/master/examples/component](https://github.com/iced-rs/iced/tree/master/examples/component)
2. Change the container used in the view function in the example to a column.(Same as row)
```rust
    fn view(&self) -> Element<Message> {
        let numeric_comp1 = numeric_input(self.value, Message::NumericInputChanged);
        let col = Column::new();
        let col = col.push(numeric_comp1);

        col.padding(20).height(Length::Fill).into()
    }
```
to
```rust
    fn view(&self) -> Element<Message> {
        let numeric_comp1 = numeric_input(self.value, Message::NumericInputChanged);
        let col = Column::new();
        let col = col.push(numeric_comp1);

        col.padding(20).height(Length::Fill).into()
    }
```

The numeric input component is not rendered, but the code in the examples works correctly.
![image](https://github.com/iced-rs/iced/assets/7760008/2714d10f-a8ad-4c75-9651-3921e0da5bc2)

I have tried it on windows 11 and macos 13.6 and got the same results on both.

### What is the expected behavior?

The numeric input component should appear on the screen.

### Version

master

### Operating System

Windows

### Do you have any log output?

```shell
iced-component-not-rendered on  main is 📦 v0.1.0 via 🦀 v1.74.0 took 16s
❯ cargo run
   Compiling iced-component-not-rendered v0.1.0 (F:\playground\iced_component_not_rendered\iced-component-not-rendered)
    Finished dev [unoptimized + debuginfo] target(s) in 1.39s
     Running `target\debug\iced-component-not-rendered.exe`
numeric input view called!
```

**Comment by hecrj** [comment]
This is expected behavior.

You need to set the `width` of the `column` to `Length::Fill` manually, since components defer `view` calls and cannot hint their sizing strategy during construction.

**Comment by ion0658** [comment]
@hecrj  Thank you! It worked properly!
