### ISSUE TITLE
The Canvas bounds.contains check has the canvas position as offset

### ISSUE THREAD

**Issue by TheComamba** [iced-rs/iced#2216]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

If the canvas top-left does not coincide with the window top-left then the check interprets the point as if it lived in the window frame of reference, not the canvas frame of reference.

SSCCE: See the [Canvas Coordinate example in my iced playground](https://github.com/TheComamba/IcedPlayground).

### What is the expected behavior?

The bounds.contains check should evaluate to true for all coordinates within the canvas.

### Version

crates.io release

### Operating System

Linux

**Comment by TheComamba** [comment]
Here's a screenshot:
![Canvas_Coordinates](https://github.com/iced-rs/iced/assets/98019967/a5fd275f-39c4-4683-82e0-7dcd9cbcd454)

**Comment by TheComamba** [comment]
The issue persists with the current master branch of iced.

**Comment by hecrj** [comment]
`Frame` coordinates are relative. The `bounds` provided in `draw` are absolute.

The user needs to convert accordingly.
