### ISSUE TITLE
Rule inside scrollable is extremely large

### ISSUE THREAD

**Issue by TheComamba** [iced-rs/iced#2217]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Placing a Rule inside a Scrollable makes the latter think that its width is extremely large. I suppose this is because Rule uses Length::Fill as its width.

SSCCE: See the [Rule on Scrollable example in my iced playground](https://github.com/TheComamba/IcedPlayground).

### What is the expected behavior?

Well, that's a design question. My first hunch is that the rule should be as large as the scrollable would be without the rule. Depending on the implementation this may also help solving #1745. Another option is for the rule to fill the width/height of the container that the scrollable lives in. This would probably align more with the current behaviour of rules outside of scrollables.

### Version

crates.io release

### Operating System

Linux

**Comment by TheComamba** [comment]
![Rule_on_scrollable](https://github.com/iced-rs/iced/assets/98019967/324d3061-67e1-4842-9211-3462d3f74589)

**Comment by TheComamba** [comment]
The issue persists with the current master branch of iced.

**Comment by hecrj** [comment]
It is considered an invalid layout to `Fill` in the scrolling direction of a `Scrollable`. A `Scrollable` has no upper limit in its scrolling direction and filling it is equivalent to trying to fill some infinite space.
