### ISSUE TITLE
Preset window dimensions are really messy (under wayland)

### ISSUE THREAD

**Issue by ThePyroTF2** [iced-rs/iced#2230]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Defining the size of the window using `settings.window.size` is wildly inconsistent under wayland. With `settings.window.resizable` set to `true`, the width is the number of pixels passed in, but the height has ~35 pixels added to it. With `resizable` set to `false`, both the height and width are  ~20 pixels extra. _I measured this as best I could with the apt package `screenruler`'s graphical screen ruler. These numbers aren't 100% precise but they are consistent._

### What is the expected behavior?

When I pass dimensions into the `settings.window.size` setting, the window should be created with those dimensions.

### Version

crates.io release

### Operating System

Linux

**Comment by ThePyroTF2** [comment]
Some digging has led me to believe this is only an issue on Wayland. :(

**Comment by ThePyroTF2** [comment]
Yep, no problem on Windows either. This is totally a wayland thing.

**Comment by dtzxporter** [comment]
I believe this is an upstream winit issue. Winit handles creating the window with the given dimensions and should take the frame into account.

**Comment by ThePyroTF2** [comment]
Not sure what makes this the case, but the current master branch of iced doesn't have this problem. :shrug:

**Comment by ThePyroTF2** [comment]
I looked at the changelog to see if there was anything addressing it. Must have been fixed by proxy of some other change.

**Comment by hecrj** [comment]
Most likely fixed by #2191.
