### ISSUE TITLE
[bug] `vertical_space()` and `horizontal_space()` functions

### ISSUE THREAD

**Issue by rizzen-yazston** [iced-rs/iced#2257]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Using release 0.12.0.

The specified `Length` parameter seems to have been removed , yet description states there should be a `Length`.

https://docs.iced.rs/iced/widget/fn.vertical_space.html

https://docs.iced.rs/iced/widget/fn.horizontal_space.html

### What is the expected behavior?

To be able to pass a `Length`, which allows for `Fill` to be used.

Pre 0.12.0, the parameter was not `Length` but a fixed unsigned value.

### Version

crates.io release

### Operating System

Linux

**Comment by hecrj** [comment]
Would you like to patch this in a PR?

**Comment by rizzen-yazston** [comment]
can do on monday

**Comment by rizzen-yazston** [comment]
Added PR to fix.

https://github.com/iced-rs/iced/pull/2265

**Comment by hecrj** [comment]
@rizzen-yazston Ah, no. I meant we should change the docs! :sweat_smile: Sorry for the confusion.
