### ISSUE TITLE
Some Path::line is invisible in Canvas

### ISSUE THREAD

**Issue by fogarecious** [iced-rs/iced#2281]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

In the [clock](https://github.com/iced-rs/iced/tree/master/examples/clock) example, seconds hand disappears when pointing at 0, 15, 30, and 45.
<img width="1024" alt="2" src="https://github.com/iced-rs/iced/assets/83577772/7f2828fc-c471-4e57-b6c8-66af22913d1e">

It seems that Path::line will not be drawn when the line is horizontal or vertical. The following code shows this:
```rust
use iced::{
    mouse,
    widget::{
        canvas::{Frame, Geometry, Path, Program, Stroke},
        Canvas,
    },
    Color, Length, Rectangle, Renderer, Sandbox, Settings, Theme,
};

fn main() -> iced::Result {
    MyApp::run(Settings::default())
}

struct MyApp;

impl Sandbox for MyApp {
    type Message = ();

    fn new() -> Self {
        Self
    }

    fn title(&self) -> String {
        "".into()
    }

    fn update(&mut self, _message: Self::Message) {}

    fn view(&self) -> iced::Element<'_, Self::Message> {
        Canvas::new(MyProgram)
            .width(Length::Fill)
            .height(Length::Fill)
            .into()
    }
}

struct MyProgram;

impl<Message> Program<Message> for MyProgram {
    type State = ();

    fn draw(
        &self,
        _state: &Self::State,
        renderer: &Renderer,
        _theme: &Theme,
        bounds: Rectangle,
        _cursor: mouse::Cursor,
    ) -> Vec<Geometry> {
        let mut frame = Frame::new(renderer, bounds.size());

        frame.stroke(
            &Path::line([0.0, 100.0].into(), [1024.0, 100.0].into()),
            Stroke {
                style: Color::BLACK.into(),
                width: 50.0,
                ..Default::default()
            },
        );

        vec![frame.into_geometry()]
    }
}
```

However, if we change the code from
```rust
&Path::line([0.0, 100.0].into(), [1024.0, 100.0].into()),
```
to
```rust
&Path::line([0.0, 100.0].into(), [1024.0, 101.0].into()),
```
i.e., move the endpoint down a little bit, then the line is drawn as expected.

### What is the expected behavior?

Path::line is drawn for all directions including vertical and horizontal.

### Version

master

### Operating System

macOS

**Comment by hecrj** [comment]
Thanks for the report! This is a problem in `iced_tiny_skia`. #2282 should fix it.

**Comment by Gibbz** [comment]
I'm having a similar issue to this. Should we reopen a new issue? Or can we get this issue reopened?

I also have no way to change line ends to be square.
