### ISSUE TITLE
`palette` is ambiguous ambiguous because of multiple potential import sources

### ISSUE THREAD

**Issue by drunkenlion** [iced-rs/iced#2294]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

<img width="612" alt="图片" src="https://github.com/iced-rs/iced/assets/5670400/8173b851-ea28-4dcc-a4d9-7175429e659d">

### What is the expected behavior?

`palette` is ambiguous
ambiguous because of multiple potential import sources

### Version

master

### Operating System

macOS

### Do you have any log output?

```shell
`palette` is ambiguous
ambiguous because of multiple potential import sources
use `::palette` to refer to this crate unambiguously
use `self::palette` to refer to this module unambiguouslyrustcClick for full compiler diagnostic
lib.rs(1, 1): `palette` could refer to a crate passed with `--extern`
theme.rs(2, 1): `palette` could also refer to the module defined here
iced_style::theme
mod palette
```

**Comment by hecrj** [comment]
Update your Rust toolchain: `rustup update`.
