### ISSUE TITLE
column macro possibly in conflict with core column macro

### ISSUE THREAD

**Issue by CristianKerr** [iced-rs/iced#2306]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

In RustRover (new ide for rust from JetBrains), the macro in iced_widget::column collides (probably) with core::column macro and causes issues with code navigation and highlighting (screenshot below). While this is not an issue of Iced itself, I would suggest to avoid these macros to have the same name (or any macros to be named the same as the core macros) as it may have unintended consequences now and in the future. 

For simplicity I would suggest to rename the macro to "col" as it would pair nicely with "row" as a short macro. This abbreviation is well known between other languages (like HTML) as well. 

Do not get me wrong, I think short but full names have their merit, but there are cases like this where I think it would be prudent to avoid it.

I have just filed [this bug](https://youtrack.jetbrains.com/issue/RUST-13672/Rust-macros-causing-unclear-variables-and-imports-usage) to Jetbrains. Feel free to look at it in detail as it includes also a minimal example and following screenshot:
![Screenshot from 2024-02-28 15-25-42](https://github.com/iced-rs/iced/assets/79404036/32349684-1ae3-4f9a-b7df-e68e5cc157bf)

### What is the expected behavior?

There are no side effects of this same naming.

### Version

crates.io release

### Operating System

Linux

**Comment by hecrj** [comment]
> For simplicity I would suggest to rename the macro to "col" as it would pair nicely with "row" as a short macro. This abbreviation is well known between other languages (like HTML) as well.

I don't like abbreviations. I think they add subconscious overhead and increase the learning barrier.

**Comment by CristianKerr** [comment]
Thanks for the tip. I actually don't think I can do anything for that, because I think its built in the RustRover, there is no option or plugin like this. 

Anyway this issue is rather about evaluating whether it would be a good idea to rename the column macro :blush:

**Comment by hecrj** [comment]
> Anyway this issue is rather about evaluating whether it would be a good idea to rename the column macro 😊

I see! We use issues for bug reports only. I recommend you to start a discussion either over [our Discord server](https://discord.gg/3xZJ65GAhd) or [our Discourse forum](https://discourse.iced.rs/).

Closing, since this isn't really a bug!

**Comment by CristianKerr** [comment]
Understood, I should have realized, my appologies :) And thank you
