### ISSUE TITLE
Dynamic Window Size

### ISSUE THREAD

**Issue by tingfeng-key** [iced-rs/iced#2340]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Cannot dynamically modify the window size

### What is the expected behavior?

The window size can be dynamically modified

### Version

master

### Operating System

Windows

**Comment by hecrj** [comment]
You should be able to use the `window::resize` command: https://docs.rs/iced/latest/iced/window/fn.resize.html

**Comment by tingfeng-key** [comment]
What should I do or the ID value of the current window?
