### ISSUE TITLE
Cannot use mousewheel without shift to scoll a horizontal-only scrollable.

### ISSUE THREAD

**Issue by Gremious** [iced-rs/iced#2359]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

I am working on an applicaiton where I have two splits, one scrolling horizontally and one vertically:

![image](https://github.com/iced-rs/iced/assets/21365711/4ac3375f-0c71-47b9-9770-0be4138bc593)

I can scroll the vertical one with the mousewheel just fine, but not the horizontal one. It demands I hold down shift, even though there's no vertical scrollbal present (the scrollable is Horizontal, not Both, so it can only scroll in the one direction anyway). I don't believe I am able to change this behaviour.

### What is the expected behavior?

Shift should be needed only when both scrollbars are present. Otherwise, scrollwheel should just scroll.
Alternatively, I should be able to specify whether I want shift scrolling on a Horizontal scrollable.

### Version

crates.io release

### Operating System

Windows

**Comment by hecrj** [comment]
What is the state of the art here? The Web does not implement this.

**Comment by Gremious** [comment]
Yeah, horizontal scrolls are pretty rare, they don't show up in windows explorer anymore, terminals, most apps honestly. They're really not developed/looked at much at all.

The web does not implement this and that's a pain whenever you actually need to make a left/right moving menu, as it creates a lot of friction, since web/app navigation is pretty much mouse only. Throwing in a shift key suddenly makes you stop moving when you expect to.

Hence why by now, everyone does little "scroll buttons" that jump x items left/right, and/or they manually implement swipe controls. You've probably seen them all round, the "display 3 elements and swipe/press the arrow on the side to keep scrolling through the next ones" is very common.

For my usecase, that really isn't good enough. I have a section of my app that is exclusively horizontally scrolled by design. I need to be fast and frictionless, and still usable without a hand on the keyboard.

I don't think most people use horizontal scrolls much, so I don't think this would impact people negatively (if at all). Though if the need arises, at worst we should be able to choose whether we want the shift modifier.
