### ISSUE TITLE
placing images inside image

### ISSUE THREAD

**Issue by aentity** [iced-rs/iced#237]
I don't know if possible, but to place image inside image (which has a container) would be very helpful.

For example, custom ui, has a surrounding image/svg box with some decorations. Another image, for example character image, is inside this, and text is to right of image.

Is it possible?

Thank you for great library!

**Comment by yaskhan** [comment]
image blending?

**Comment by manokara** [comment]
I think OP is looking for a way to use an image as a background for a Container, possibly with 9-patch capabilities for decoration, quite like this:

![example](https://rpgmaker.net/media/content/users/10538/locker/script_opa255.png)

This could be a new widget, something like `DecoratedContainer`, or once layers are a thing, a normal Container with controls on top of the background Image, but in that case decorations wouldn't work well. If it's a new widget, I'm not sure if it would be something to be included with iced, it should probably be on a "community widgets" repository.

**Comment by aentity** [comment]
Not really; i just mean one image is a background, and then i place one or more image on top. Example:

![example](https://user-images.githubusercontent.com/55963758/77723753-884d9580-6fae-11ea-90ec-73c8f1483d2d.png)

Image 1 (black) is background. 2 is white square; 3 is red circle. Background maybe very complicated, for example, and recreating style programmatically is too hard/tedious (and then if style changes, have to do all over again, instead of loading image).

**Comment by aentity** [comment]
ah @manokara thank you, is good example too! :)

**Comment by akshayr-mecha** [comment]
Hello @manokara 
is this added?
