### ISSUE TITLE
readme out of date

### ISSUE THREAD

**Issue by n1ght-hunter** [iced-rs/iced#2384]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

the readmes are out of date
version is wrong
https://github.com/iced-rs/iced/blob/ee105e3bee1bc676dcf3324693984ccda8e4e733/core/README.md

### What is the expected behavior?

NA

### Version

master

### Operating System

Windows

**Comment by ccpwcn** [comment]
When I saw https://github.com/iced-rs/iced/issues/2346, I thought the problem was fixed. So...

I'm imported iced 0.12.1, copied code from https://github.com/iced-rs/iced/blob/master/examples/counter/src/main.rs
It really sucks, The bug still exists.
![image](https://github.com/iced-rs/iced/assets/5465756/5a227eed-329e-426b-8867-a40c6f86c249)

```rust
//隐藏Windows上的控制台窗口
#![windows_subsystem = "windows"]

use iced::widget::{button, column, text, Column};
use iced::Alignment;

pub fn main() -> iced::Result {
    iced::run("A cool counter", Counter::update, Counter::view)
}

#[derive(Default)]
struct Counter {
    value: i64,
}

#[derive(Debug, Clone, Copy)]
enum Message {
    Increment,
    Decrement,
}

impl Counter {
    fn update(&mut self, message: Message) {
        match message {
            Message::Increment => {
                self.value += 1;
            }
            Message::Decrement => {
                self.value -= 1;
            }
        }
    }

    fn view(&self) -> Column<Message> {
        column![
            button("Increment").on_press(Message::Increment),
            text(self.value).size(50),
            button("Decrement").on_press(Message::Decrement)
        ]
        .padding(20)
        .align_items(Alignment::Center)
    }
}
```

cargo run
![image](https://github.com/iced-rs/iced/assets/5465756/889607d7-eaed-4747-89ad-bdb567aaac37)

**Comment by ccpwcn** [comment]
iced = "0.12" doesn't work either.

**Comment by ccpwcn** [comment]
iced = "0.12.0" doesn't work either.
iced = "0.10.0" doesn't work either.
iced = "0.0.0" doesn't work either.

All of them, cannot find the `iced::run` function. But I saw this function in 0.13.0-dev.

**Comment by hecrj** [comment]
![image](https://github.com/iced-rs/iced/assets/518289/71f9f199-bb44-4f62-a5d2-c02e0e1fdaa4)

**Comment by alex-ds13** [comment]
> ![image](https://private-user-images.githubusercontent.com/518289/334062728-71f9f199-bb44-4f62-a5d2-c02e0e1fdaa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MDU1MjUsIm5iZiI6MTcxNjgwNTIyNSwicGF0aCI6Ii81MTgyODkvMzM0MDYyNzI4LTcxZjlmMTk5LWJiNDQtNGY2Mi1hNWQyLWMwMmUwZTFmZGFhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QxMDIwMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTRmYjliNDVlNzU3MTlhOTFiYWRlN2QxMzZmMGE1YjdhNGM0NjgwODE1YzU1YTNhMTVhZDk1MjlkMWM1NDdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rov0ljNyzIagCadMdyM3jwJI-9DGhQEAgRIXiRt-4f4)

Actually this issue is related to the `iced_core` README file that still tells to use version `0.9` even on master branch.

The comments from @ccpwcn are unrelated to this issue itself. Was wrongfully directed here from issue #2346 which is actually the problem they're facing. I've already responded there.

**Comment by alex-ds13** [comment]
The same thing happens on the `iced_wgpu` [README](https://github.com/iced-rs/iced/blob/master/wgpu/README.md).

But since I don't think there is many people using the `iced_core` or `iced_wgpu` crates directly I don't think this is that much of an issue...
