### ISSUE TITLE
Layout issues when resizing window

### ISSUE THREAD

**Issue by njust** [iced-rs/iced#2391]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Using the current master branch, a simple layout causes problems when resizing the window:

https://github.com/iced-rs/iced/assets/2380253/87041735-396e-46ed-a96e-2595e6e4ae55

Repository with the example:
https://github.com/njust/iced_layout_issue

### What is the expected behavior?

The layout should be consistent.

### Version

master

### Operating System

Windows

**Comment by hecrj** [comment]
I cannot reproduce.

**Comment by njust** [comment]
Sorry for the double post. But it seems, that setting the environment variable `ICED_BACKEND=tiny-skia` doesn't have an effect on the current master branch. Therefore, I tried to force the usage of tina-skia by removing the wgpu feature via `default-features = false` which leads to a white screen: 
![image](https://github.com/iced-rs/iced/assets/2380253/b3ab72e6-870e-4cd9-84a1-f6fbd87477b8)

**Comment by njust** [comment]
Short update, I tried today again with the latest master branch and this is still an issue. I updated the example to use the content explain feature. The problem only occurs if the content in the scroll area does not have enough space:

https://github.com/iced-rs/iced/assets/2380253/03cfbf9a-2f0b-4f77-8858-cd6ced53d1c1

I also attached the current log file:
[Demo_2024-05-03_17-55-50.log](https://github.com/iced-rs/iced/files/15202519/Demo_2024-05-03_17-55-50.log)

The repository with the updated example is here:
https://github.com/njust/iced_layout_issue

Is there any way I can help to analyze the problem?

**Comment by hecrj** [comment]
This is most certainly a graphics driver issue.

If you are using a VM, enable the `tiny-skia` feature and use it with `ICED_BACKEND=tiny-skia`.
