### ISSUE TITLE
button::Appearance has both `shadow` and `shadow_offset` properties

### ISSUE THREAD

**Issue by lufte** [iced-rs/iced#2396]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

I assume this is not intended: https://docs.rs/iced/0.12.1/iced/widget/button/struct.Appearance.html

### What is the expected behavior?

Just have a shadow property.

### Version

crates.io release

### Operating System

Linux

**Comment by hecrj** [comment]
Thanks! This is already fixed in `master`.
