### ISSUE TITLE
The buttons contain different single English characters, yet their sizes vary.

### ISSUE THREAD

**Issue by Seikaijyu** [iced-rs/iced#2399]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Using the '+' button will noticeably increase the size compared to using the '-' button. In the example 'examples/counter', change the text to '+' and '-' to see the results.
![image](https://github.com/iced-rs/iced/assets/68497295/5d4ed031-db5c-408e-a722-438646201ecd)

### What is the expected behavior?

The two buttons are the same size.

### Version

crates.io release

### Operating System

Windows

**Comment by lufte** [comment]
I say this makes sense. The button expands to fit the text inside of it and, unless you're using a monospaced font, different characters have different lengths.

**Comment by Seikaijyu** [comment]
Okay, thank you very much for your explanation
