### ISSUE TITLE
Stack widget layout issue

### ISSUE THREAD

**Issue by njust** [iced-rs/iced#2431]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

Using the stack widget with two views with buttons won't render the above button properly:

The last element is a stack with two "card_views":
![image](https://github.com/iced-rs/iced/assets/2380253/6d70cf40-afb0-4386-b0c9-f486ff9d6744)

Example repository is here:
https://github.com/njust/iced_layout_issue/tree/stack_widget_issue

### What is the expected behavior?

Properly render the most recent widget in the stack.

### Version

master

### Operating System

Windows

**Comment by WailAbou** [comment]
I've done some debugging and found that the text `size` attribute is causing issues with the button rendering. If you remove the `size` attribute, the button renders correctly. I'm currently looking for a fix, but I can't make any promises as I'm new to this framework and not a maintainer. From the looks of it, this is likely an issue within the rendering code, which I am not well-versed in 😅.

**Comment by WailAbou** [comment]
After looking into it further, I found that the issue has been resolved in a later commit than the one you were using in your Cargo.lock file. To fix this, you should delete your Cargo.lock and let it regenerate, then make some small syntax changes to match the updates. I've created a pull request for you that implements these changes: https://github.com/njust/iced_layout_issue/pull/2.

If a maintainer reviews this, you can most likely close this issue.

**Comment by njust** [comment]
Hi, thanks for looking into this. I can confirm this works now as expected on the latest master branch.
