### ISSUE TITLE
Unable to register on_open event for combo box

### ISSUE THREAD

**Issue by WZ-Tong** [iced-rs/iced#2452]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

I can only register `on_close event, but not `on_open` event.
It's useful to refresh items when combo box is selected.

Currently I can use `on_option_hovered`, but it triggers everytime mouse move over an option

### What is the expected behavior?

ComboBox::new().on_open

### Version

crates.io release

### Operating System

Windows

**Comment by WailAbou** [comment]
Hi @WZ-Tong,

I have submitted a PR to add the new feature. The method is named `on_focus` instead of `on_open`, as it makes more sense in this context.
