### ISSUE TITLE
TOFU characters while rendering unicode string

### ISSUE THREAD

**Issue by abique** [iced-rs/iced#2458]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

iced failed to render correctly the given string: `Insane Creatures - ɨռֆǟռɛ ƈʀɛǟȶʊʀɛֆ & ʍɛȶʀɨ? - ค๒รՇгคςՇ гєคɭเՇץ.flac`

As another example it also failed at rendering: `Archaic - The Solution Comes In Non-Ordinary realities🍃`

<img width="586" alt="Screenshot 2024-06-12 at 01 07 36" src="https://github.com/iced-rs/iced/assets/31200/5c10f1c0-60b7-4842-8cb9-be6605475527">
<img width="316" alt="Screenshot 2024-06-12 at 01 07 11" src="https://github.com/iced-rs/iced/assets/31200/09bd6bd2-9be7-428a-83df-35e13849e2d1">

### What is the expected behavior?

It should render all glyphs without using tofu.

### Version

master

### Operating System

macOS

**Comment by hecrj** [comment]
[Use `shaping(text::Shaping::Advanced)`](https://docs.rs/iced/latest/iced/advanced/widget/struct.Text.html#method.shaping).
