### ISSUE TITLE
window::open_events() function subscribes to close events

### ISSUE THREAD

**Issue by shartrec** [iced-rs/iced#2481]
### Is your issue REALLY a bug?

- [X] My issue is indeed a bug!
- [X] I am not crazy! I will not fill out this form just to ask a question or request a feature. Pinky promise.

### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

In the master branch in the /runtime/src/window.rs the open_events() code erroreously subscribes to the wrong events. Simple Copy/Paste error by the looks of it.
```
/// Subscribes to all [`Event::Closed`] occurrences in the running application.
pub fn open_events() -> Subscription<Id> {
    event::listen_with(|event, _status, id| {
        if let crate::core::Event::Window(Event::Closed) = event {
            Some(id)
        } else {
            None
        }
    })
```

### What is the expected behavior?

Should subscribe to Open events

### Version

master

### Operating System

Linux

**Comment by hecrj** [comment]
Ah, classic copy-paste! Fixing...
