### ISSUE TITLE
How do I focus a combobox?

### ISSUE THREAD

**Issue by im-n1** [iced-rs/iced#2530]
### Is your issue REALLY a bug?

- [X] My issue is indeed a bug!
- [X] I am not crazy! I will not fill out this form just to ask a question or request a feature. Pinky promise.

### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

What works on 0.10:

```rust
 let state = combo_box::State::new(self.search_results.clone().unwrap());
 state.focus();
```

### What is the expected behavior?

How to do the same on 0.12?

### Version

crates.io release

### Operating System

Linux

**Comment by hecrj** [comment]
> I am not crazy! I will not fill out this form just to ask a question or request a feature. Pinky promise.

:(

**Comment by im-n1** [comment]
Thank you, this really helps the project to be liked among developers

**Comment by max397574** [comment]
> Thank you, this really helps the project to be liked among developers

Agree with that. It helps to improve the quality of the plugin because the maintainer can focus on real issues and doesn't has to spend his time helping users with questions many people could answer.
