### ISSUE TITLE
wgpu-core 0.19.0 has been yanked from crates.io

### ISSUE THREAD

**Issue by edwloef** [iced-rs/iced#2559]
### Is your issue REALLY a bug?

- [X] My issue is indeed a bug!
- [X] I am not crazy! I will not fill out this form just to ask a question or request a feature. Pinky promise.

### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

```
error: failed to select a version for the requirement `wgpu-core = "^0.19.0"`
candidate versions found which didn't match: 22.1.0, 22.0.0, 0.21.1, ...
location searched: crates.io index
required by package `wgpu v0.19.0`
    ... which satisfies dependency `wgpu = "^0.19"` of package `iced_wgpu v0.12.0`
    ... which satisfies dependency `iced_wgpu = "^0.12"` of package `iced_renderer v0.12.1`
    ... which satisfies dependency `iced_renderer = "^0.12.1"` of package `iced v0.12.1`
    ... which satisfies dependency `iced = "^0.12.1"` of package `[...]`
```

see https://github.com/gfx-rs/wgpu/issues/5837

### What is the expected behavior?

No error selection version of wgpu

### Version

crates.io release

### Operating System

Linux

**Comment by edwloef** [comment]
As a workaround you can add the following to your `Cargo.toml` for now:
```
[patch.crates-io]
wgpu-core = { git = "https://github.com/gfx-rs/wgpu", tag = "wgpu-hal-v0.19.5" }
wgpu-types = { git = "https://github.com/gfx-rs/wgpu", tag = "wgpu-hal-v0.19.5" }
wgpu-hal = { git = "https://github.com/gfx-rs/wgpu", tag = "wgpu-hal-v0.19.5" }
```

**Comment by abzr1** [comment]
It's actually v0.20.0 and v0.18.0 that have been yanked

**Comment by edwloef** [comment]
Sorry, meant to say wgpu-core

**Comment by edwloef** [comment]
~Sorry, meant to say wgpu-core~ seems to be back now, it was gone this morning.
