### ISSUE TITLE
Second, Invisible Window

### ISSUE THREAD

**Issue by andymandias** [iced-rs/iced#2564]
### Is your issue REALLY a bug?

- [X] My issue is indeed a bug!
- [X] I am not crazy! I will not fill out this form just to ask a question or request a feature. Pinky promise.

### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

When running an iced application on Fedora Asahi Remix 40 using GNOME 46.4, two windows are opened.  The application window as intended, and a second, invisible window.  The second window is only apparent via the application switcher:
 
![Screenshot from 2024-08-28 09-33-04](https://github.com/user-attachments/assets/ef345331-684f-4bf3-a7ce-3a819e2bfac1)

The invisible window is named "winit window" in the application switcher, and closes when the application closes.  It does not interfere with the application as far as I can tell, only with the expected operation of the application switcher.

This happens with every iced example program I've tested.  When running the wgpu and winit example programs (`hello_triangle` and `window`, respectively), only one window is launched.

### What is the expected behavior?

Only the application window is opened when it is run.

### Version

master

### Operating System

Linux

**Comment by blazra** [comment]
Same problem on Ubuntu 22.04 with Plasma 6
![image](https://github.com/user-attachments/assets/decc35b4-32e1-4142-af37-05bc2fd582ba)

**Comment by njust** [comment]
The second window still exists if the tiny-skia backend is used. This can be reproduced with the examples on the current master branch by forcing the usage of tiny skia backend:
`export ICED_BACKEND=tiny-skia`

![image](https://github.com/user-attachments/assets/f577b551-d0f5-4398-8931-c3b68baf6a91)

Tested on Ubuntu 22.04
