### ISSUE TITLE
`auto-detect-theme` depends on faulty version of `dark-light`

### ISSUE THREAD

**Issue by Rudxain** [iced-rs/iced#2581]
### Is your issue REALLY a bug?

- [X] My issue is indeed a bug!
- [X] I am not crazy! I will not fill out this form just to ask a question or request a feature. Pinky promise.

### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

(#2343) [This line](https://github.com/iced-rs/iced/pull/2343/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R127) introduced a buggy feature: frewsxcv/rust-dark-light#39

~~TLDR: please use an exact version, preferably `=1.0.0`, as I've tested it works~~

### What is the expected behavior?

It should detect color-scheme on any supported OS

### Version

master

### Operating System

Linux

**Comment by Mingun** [comment]
This is a library. If it would use exact dependencies, consumes cannot select other version. You should lock the version of the dependency in you _application_ crate. If your crate is a library, please, do not use exact versions.

**Comment by Rudxain** [comment]
> If it would use exact dependencies, consumes cannot select other version. You should lock the version of the dependency in you _application_ crate. If your crate is a library, please, do not use exact versions.

Thanks for the advice! It reminded me of [this](https://doc.rust-lang.org/1.71.1/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) (which I previously forgotten)

Should I close this issue?

**Comment by hecrj** [comment]
As mentioned, this should be fixed upstream.
