### ISSUE TITLE
In 0.13 and 0.13.1, mouse_area doesn't activate on_move message

### ISSUE THREAD

**Issue by pixelprizm** [iced-rs/iced#2589]
### Is your issue REALLY a bug?

- [X] My issue is indeed a bug!
- [X] I am not crazy! I will not fill out this form just to ask a question or request a feature. Pinky promise.

### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

The `mouse_area` element with `on_move` seems to be broken in 0.13 and 0.13.1.  It worked in 0.12.

The following code dispatches the OnMove message in 0.12 but not in 0.13.

```
mouse_area("Hello world").on_move(Message::OnMove),
```

`on_press` still works.

It looks related to the change made here: https://github.com/iced-rs/iced/commit/c711750be7ccca6a6852d0222169ebfea04ee864#diff-2b3d8bbc11ac699d4e936dac3b987950f3d1a63b5345395c14541a1021322e14R322.

From some brief debugging, the mouse move does not activate the following if-condition: `if state.cursor_position != cursor_position && state.bounds != bounds {`.

### What is the expected behavior?

I'm expecting the mouse_area element to dispatch an OnMove message when I move the cursor over that mouse area element, but it doesn't since 0.13.

### Version

crates.io release

### Operating System

Windows

**Comment by hecrj** [comment]
I'm quite confident I fixed this in https://github.com/iced-rs/iced/commit/1f8dc1f3dda25c699b94c653d5d569f4142e9b83, which was released in `0.13.1`.

Try running `cargo update` to make sure your `Cargo.lock` is using the latest patch for all the subcrates.

**Comment by pixelprizm** [comment]
Thanks for replying, confirming it's fixed after `cargo update`.
