### ISSUE TITLE
What happened to Sandbox 0.12.1 -> 0.13.1?

### ISSUE THREAD

**Issue by tgrushka** [iced-rs/iced#2622]
### Is your issue REALLY a bug?

- [X] My issue is indeed a bug!
- [X] I am not crazy! I will not fill out this form just to ask a question or request a feature. Pinky promise.

### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

The reason I call this a bug is that I looked in the CHANGELOG and README and don't see a change (it is not documented), and I looked through the features using `cargo feature iced`, and I don't see any mention of it.

I'm just trying to get started with the library and came across a tutorial based on 0.12.1 that uses `Sandbox`. I read the docs for it:

```
/// A sandboxed [`Application`].
///
/// If you are a just getting started with the library, this trait offers a
/// simpler interface than [`Application`].
...
///
/// Therefore, it is recommended to always start by implementing this trait and
/// upgrade only once necessary.
```

OK, fine, but where is it?

If it's deprecated, or no longer supported, would it be possible to leave it in but add `#[deprecated(...)]` and add docs to the README and CHANGELOG?

I don't "miss it" because I'm just starting to use this library. I just think it would be really helpful to newcomers to have a simpler way of getting started, if recommended, or at least redirect them to use the correct trait.

Thank you!

### What is the expected behavior?

For the missing `Sandbox` trait, I expected to find docs in the README and/or CHANGELOG or a `#[deprecated(...)]` message in the code directing me to what I should use instead (`Application`).

### Version

crates.io release

### Operating System

Linux

**Comment by bbb651** [comment]
`Application` and `Sandbox` are redundant with [the new `Program` api](https://github.com/iced-rs/iced/pull/2331).
[`iced::run`](https://docs.rs/iced/latest/iced/fn.run.html) replaces `Sandbox` and [`iced::application`](https://docs.rs/iced/latest/iced/application/index.html) replaces `Application` pretty much.

**Comment by alfonso133** [comment]
for those who need a basic mapping of the changes needed to migrate from 0.12 to 0.13 here is a basic outline:

**NOTE**: this is **not** complete and may contain errors

| **applies to**                                                    | **0.12**                                                                                          | **0.13**                                                                                                   |
|:------------------------------------------------------------------|---------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------|
| application                                                       | must implement Application (with related functions view, update)                                  | view and update functions are provided in startup config: `iced::application("title", update_fn, view_fn)` |
| application                                                       | new function implemented as part of Application                                                   | startup tasks provided in `run_with`: `iced::application(..).settings(..).run_with(..)`                    |
| application                                                       | settings are provided as `App::run(settings)`                                                     | settings are provided as `iced::application(..).settings(..)`                                              |
| application                                                       | window setup is provided inside settings struct                                                   | window setup is provided separately: `iced::application(..).settings(..).window(..).run()`                 |
| application                                                       | `Command<Message>`                                                                                | `Task<Message>`                                                                                            |
| theming                                                           | themes needed to be implemented per app                                                           | themes are already implemented in the library (can be customized)                                          |
| all styleable components (button, checkbox, container, text, etc) | styling is provided implementing `button::StyleSheet`, `container::StyleSheet`, etc for app theme | styling is provided as a function: `impl Fn(&Theme, Status) -> Style`                                      |
| all styleable components (button, checkbox, container, text, etc) | style props are in `button::Appearance`, `container::Appearance`, etc                             | style props are in `button::Style`, `container::Style`, etc (some have been renamed)                       |
| all styleable components (button, checkbox, container, text, etc) | `container.width(Length::Fill).center_x()`                                                        | `container.center_x(Length::Fill)`                                                                         |
| all styleable components (button, checkbox, container, text, etc) | `container.center_x()`                                                                            | `container.center_x(Length::Shrink)`                                                                       |
| all styleable components (button, checkbox, container, text, etc) | `container.height(Length::Fill).center_y()`                                                       | `container.center_y(Length::Fill)`                                                                         |
| all styleable components (button, checkbox, container, text, etc) | `container.center_y()`                                                                            | `container.center_y(Length::Shrink)`                                                                       |
| all styleable components (button, checkbox, container, text, etc) | `container.width(Length::Fill).center_x().height(Length::Fill).center_y()`                        | `container.center(Length::Fill)`                                                                           |
| text                                                              | `text.horizontal_alignment(Horizontal::Center)`                                                   | `text.align_x(Horizontal::Center)`                                                                         |
| text                                                              | `text.vertical_alignment(Vertical::Center)`                                                       | `text.align_y(Vertical::Center)`                                                                           |
| padding                                                           | `row.padding([8, 9, 10, 11])`                                                                     | `row.padding(Padding {top: 8.0, right: 9.0, bottom: 10.0, left: 11.0})`                                    |
| padding                                                           | `row.padding([8, 8, 8, 8])`                                                                       | `row.padding(8)` or `row.padding(padding::all(8))` or `row.padding(Padding::new(8.0))`                     |
| padding                                                           | `row.padding([16, 8, 16, 8])`                                                                     | `row.padding([16, 8])`                                                                                     |
| padding                                                           | `row.padding([8, 0, 0, 0])`                                                                       | `row.padding(padding:top(8))`                                                                              |
| padding                                                           | `row.padding([0, 8, 0, 0])`                                                                       | `row.padding(padding:right(8))`                                                                            |
| padding                                                           | `row.padding([0, 0, 8, 0])`                                                                       | `row.padding(padding:bottom(8))`                                                                           |
| padding                                                           | `row.padding([0, 0, 0, 8])`                                                                       | `row.padding(padding:left(8))`                                                                             |
| row                                                               | `row.align_items(Alignment::Center)`                                                              | `row.align_y(Alignment::Center)`                                                                           |
| column                                                            | `column.align_items(Alignment::Center)`                                                           | `column.align_x(Alignment::Center)`                                                                        |
