### ISSUE TITLE
`on_press_with` always calls the closure

### ISSUE THREAD

**Issue by T-256** [iced-rs/iced#2682]
### Is your issue REALLY a bug?

- [X] My issue is indeed a bug!
- [X] I am not crazy! I will not fill out this form just to ask a question or request a feature. Pinky promise.

### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is this issue related to iced?

- [X] My hardware is compatible and my graphics drivers are up-to-date.

### What happened?

At below code, when click on each button, it will print both `foo` and `bar`.

```rs
use iced::widget::{button, column, text};

#[derive(Default)]
struct State {}

#[derive(Debug, Default, Clone)]
enum Message {
    #[default]
    Test,
}

fn main() -> iced::Result {
    iced::application("icedbug", |_: &mut State, _| {}, view).run()
}

fn view(_state: &State) -> iced::Element<Message> {
    column![
        button(text("foo")).on_press_with(|| {
            dbg!("foo");
            Message::Test
        }),
        button(text("bar")).on_press_with(|| {
            dbg!("bar");
            Message::Test
        }),
    ]
    .into()
}
```

### What is the expected behavior?

Call closure only when related button pressed.

### Version

crates.io release

### Operating System

Windows

### Do you have any log output?

`Cargo.toml`:

```toml
[package]
name = "icedbug"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13" }
```

**Comment by bernardolansing** [comment]
@hecrj Hi, could we have a release to add this fix right now? It's kinda important for me... I'm experiencing the same under Linux. Thanks in advance.

**Comment by airstrike** [comment]
> [@hecrj](https://github.com/hecrj) Hi, could we have a release to add this fix right now? It's kinda important for me... I'm experiencing the same under Linux. Thanks in advance.

Cargo lets you pin your dependency to a specific commit so have you tried pointing your Cargo.toml to https://github.com/iced-rs/iced/commit/3b2a422d5d4bf0d21301338050637ce717cff5f7 in the meantime?

**Comment by bernardolansing** [comment]
> > [@hecrj](https://github.com/hecrj) Hi, could we have a release to add this fix right now? It's kinda important for me... I'm experiencing the same under Linux. Thanks in advance.
> 
> Cargo lets you pin your dependency to a specific commit so have you tried pointing your Cargo.toml to [3b2a422](https://github.com/iced-rs/iced/commit/3b2a422d5d4bf0d21301338050637ce717cff5f7) in the meantime?

That will do for now, thank you very much.
