### ISSUE TITLE
Is software rendering supported?

### ISSUE THREAD

**Issue by otavio** [iced-rs/iced#337]
I am researching a toolkit to use for an embedded tool we'd use across different types of devices and ideally we'd support also software rendering for devices without GPU support. 

Is it currently supported?

**Comment by Matthias-Fauconneau** [comment]
It's not.
If nevertheless you'd still be interested in trying iced, I don't know if wgpu would work well with software Vulkan. 
As an alternative, I started a software rendering backend stub (gutted from iced_wgpu).
https://github.com/hecrj/iced/pull/311
It is currently tied to WlShm, I don't know which platform you are targeting.
(and does not work yet)

**Comment by otavio** [comment]
Right, the use of Wayland is Ok. We aim to use with embedded devices which has no gpu at all and we can rely on the software rendering for that.

Once the #311 is usable, we can try it.

**Comment by Matthias-Fauconneau** [comment]
Just to be clear 311 is more of a stub I've been doing in my spare time than
something usable yet. Iced seems like a good coordination point for Rust UI
long term, but depending on your deadline you might want to consider
another option, unless you see benefits in investing to contribute to
improve iced in this direction.

**Comment by myfreeweb** [comment]
Now that there's an OpenGL backend, you should be able to use it with any software OpenGL implementation (e.g. mesa's llvmpipe).

Maybe WebRender's [swgl](https://github.com/servo/webrender/tree/master/swgl) is worth looking into, as an integrated implementation that doesn't require a system-wide one.

**Comment by handicraftsman** [comment]
Yes, this would be useful, because current OpenGL backend only seems to support OpenGL 3.3+, while it's not supported by *every* machine. For example, while my graphics card supports 3.3 (at most though), embedded GPU (an Intel G41, embedded into motherboard chipset) only supports 2.1.

**Comment by otavio** [comment]
What is the current status of this?

**Comment by maroider** [comment]
There has been [some experimenation with a `raqote` backend](https://github.com/twitchyliquid64/iced/tree/raqote), but `iced` itself will need to change somewhat for that backend to be _not_ awkward to implement/use.

**Comment by hecrj** [comment]
Closing in favor of #1071.
