### ISSUE TITLE
In the docs for iced add links to the widgets in iced_native

### ISSUE THREAD

**Issue by SpyrosRoum** [iced-rs/iced#340]
For example, the [doc for the button widget](https://docs.rs/iced/0.1.1/iced/widget/button/type.Button.html) has this text only:

> A widget that produces a message when clicked.
> 
> This is an alias of an `iced_native` button with an `iced_wgpu::Renderer`.

That means that I have to search and find the docs for iced_native and find the widgets there but I think it would make sense to at least have a link that can take you to the iced_native version of the widget

**Comment by hecrj** [comment]
We should figure out why `docs.rs` isn't linking the type alias automatically.

If I run `cargo doc --no-deps --all` locally, [I do get a proper link](https://iced-docs.now.sh/iced/widget/type.Button.html).

**Comment by Imberflur** [comment]
strangely in the `iced_wgpu` docs where I assume it gets these docs from there is a link https://docs.rs/iced_wgpu/0.2.2/iced_wgpu/widget/button/type.Button.html

**Comment by hecrj** [comment]
We may need to add `iced_native` as an explicit dependency of `iced`.

**Comment by hecrj** [comment]
This has been fixed since #1328.
