### ISSUE TITLE
Add hex constructors for Color

### ISSUE THREAD

**Issue by BillyDM** [iced-rs/iced#375]
It would be nice to add a feature to create colors from a single hexadecimal number like this:
```rust
let color1 = Color::from_hex_rgb(0x3280c8);
let color2 = Color::from_hex_rgba(0x3280c86f);
```
The code could be something like this:
```rust
pub fn from_hex_rgb(hex: u32) -> Color {
    let r = (hex & 0xff0000) >> 16;
    let g = (hex & 0xff00) >> 8;
    let b = (hex & 0xff);

    Color {
        r: f32::from(r) / 255.0,
        g: f32::from(g) / 255.0,
        b: f32::from(b) / 255.0,
        a: 1.0f32,
    }
}

pub fn from_hex_rgba(hex: u32) -> Color {
    let r = (hex & 0xff000000) >> 24;
    let g = (hex & 0xff0000) >> 16;
    let b = (hex & 0xff00) >> 8;
    let a = (hex & 0xff);

    Color {
        r: f32::from(r) / 255.0,
        g: f32::from(g) / 255.0,
        b: f32::from(b) / 255.0,
        a: f32::from(a) / 255.0,
    }
}
```

**Comment by hecrj** [comment]
You can currently write:

```rust
let color1 = Color::from_rgb8(0x32, 0x80, 0xC8);
let color2 = Color::from_rgba8(0x32, 0x80, 0xC8, 0.44);
```

A constructor like `from_hex_rgb` doesn't exist because it feels wrong to ask for a `u32` and discard part of it. I think we could add `from_hex_rgba`, although maybe we should name it `from_rgba8_u32` for consistency (i.e. the hexadecimal representation of the literal isn't relevant).

**Comment by BillyDM** [comment]
Well, I'm usually copying and pasting the hex values strait from an external program like Inkscape. It is cumbersome to have to constantly reformat it every time I want to check how it looks in the app.

**Comment by BillyDM** [comment]
Yeah, `from_rgba8_u32` could work. Inkscape uses that format anyway, even if the alpha is `ff`. I feel like that name's not that clear that it's an option for using hex values, but perhaps that could be explained in a comment / documentation?

**Comment by hecrj** [comment]
> Well, I'm usually copying and pasting the hex values straight from an external program like Inkscape. It is cumbersome to have to constantly reformat it every time I want to check how it looks in the app.

You could create your own helper function:

```rust
fn inkscape_color(value: u32) -> iced::Color { /* ... */ }
```

> I feel like that name's not that clear that it's an option for using hex values, but perhaps that could be explained in a comment / documentation.

Yes. It feels wrong to mention `hex` when the argument can be any `u32`.

**Comment by BillyDM** [comment]
Oh yeah, I could write my own helper function. It would be nice just to have this in iced at some point though. Other people using iced may want the same thing but not know how to write that specific helper function.
