### ISSUE TITLE
window is rotated

### ISSUE THREAD

**Issue by aisq2008** [iced-rs/iced#409]
nvidia graphics card  run todos demo ,the window is rotate .

my computer operating system is windows 10，

graphics card is NVIDIA GeForce GTX 1050，driver version is 2020/05/27, game ready driver.

![image](https://user-images.githubusercontent.com/4617898/84754348-d93fb980-aff2-11ea-83b2-4023d5d826ac.png)

**Comment by hecrj** [comment]
Do the [`wgpu` examples][1] display the same issue for you?

[1]: https://github.com/gfx-rs/wgpu-rs

**Comment by aisq2008** [comment]
I was runing the wgpu example hello，output infomation was "AdapterInfo { name: "Intel(R) HD Graphics 630", vendor: 32902, device: 22811, device_type: IntegratedGpu, backend: Vulkan }"

**Comment by aisq2008** [comment]
I was runing the wgpu example hello，output infomation was 
"AdapterInfo { name: "Intel(R) HD Graphics 630", vendor: 32902, device: 22811, device_type: IntegratedGpu, backend: Vulkan }"

the example use a IntegratedGpu,not my nvidia graphics card.

**Comment by aisq2008** [comment]
other examples i could't find any difference info compare with the office example run output.

**Comment by krooq** [comment]
Lol... what in the heck.. its like the whole image is reflected vertically..
Can only be the transform matrix surely.. really bizzare..

**Comment by aisq2008** [comment]
I test a Styling demo of the examples , using the follow setting , the demo work fine,

```rust
   let setting = Settings {
        window: window::Settings  {
            size:(800,600),
            resizable: true,
            decorations: true,
            ..Default::default()
        },
        flags:(),
        antialiasing:true,
        ..Settings::default()
    };

    Styling::run(setting)
```
![image](https://user-images.githubusercontent.com/4617898/142161664-78a16f83-77bf-4ed5-91d6-b5b8bc4ead70.png)

But when i comment the setting option **antialiasing:true** , the demo working wrong like this,
```rust
   let setting = Settings {
        window: window::Settings  {
            size:(800,600),
            resizable: true,
            decorations: true,
            ..Default::default()
        },
        flags:(),
        //antialiasing:true,
        ..Settings::default()
    };

    Styling::run(setting)
```
![image](https://user-images.githubusercontent.com/4617898/142161941-3c71ba35-383d-4079-b7bc-8815169ac366.png)
