### ISSUE TITLE
Clipboard trait not accessible via iced_winit

### ISSUE THREAD

**Issue by Imberflur** [iced-rs/iced#521]
The `iced_winit::Clipboard` struct clashes with the `Clipboard` trait being re-exported from `iced_native`

**Comment by hecrj** [comment]
This is intended. If you want to use the internal `Clipboard` trait directly, you should add `iced_native` as an explicit dependency.

Is this an issue for you? What is your use case?

**Comment by Imberflur** [comment]
Sorry for the delay! I missed the reply and then forgot about this issue.

I am using `iced_winit` for the event conversion and since it re-exports glob re-exports `iced_native` it is convenient to use the iced types from there rather than through `iced_native` directly. However, I am also defining custom widgets and the [`on_event` ](https://docs.rs/iced_native/0.4.0/iced_native/widget/trait.Widget.html#method.on_event) method uses the clipboard trait in it's definition.

**Comment by Imberflur** [comment]
@hecrj any thoughts on this? I'm happy to see it closed if the idiomatic usage for my case is to just also use `iced_native` directly.

**Comment by hecrj** [comment]
Yes, I think depending on `iced_native` is the way to go if you are implementing custom widgets!
