### ISSUE TITLE
Advanced PaneGrid usage

### ISSUE THREAD

**Issue by lerouxrgd** [iced-rs/iced#525]
I am trying to put `Image` and `Scrollable` content (basically controls to modify the image) in different panes of a `PaneGrid`.

It looks like scrollable have infinite length when put in panes. And it also looks like images are not scaled automatically to use maximum available space (which is the case if they are not in a `Pane`). Besides, it  feels like rendering an image in a `Pane` is more expensive (higher CPU usage and longer rendering time).

Is it a bad idea to put `Image` and `Scrollable` content in `PaneGrid` ? Or are there some parameters to tune for things to go smoothly ?

**Comment by hecrj** [comment]
[The `pane_grid` example](https://github.com/hecrj/iced/tree/4f2962d73f3bdeeca8a11817e404c45e91e2c2cc/examples/pane_grid) uses a `Scrollable` inside a `PaneGrid`.

I am not sure I understand the issue you are having. What are you trying to do exactly? Could you share an [SSCCE](http://sscce.org/)?

**Comment by lerouxrgd** [comment]
> What are you trying to do exactly? 

So the idea is to have a GUI with 2 parts, one to display an image, and the other with controls to pixelize the image. You can actually check the current code [here](https://github.com/lerouxrgd/quixelart). On `master` the 2 parts are just two cells of a column and it works smoothly. On `panes` branch I try to put the 2 parts in two panes. The reason I want to use panes is to be able to resize and switch layout (row/column) of the 2 parts.

> Could you share an SSCCE?

So I made this [SSCCE](https://github.com/lerouxrgd/sscce-iced). It displays the Rust logo when you choose its resolution through a radio control. 

When using 144px, the whole pane space won't be completely filled (as it would happen if I hadn't use panes but simply columns, because `Image` tries to resize its content to fill up all the available space, if I understood it correctly). It also feels like rendering the 1024px image is slow (again, compared to an `Image` used in a regular container) even though it is not wrapped in a `Scrollable` here.

Finally, the pane with the `Radio` can be scrolled down infinitely and there is no slider displayed.

**Comment by lerouxrgd** [comment]
Ok I realized that at least for the `Scrollable` controls I just have to not wrap them in a `Container` to get the expected behavior.
