### ISSUE TITLE
Invisible text when antialiasing enabled

### ISSUE THREAD

**Issue by nyanpasu64** [iced-rs/iced#537]
When I run certain examples (I think examples with antialiasing enabled), all text is missing.

I ran `cargo run --package ...` and tested `game_of_life` on several commits I tested from eec65a05 (2020-06-20) to master 4f2962d7 (most recent commit on 2020-09-12). I tested several other examples on master:

- custom_widget, stopwatch, and tour have working text. svg renders properly.
- bezier_tool and game_of_life have missing text.

![game_of_life_PhnlZeOuEE](https://user-images.githubusercontent.com/913957/93711297-032cde80-fb02-11ea-97a1-a22be69d5017.png)

- clock has strange rendering glitches. Video at https://youtu.be/c3XJtY8CBl8.

![iced clock bug](https://user-images.githubusercontent.com/913957/93711769-bf3bd880-fb05-11ea-9f83-73ebc96faef7.png)

I originally ran the tests on Radeon Software 20.8.1 (a few months old). I retested `game_of_life` on 20.9.1 and it's still broken.

*How do I check which backend (DX11, DX12, Vulkan) is being used?*

## Workarounds

When I disable antialiasing (`Settings { antialiasing: false`), all programs (bezier_tool, game_of_life, clock) are fixed.

When I use iced_glow (`--features glow,glow_canvas`), all programs are fixed.

- Strangely, glow's default font is Lato, but otherwise the default font is Arial.
- tour doesn't compile:

```
error[E0277]: the trait bound `iced_glow::backend::Backend: iced_graphics::backend::Image` is not satisfied
   --> examples\tour\src\main.rs:675:5
    |
675 |     Container::new(
    |     ^^^^^^^^^^^^^^ the trait `iced_graphics::backend::Image` is not implemented for `iced_glow::backend::Backend`
    |
    = note: required because of the requirements on the impl of `iced_native::widget::image::Renderer` for `iced_graphics::renderer::Renderer<iced_glow::backend::Backend>`       
    = note: required because of the requirements on the impl of `std::convert::From<iced::Image>` for `iced_native::element::Element<'_, _, iced_graphics::renderer::Renderer<iced_glow::backend::Backend>>`
    = note: required because of the requirements on the impl of `std::convert::Into<iced_native::element::Element<'_, _, iced_graphics::renderer::Renderer<iced_glow::backend::Backend>>>` for `iced::Image`
    = note: required by `iced_native::widget::container::Container::<'a, Message, Renderer>::new`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `tour`.
```

## Related bugs

Bug #427 was also worked around by disabling antialiasing or switching to glow. That bug may be related because the same antialiasing method is used in both. However, that bug was reported on a different OS, different GPU, and probably different backend API.

## Specs

- OS: Windows 10 1909 (18363.1082) x64
- GPU: AMD Radeon(TM) RX Vega 10 Graphics
- Drivers: Radeon Software 20.8.1 (outdated), 20.9.1 (latest)
- Screenshots were taken at 125% Windows DPI scale, but the issues persist at 100% (I only tested game_of_life)

**Comment by justinmoon** [comment]
I ran `tour` with `glow` enabled from WSL2, and get the same `the trait `iced_graphics::backend::Image` is not implemented for `iced_glow::backend::Backend`` error.

My GPU is Intel(R) HD Graphics 620.

**Comment by hecrj** [comment]
The `antialiasing` flag enables `PowerMode::HighPerformance` in `wgpu`. As a result, your OS may be choosing a different GPU for rendering the example.

I recommend you to test the examples of [`wgpu_glyph`](https://github.com/hecrj/wgpu_glyph) and report any issues there.
