### ISSUE TITLE
Can not display "tab" character in Text widget

### ISSUE THREAD

**Issue by wyhhh** [iced-rs/iced#540]
```rust
v.push(
   Text::new(String::from("Hello\tRust!"))
   .width(Length::Fill)
  .horizontal_alignment(HorizontalAlignment::Center)
  .into());
```
I made this code, it seems that no display of `tab` character.

**Comment by twitchyliquid64** [comment]
I imagine the underlying font glyph library does no shaping, and doesnt handle the tab character specially if your font has no glyph for it.

It might be easier to just replace tab character with two or four spaces, whatever your preference is. Or use a font that has a (whitespace) glyph for the tab character.

**Comment by twitchyliquid64** [comment]
Its hard to trace, but if you are using wgpu, I think no shaping is done any only the horizontal movement + kern values are [used](https://github.com/alexheretic/glyph-brush/blob/d57f4f06c297890c624b548ff7d559ad7d0fcd20/layout/src/words.rs#L116) to layout text.

I wonder what the best-in-class Rust shaping engine is? Maybe we can switch to something like fontdue (well, just for shaping/layout) in the future?

**Comment by wyhhh** [comment]
thank you for your reply!

**Comment by dhardy** [comment]
> I wonder what the best-in-class Rust shaping engine is?

We're not there yet, but allsorts and rustybuzz are going in that direction. But shaping alone isn't enough. See my blog post: https://kas-gui.github.io/blog/why-kas-text.html
