### ISSUE TITLE
Visual artifacts / lag when resizing window

### ISSUE THREAD

**Issue by MOZGIII** [iced-rs/iced#546]
I'm running the latest iced examples on Ubuntu 20.04, and when I'm resizing the window, the framerate drops below 60 fps (it's visually distinguishable, sometimes visual artifacts - black bars - appear in the portions of the window that couldn't update in time).

This doesn't seem like a big issue, however, I'd like to know if it can be dealt with.

Is there a way to work around it, or solve it in the app implementation?
Is there a way to solve this on the `iced` side?

**Comment by Songtronix** [comment]
Do you run in release mode? (`cargo run --release`)
