### ISSUE TITLE
macOS crashes on start, most likely due to font_kit.

### ISSUE THREAD

**Issue by casperstorm** [iced-rs/iced#548]
Hi,

A user who is using a small application I made says it crashes on boot. I made him compile it himself and send me traceback:
[ajour_full_backtrace_log.txt](https://github.com/hecrj/iced/files/5321794/ajour_full_backtrace_log.1.txt).

Lumpio from ##Rust said the following which seems very relevant (thank you!):

> 16:10 <Lumpio-> https://developer.apple.com/documentation/coregraphics/1408288-cgdataprovidercreatewithdata
> 16:10 <Lumpio-> This suggests the return value should be release with CGDataProviderRelease instead of CFRelease but > the only different is that "CGDataProviderRelease doesn't fail if the parameter is NULL"
> 16:10 <Lumpio-> And judging by your trace it is null, casperstorm
> 16:11 <Lumpio-> Why is it null though, that is the question
> 16:12 <Lumpio-> https://github.com/servo/font-kit/commit/ec11b73c4801444dd3eabe9d334ec644d66fc5b3#diff-be1a21cf9e43b649f726ac7cb25a7182R86
> 16:12 <Lumpio-> The bit that ends up calling that seems to have been changed very recently
> 16:12 <Lumpio-> The message was about fixing memory leaks though, not outright crashes.

**Comment by hecrj** [comment]
I am going to close this for now, since `font-kit` has likely changed a bunch since the issue was opened.

In any case, if the bug is still present, we should report it to the `font-kit` maintainers.
