### ISSUE TITLE
Hello World application panics "OutOfMemory" resizing the window

### ISSUE THREAD

**Issue by TheLonelyAdventurer** [iced-rs/iced#551]
Hello, I was looking for a cross-platform gui crate and found this project.
I really like the idea of using Elm's architecture.

### Version
`cargo rust --version`: rustc 1.46.0 (04488afe3 2020-08-24)
iced: 0.1.1
other dependencies: none

### Bug description
I copied the "Hello World" example from https://docs.rs/iced/0.1.1/iced/trait.Application.html and, out of frustration, I shaked the mouse cursor for about 7 to 12 seconds (I am able to reproduce it, but varies) while resizing the application window. It panicked and crashed.

### Backtrace in debug run (RUST_BACKTRACE=full)
[debug.log](https://github.com/hecrj/iced/files/5328856/debug.log)

### Behaviour with --release (RUST_BACKTRACE=full)
The issue is present as well. Produces this backtrace.
[release.log](https://github.com/hecrj/iced/files/5328859/release.log)

### Steps to reproduce the error
Run `cargo run` or `cargo run --release` and try to resize the window shaking the mouse cursor all around the screen for about 10 seconds. I also experienced issue #546 .

### Machine and OS details
- Windows 10 Home
- Screen resolution: 4K UHD (3840x2160@60hz, 250% zoom)
- RAM: 16GB
- CPU: Intel Core i7-9750H (Coffee Lake-H SRF6U)

Also, I read wgpu-native in the log, so I thought it was related:
- GPU: Intel UHD Graphics 630 (Coffee Lake-H GT2) / NVIDIA RTX 2070 Max-Q (TU106M)

I'm sorry if this isn't really a use case.

If you need anything more, I'll be pleased to help.

**Comment by hecrj** [comment]
`master` has changed considerably since the latest release. Does this happen with any of the current examples?

**Comment by TheLonelyAdventurer** [comment]
> 
> 
> Thanks for the detailed report!
> 
> `master` has changed considerably since the latest release. Does this happen with any of the current examples?

You're welcome.

I cloned the repo with `git clone` and ran `cargo build`.
Then, I ran `cargo run --package clock` and tried to reproduce the error, and yes, it panicked with the same behaviour.

Actually, it happens with a variation. It looks like it takes less to panic if I try to resize it from the bottom-right corner.

Also, issue #546 still occurs.

I also noticed a 500ms to 1second lag for the clock to render the first time.

I'm attaching the log here.

[debug.log](https://github.com/hecrj/iced/files/5329030/debug.log)

**Comment by hecrj** [comment]
Thanks for testing!

Do the examples in [the `wgpu-rs` repository](https://github.com/gfx-rs/wgpu-rs/tree/v0.6) have the same issue?

**Comment by Kaiden42** [comment]
Could be related to #518

**Comment by TheLonelyAdventurer** [comment]
> 
> 
> Thanks for testing!
> 
> Do the examples in [the `wgpu-rs` repository](https://github.com/gfx-rs/wgpu-rs/tree/v0.6) have the same issue?

Just cloned wgpu v0.6.0 and tried to reproduce the error.

Yeah, it does occur. I tried with the hello-window example.

I'm attaching the log here, but I think I should open an issue to wgpu if there isn't already.

[debug.log](https://github.com/hecrj/iced/files/5329157/debug.log)

Notice: the windows took about 1 second to render and the issue occurred **immediately** and not just after a few seconds.

Also, #546 occurs as well.

**Comment by TheLonelyAdventurer** [comment]
> 
> 
> Could be related to #518

I just checked the attached video to that one issue. I think I didn't check the issue list well.

It behaves exactly the same, but I think we could consider this to be wgpu's fault.

**Comment by TheLonelyAdventurer** [comment]
@hecrj @Kaiden42 There is in fact an open issue https://github.com/gfx-rs/wgpu-rs/issues/571 on their repo.

I'm going to report it there as well.
