### ISSUE TITLE
More icons in icon font?

### ISSUE THREAD

**Issue by Kaiden42** [iced-rs/iced#555]
I noticed that the icon font only contains two icons. The `arrow down` and `checkmark` icon. Is it planned to have more than this two icons in the future?

For the widget I'm currently working on, I would like to have the `clear` icon. As I can see, the font was created with [Fontello](http://fontello.com). I assume the arrow down and checkmark icon are from Font Awesome, am I right?

Fontello provides an im- and export of a config file. This could be helpfull for contributors to add the icons, they would like to have, to the font, without the need to configure everything again.

How were the values `'\u{E800}'` for the arrow down icon, and `'\u{F00C}'` for the checkbox icon determined?

**Comment by hecrj** [comment]
The built-in icon font is meant to provide icons for the built-in widgets.

If you want to use additional icons, you can always use your own custom font with [the `Font` enum](https://docs.rs/iced/0.1.1/iced/enum.Font.html).

**Comment by Kaiden42** [comment]
I'm currently experimenting with a Tabs widget. While it is indeed using custom icon fonts for showing icons on the tabs, there is one icon, for closing a tab, that I would like to have build-in, when the widget could become a build-in widget (This depends on your choice :) ). That's why I was asking.

I will talk more about this in the upcomming days.

**Comment by 13r0ck** [comment]
@Kaiden42 
I'm assuming that you got this one figured out by now :). Do you think you could close this?
