### ISSUE TITLE
iced is excellent! I have some suggestions.

### ISSUE THREAD

**Issue by xiuno** [iced-rs/iced#565]
I compared iced and druid, found that the componets of iced are more standardized and beautiful, the supported platforms are more popular, druid have not ios & android.

I think Component should be divided into two layers, iced provides basic controls, crate iced-basic:
 Input, Button, Text, Font, SVG, File,Image,Select, Radio, LocalStorage API, Camera, Location, Notification...  

Then based on iced, make another crate iced-widgets:
Layout, Modal, Navbar, Paitionation, Alert, Confirm, Tab, Card, Panel, Progress, Popover, FadeIn, FadeOut, Animation, Download, Album, FileBrowser...

**Comment by hecrj** [comment]
Thanks for the suggestions and the kind words!

> ruid have not ios & android

Keep in mind that `iced` does not officially support iOS nor Android either.

> iced provides basic controls, crate iced-basic [...]
> Then based on iced, make another crate iced-widgets

Yes, I think this may be a good idea in the long run. In fact, it may be interesting to be even more granular based on the dependencies of each widget.

Also, not every widget crate needs to be implemented and maintained by me! Users of the library should be able to share their own. [`iced_audio`](https://github.com/BillyDM/iced_audio) is a great example of this.

In any case, I believe splitting may be a bit overkill currently, given that we do not have a lot of built-in widgets yet.

**Comment by xiuno** [comment]
iced base on winit, winit supports ios & Android, so I think iced naturally supports ios & Android.
![image](https://user-images.githubusercontent.com/3362277/97410832-824fd680-193a-11eb-97f6-fb3530939214.png)

About layering, maybe the time is early yet, and can consider it later.
