### ISSUE TITLE
`Primitive::Text.bounds` has semantic meaning depending on alignment

### ISSUE THREAD

**Issue by twitchyliquid64** [iced-rs/iced#567]
[Primitive::Text](https://github.com/hecrj/iced/blob/d34f8e06c8e3cdbba07a272f346163cfc0f920a6/graphics/src/primitive.rs#L20) is defined as:

```rust
    Text {
        /// The contents of the text
        content: String,
        /// The bounds of the text
        bounds: Rectangle,
        /// The color of the text
        color: Color,
        /// The size of the text
        size: f32,
        /// The font of the text
        font: Font,
        /// The horizontal alignment of the text
        horizontal_alignment: HorizontalAlignment,
        /// The vertical alignment of the text
        vertical_alignment: VerticalAlignment,
    },
```

Based on the doc comments, I would assume that `bounds.x` & `bounds.y` refer to the bounding box top-left, and `width+x` + `height+y` refer to the bottom right.

This is only true if alignment is set to `Left` & `Top`:

```rust
        let x = match horizontal_alignment {
            iced_native::HorizontalAlignment::Left => bounds.x,
            iced_native::HorizontalAlignment::Center => bounds.center_x(),
            iced_native::HorizontalAlignment::Right => bounds.x + bounds.width,
        };

        let y = match vertical_alignment {
            iced_native::VerticalAlignment::Top => bounds.y,
            iced_native::VerticalAlignment::Center => bounds.center_y(),
            iced_native::VerticalAlignment::Bottom => bounds.y + bounds.height,
        };
```

Hence, the `bounds` X/Y change, mapping to the input X/Y position that the wgpu backend expects for text of that alignment.

This has proven very challenging to work around for the `raqote` backend, which always needs the top-left X/Y position.

Could we either:

1. Change the semantics so `bounds` is always the bounding box, or
2. Provide the information from `TextBackend::measure()` in the primitive, so its easier to recompute the correct position (rather than either caching text runs in the backend or re-adding all the glyph sizes)

**Comment by hecrj** [comment]
I talked a bit about this in https://github.com/hecrj/iced/pull/377#pullrequestreview-422212852.

For a `raqote` backend, I believe it may be interesting to not use `Primitive` at all and instead implement the widget `Renderer` traits directly. We can find and discuss any similarities later.
