### ISSUE TITLE
Error with wgpu-native-0.4.3 when running on Linux

### ISSUE THREAD

**Issue by sum-elier** [iced-rs/iced#571]
When running an application compiled targeting x86_64-unknown-linux-gnu with `ìced = "0.1.1"`, throws this error:
```rust
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-native-0.4.3/src/instance.rs:474:72
```
Looks like this is not in the master version of `wgpu-native` but only the last published version to crates.io; is this error fixed in the latest version from wgpu-native? Searching around github the problem was supposedly fixed by the introduction of glow but seems not, could be a graphics driver issue?

Thanks!

**Comment by twitchyliquid64** [comment]
> Searching around github the problem was supposedly fixed by the introduction of glow but seems not

You have to use `features = ["glow"]` to enable the glow backend.

The version published on crates.io is miles behind. Can you try pointing the crate at master and see if the thread still panics?

**Comment by sum-elier** [comment]
How do I enable this feature? When I do `iced = {version = "0.1.1", features = ["glow"]}` it just errors with

> the package `xyz` depends on `iced`, with features: `glow` but `iced` does not have these features.

Also, what's the best way to point to master directly?

**Comment by twitchyliquid64** [comment]
I dont think glow is in `0.1.1`. Try:

```
[dependencies]
iced = { git = "https://github.com/hecrj/iced", rev = "23647d2f50f0e177b93cf09c72886a90702df982", version = "0.1.0" }
iced_winit = { git = "https://github.com/hecrj/iced", rev = "23647d2f50f0e177b93cf09c72886a90702df982", version = "0.1.1" }
iced_native = { git = "https://github.com/hecrj/iced", rev = "23647d2f50f0e177b93cf09c72886a90702df982", version = "0.2.2" }
iced_graphics = { git = "https://github.com/hecrj/iced", rev = "23647d2f50f0e177b93cf09c72886a90702df982", version = "0.1.0" }
```

**Comment by sum-elier** [comment]
By declaring the dependency in this way, will this fetch the latest version from master when doing `cargo update`?

**Comment by twitchyliquid64** [comment]
I think theres a way to track `master` instead of a specific git revision, but i don't know it off the top of my head (check the cargo docs)

**Comment by sum-elier** [comment]
Will do. Crossing fingers this solves the initial issue. Thank you

**Comment by twitchyliquid64** [comment]
How'd u go @sum-elier ? Did you manage to get `glow` working for you?

**Comment by sum-elier** [comment]
@twitchyliquid64 Kinda. Managed to have it detect `glow` but had to cease using it because I am using the `svg` feature which isn't supported. ... But updating to the latest Iced version seems to have fixed the initial reported error. At least now it runs but doesn't show anything, just opens and closes without showing any GUI. Thought it was panicking but after installing an `panic::set_hook` couldn't see any errors.
