### ISSUE TITLE
PickList requires Copy trait, severely limiting its use

### ISSUE THREAD

**Issue by olson-dan** [iced-rs/iced#572]
I have something like this:

```rust
#[derive(Debug, Clone, PartialEq, Eq)]
struct Item {
  id: u32,
  description: String,
}

impl std::fmt::Display for Item {
 // ...
}

struct State {
  items: Vec<Item>,
  selected_item: Option<Item>,
  dropdown: pick_list::State<Item>
}

// ...

fn view(&mut self) -> Element<Message> {
  // ...
  let dropdown = PickList::new(&mut self.dropdown,
    &self.items,
    self.selected_item,
    Message::ItemSelected);
  // ...
}
```

This does not work because the third parameter to `PickList::new()` takes an `Option<T>` and requires `Copy` to be implemented.  This prevents any type that implements `String` from being used with `PickList`, which is highly limiting.

**Comment by twitchyliquid64** [comment]
Have a look at #467 - basically just have the `T` in `PickList` be an index into state at a higher scope, and implement `impl std::fmt::Display` to resolve that string.

**Comment by olson-dan** [comment]
> 
> 
> Have a look at #467 - basically just have the `T` in `PickList` be an index (ie: fixed-size newtype) into state at a higher scope, and implement `impl std::fmt::Display` to resolve that string.

Thanks for the suggestion.  Pardon me if I'm not following along, but how would one pass state into a Display implementation without storing it in the struct or using a global?

**Comment by hecrj** [comment]
We may be able to accept a reference as the third argument. I'll look into it!

For the time being, you should be able to circumvent the issue with an explicit clone: `self.selected_item.clone()`.

**Comment by olson-dan** [comment]
> For the time being, you should be able to circumvent the issue with an explicit clone: `self.selected_item.clone()`.

Thanks, it was silly of me to not try that!
