### ISSUE TITLE
Draw raster images in `Canvas`

### ISSUE THREAD

**Issue by savente93** [iced-rs/iced#582]
I've been trying to make an app that can make simple image annotations. As far as I can see `Image` doesn't `impl Layer`, meaning that I can't add it to a `Canvas`.  This seems like a good thing to me, especially since a "paint clone" is mentioned in the Roadmap? I'm wondering how easy this would be to implement, and whether this would be the correct way to go about it, or whether there is an easier way. If it's not too complicated, I'd be willing to try and make a PR for it. Thoughts?

**Comment by tinaun** [comment]
I would like a Frame.draw_image(imageRect, canvasRect) function, much like the function in js's canvas

**Comment by shssoichiro** [comment]
Hi, I wanted to see if there was any update on this, or if someone had found a workaround for it? This is a blocker for the project I'm currently working on, where I want to render an RGB image as the base layer in a canvas, then draw annotations, grids, etc. on top of it.

**Comment by hardesh** [comment]
Hi, I'm also looking for this. Is there any update on this?

**Comment by justDeeevin** [comment]
resolved by #2537. Use `Frame::draw_image` or `Frame::draw_svg`.
