### ISSUE TITLE
entire thread closes on window close, using another thread is not allowed by winit.

### ISSUE THREAD

**Issue by toastmod** [iced-rs/iced#602]
i noticed that closing a window closes the entire thread, how can i make it so that the program continues after the window is closed?
im not able to run iced on another thread besides the main thread as i get this when i try:

```
Initializing the event loop outside of the main thread is a significant cross-platform compatibility hazard. If you really, absolutely need to create an EventLoop
on a different thread, please use the `EventLoopExtWindows::new_any_thread`
```

i'd also like to point out that there is a problem with sharing COMs on certain threads. for example in one of my programs my main function calls CPAL's audio thread before starting my iced GUI, but im given an error about different COM modes. I have to get to a math assignment right now so i will post about the COM problem later. thanks!

**Comment by hecrj** [comment]
Fixed by #1112!
