### ISSUE TITLE
gfx-hal renderer

### ISSUE THREAD

**Issue by huisedenanhai** [iced-rs/iced#611]
Is there any plan for a gfx-hal renderer? It will be a great help for those who want to integrate iced in their gfx-hal applications.

**Comment by hecrj** [comment]
Personally, I do not have plans to work on a `gfx-hal` renderer. `gfx-hal` is extremely low-level and unsafe. It'd take me a lot of effort to build a proper renderer on top of it.

That said, `wgpu` uses `gfx-hal` internally, and they have yet to explore interoperability: https://github.com/gfx-rs/wgpu-rs/issues/34.
