### ISSUE TITLE
Unable to compile examples/events from a clone

### ISSUE THREAD

**Issue by mscofield0** [iced-rs/iced#621]
Unable to compile examples/events from a clone on Ubuntu 20.04.

Output log: <https://hasteb.in/cuxumabo.yaml>

**Comment by manokara** [comment]
You must install the development version of the freetype library: `sudo apt install libfreetype-dev`

**Comment by mscofield0** [comment]
Did not fix the issue: <https://hasteb.in/upiyitoc.yaml>

**Comment by manokara** [comment]
Now you need to install `libexpat1-dev`. It's likely that you're going to face more dependency issues, so look at the lines before "stack trace [...]" for something like "X is needed" or "X not found" and look for X in `apt` or even in the Software Center (I'm not sure if system libraries show up there though), and get the one with `-dev` at the end.

We probably should maintain a list of packages for popular distros at some point to avoid this problem.

**Comment by hecrj** [comment]
You can also try to disable the `font-kit` dependency with the `--no-default-features` flag:

```
cargo run --no-default-features --features wgpu --package <example>
```

**Comment by mscofield0** [comment]
After installing `libexpat1-dev` I ran the build again, and now it just freezes my entire OS when compiling `styling`. Lol...

**Comment by hecrj** [comment]
Any updates on this? I will pre-emptively close, but feel free to reopen!

We will include a building section with a list of the required dependencies in the upcoming guidebook at https://book.iced.rs/
