### ISSUE TITLE
Clock example crashes on Mac after running for a few seconds

### ISSUE THREAD

**Issue by Hodkinson** [iced-rs/iced#642]
Same thing happens with the game-of-life example, but for me only when the window is expanded to be large.

No crash happens when run with features "glow" and "glow_canvas", or if anti-aliasing is false.

[clock.txt](https://github.com/hecrj/iced/files/5614493/clock.txt)

**Comment by hecrj** [comment]
Could you retry with the latest `master` branch? Reopen the issue if the problem is still present.
