### ISSUE TITLE
Can I load fonts dynamically?

### ISSUE THREAD

**Issue by Erxl** [iced-rs/iced#659]
I want to load fonts dynamically from the system fonts folder ,but I noticed `default_font`  in `Settings `is `static`

**Comment by twitchyliquid64** [comment]
You can do it on a per-text basis if you want to get around the static:

https://github.com/hecrj/iced/blob/d16b9cf7cd98a3d65ea5408ac9b72298cb267e85/examples/todos/src/main.rs#L455-L466

Alternatively if you do want to dynamically choose a default font, you can load it into a `Box`, and then safely [leak](https://doc.rust-lang.org/std/boxed/struct.Box.html#method.leak) it into the `'static` lifetime. Though of course this will eat a lil memory for the life of your program.
