### ISSUE TITLE
`glow` backend does not support `Image`

### ISSUE THREAD

**Issue by rednaz1337** [iced-rs/iced#674]
Is it possible to run the `tour` example with the glow backend? when I add the `glow` feature to the example's `Cargo.toml` I get the following error:

```
error[E0277]: the trait bound `iced_glow::backend::Backend: iced_graphics::backend::Image` is not satisfied
   --> examples/tour/src/main.rs:675:5
    |
675 |     Container::new(
    |     ^^^^^^^^^^^^^^ the trait `iced_graphics::backend::Image` is not implemented for `iced_glow::backend::Backend`
    |
    = note: required because of the requirements on the impl of `iced_native::widget::image::Renderer` for `iced_graphics::renderer::Renderer<iced_glow::backend::Backend>`
    = note: required because of the requirements on the impl of `From<Image>` for `iced_native::element::Element<'_, _, iced_graphics::renderer::Renderer<iced_glow::backend::Backend>>`
    = note: required because of the requirements on the impl of `Into<iced_native::element::Element<'_, _, iced_graphics::renderer::Renderer<iced_glow::backend::Backend>>>` for `Image`
    = note: required by `iced_native::widget::container::Container::<'a, Message, Renderer>::new`
```

It seems like the `Image` widget is not supported on the `glow` backend.

**Comment by cryptoquick** [comment]
Yeah, it looks like there's no `iced_glow/image` implementation, like there is for `iced_wgpu/image`.

**Comment by cryptoquick** [comment]
Related to #354

**Comment by genbyte** [comment]
Probably not the right place to ask, but is anyone working on `Image` for `iced_glow`? I'd very much like it to be a thing and would be happy to give `Image` a glow if someone isn't already working on it.

**Comment by hecrj** [comment]
The current `Image` implementation has a bunch of underlying issues! https://github.com/iced-rs/iced/labels/image

Instead of porting the existing code to the `glow` backend, we should focus on coming up with a proper implementation that addresses all of these issues.
