### ISSUE TITLE
Error: GraphicsAdapterNotFound

### ISSUE THREAD

**Issue by xin-water** [iced-rs/iced#677]
iced-examples on ArchLinux and windows7  is Error: GraphicsAdapterNotFound ; but gtk and orbtk is normal operation；

**Comment by katyo** [comment]
I have same issue on `nixos` with `nouveau`.
Possibly related to missing support of `vulkan` gfx api.

**Comment by yusdacra** [comment]
> I have same issue on `nixos` with `nouveau`.
> Possibly related to missing support of `vulkan` gfx api.

I'm on NixOS too and yes, one will get this error by default. This happens because the Vulkan library (among other libraries) cannot be found when the application tries to `dl_open`. This can be fixed if you set your `LD_LIBRARY_PATH` to where these libraries are, which can be done with Nix:
```nix
{ pkgs ? import <nixpkgs> { } }:
  let
  neededLibs = with pkgs; (with xorg; [ libX11 libXcursor libXrandr libXi ])
    ++ [ vulkan-loader wayland wayland-protocols libxkbcommon ];
  in with pkgs;
  mkShell {
    shellHook = ''
      export LD_LIBRARY_PATH=${lib.makeLibraryPath neededLibs}
    '';
  }
```
example as a Nix shell. Note that just having these packages in your environment *will not* fix the issue.

**Comment by katyo** [comment]
Thx @yusdacra 
But seems the vulkan only backend is supported:
```
[2021-01-07T18:37:26Z ERROR gfx_backend_vulkan]
    GENERAL [Loader Message (0)] : setupLoaderTermPhysDevs:  Failed to detect any valid GPUs in the current config
    object info: (type: INSTANCE, hndl: 93854623489360)

[2021-01-07T18:37:26Z ERROR gfx_backend_vulkan]
    GENERAL [Loader Message (0)] : setupLoaderTrampPhysDevs:  Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader to get count.
    object info: (type: INSTANCE, hndl: 93854623489360)

[2021-01-07T18:37:26Z ERROR gfx_backend_vulkan]
    GENERAL [Loader Message (0)] : setupLoaderTermPhysDevs:  Failed to detect any valid GPUs in the current config
    object info: (type: INSTANCE, hndl: 93854623489360)

[2021-01-07T18:37:26Z ERROR gfx_backend_vulkan]
    GENERAL [Loader Message (0)] : setupLoaderTrampPhysDevs:  Failed during dispatch call of 'vkEnumeratePhysicalDevices' to lower layers or loader to get count.
    object info: (type: INSTANCE, hndl: 93854623489360)

[2021-01-07T18:37:26Z ERROR gfx_backend_vulkan] Could not enumerate physical devices! Initialization of a object has failed
Error: GraphicsAdapterNotFound
```
IIRC `wgpu` has basic support for gl

**Comment by twitchyliquid64** [comment]
For now (iced 0.2) you need Vulkan on Linux. Most modern installs shouldn't have an issue (have you installed Vulkan Mesa packages?).

> IIRC wgpu has basic support for gl

Iced has its own backend for openGL, with its own set of limitations. You can enable it with the `glow` feature.

**Comment by katyo** [comment]
@twitchyliquid64 Unfortunately nouveau graphics driver does not support the Vulkan API for now.

**Comment by twitchyliquid64** [comment]
@katyo Mesa has a pretty speedy CPU emulation for Vulkan if youre stuck with hardware vendors that doesn't play well with Linux

**Comment by katyo** [comment]
@twitchyliquid64 I have no ideas how to get it works.

**Comment by twitchyliquid64** [comment]
What distro are you on?

**Comment by katyo** [comment]
Seems it works fine with google's swiftshader.

**Comment by twitchyliquid64** [comment]
Wut? how did you glue switftshader to iced?

**Comment by katyo** [comment]
I just add swiftshader to buildInputs in my shell.nix

**Comment by twitchyliquid64** [comment]
Ah, you installed it and now it looks like Iced is working via swiftshaders' CPU implementation?

**Comment by katyo** [comment]
@twitchyliquid64 yep, this just works with acceptable performance
This is my `shell.nix`:
```nix
{ pkgs ? import <nixpkgs> {} }:
with pkgs;
mkShell rec {
    name = "shell";
    nativeBuildInputs = [pkgconfig gdb];
    buildInputs = [
        openssl freetype expat
        vulkan-loader vulkan-tools
        wayland wayland-protocols libxkbcommon swiftshader
    ] ++ (with xorg; [
        libX11 libXcursor libXrandr libXi
    ]);
    shellHook = ''
        export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${lib.makeLibraryPath buildInputs}";
    '';
}
```

**Comment by twitchyliquid64** [comment]
Nice!

**Comment by Randall-Coding** [comment]
For me adding the "glow" feature to iced in Cargo.toml fixes this problem.

I'm running Ubuntu 18.04 LTS.

**Comment by twitchyliquid64** [comment]
(Nit note: the glow feature is an entirely different graphics backend based on openGL - its doesnt fix the issue of not having a modern graphics pipeline on your system).

**Comment by Randall-Coding** [comment]
Interesting thanks.

**Comment by Randall-Coding** [comment]
@twitchyliquid64   Yeah I'm noticing some of the example packages won't work using "glow".  I guess that is related to what you are talking about :( 

So when you say there is no modern graphics pipeline on my system, is that a hardware or a software problem?  And how modern is modern?
