### ISSUE TITLE
How to create a new window from update()

### ISSUE THREAD

**Issue by rnd-ash** [iced-rs/iced#680]
I cannot find any documentation on how to do this.

Essentially my app requires a launcher UI where a user can connect to an API DLL, and once selected and verified that the DLL works, the user should then be placed into the main application as such.

In my launcher's update function, I have the following code:

```rust
fn update(&mut self, message: Self::Message) -> Command<Self::Message> {
        match message {
            Message::DeviceSelected(name) => self.selected_device = name,
            Message::Launch => {
                println!(
                    "Launch requested. Selected device: {}",
                    self.selected_device
                );
                // Try to connect with the device
                match self.load_device() {
                    Ok((details, driver, idx)) => {
                        println!("Ready to launch!");
                        // TODO Create main window
                    }
                    Err(e) => self.summary_text = e,
                }
            }
        }
        Command::none()
    }
```
As far as i can tell however, there is no way of launching a new application window, and closing the current one down from within this update function. Also, how would one pass the 3 parameters details, driver, and idx to the new window? - Since Application::run only takes settings.

Any ideas?

**Comment by twitchyliquid64** [comment]
Unfortunately it doesn't look like theres a way currently to bail out of a running `iced::Application` and execute elsewhere. It may be possible to have control over this if you manage the event loop yourself (ie: like how the integration example does it), but otherwise I dont think this is supported yet :/

**Comment by hecrj** [comment]
I believe this use case may be satisfied by #1112. Feel free to reopen otherwise!
