### ISSUE TITLE
Minimize clones in from_memory

### ISSUE THREAD

**Issue by cryptoquick** [iced-rs/iced#681]
Would it be worth making a generic interface for both passing byte slice references, or a boxed byte slice, rather than just the owned byte vec for the from_memory method?

https://docs.rs/iced_native/0.3.0/iced_native/widget/image/struct.Handle.html#method.from_memory

The reason I ask is because the image crate accepts a byte slice reference here:

https://docs.rs/image/0.23.12/image/fn.load_from_memory.html

I had to do the following here, and I'm unsure if it's suboptimal because of the number of clone operations:

https://github.com/FuzzrNet/Fuzzr/pull/60/files

If so, I could submit a PR.

**Comment by hecrj** [comment]
In general, you should not create an `image::Handle` inside `view`, which is very expensive. Instead, you should store the `Handle` in your application state and `clone` it in `view`.
