### ISSUE TITLE
Get access to physical key events

### ISSUE THREAD

**Issue by Woyten** [iced-rs/iced#688]
I would like to turn [`microwave`](https://crates.io/crates/microwave) into an app that runs both on desktop and web environments.

To me it seems that `iced` is the most promising candidate to achieve this goal. My first experience with it was very pleasant and everything worked out-of-the box.

However, to fully migrate [`microwave`](https://crates.io/crates/microwave) to `iced` I need to access the physical location / scan code of keyboard events. It seems that this is not possible at the moment.

**Comment by dhardy** [comment]
Are you aware of https://github.com/rust-windowing/winit/issues/1806 ?

Currently I believe it is possible to get scancodes, though these are platform-specific and not really much use aside from matching the same key again (though IIUC they may not be unique on Windows). Physical key location is planned but I'm not sure at the moment exactly how that will look (probably equivalent key on US-ASCII layout, with `None` for extra media keys).

**Comment by Woyten** [comment]
Thanks for sharing your ideas. Is there an idiomatic way to register an onkeydown event listener on some canvas component which feeds OnKeyDownEvents into the main loop of iced?

**Comment by hecrj** [comment]
@Woyten You can listen to keyboard events in [`canvas::Program::update`](https://docs.iced.rs/iced_graphics/widget/canvas/trait.Program.html#method.update) and return a `Message` for the `Application` when necessary.
