### ISSUE TITLE
Make renderer settings a child of global settings

### ISSUE THREAD

**Issue by semtexzv** [iced-rs/iced#689]
Current implementation just copies shared fields between the 
`src/settings.rs`
`src/glow/setting.rs`
`src/wgpu/settings.rs` 
This approach makes it impossible to pass renderer-specific settings to the renderer ( eg. specifying custom texture format )

I propose making the renderer crate public, and adding the settings to the global settings. This renderer-specific field is bound by implementation of Default, and can be set to `Default::default()` in almost all cases, preserving old behavior while adding capability to customize the lower level details.

This is needed to run iced on android device ( My device doesn't support BGRA TextureFormat, but supports RGBA ).

The goal of this issue is to find whether you're open to this idea, or there are other approaches.
I have something running in https://github.com/semtexzv/iced/tree/renderer-settings

**Comment by hecrj** [comment]
This is intended.

`iced` consists in different abstraction layers that change based on the target (check out the [`ECOSYSTEM`](https://github.com/hecrj/iced/blob/master/ECOSYSTEM.md) guide for more details) and, ideally, we want to avoid exposing any of the renderer implementation details at the outermost layer (i.e. the `iced` crate).

Instead, the subcrates are meant to allow for further configuration and flexibility. For instance, [`iced_winit`](https://docs.rs/iced_winit/0.2.0/iced_winit/index.html) has [a `run` function](https://docs.rs/iced_winit/0.2.0/iced_winit/application/fn.run.html) that takes some [`Compositor::Settings`](https://docs.rs/iced_graphics/0.1.0/iced_graphics/window/trait.Compositor.html#associatedtype.Settings).
