### ISSUE TITLE
Add bold and italic variants for the default font.

### ISSUE THREAD

**Issue by a2aaron** [iced-rs/iced#708]
It looks like the default font doesn't have any bold or italic variants. I see that doing inline bold/italics is currently a WIP, but it would be nice to have some access to a bold/italic version of the default font if possible (this is helpful, for example, for making sure that headings have enough weight to them).

Note that [Lato](https://fonts.google.com/specimen/Lato), the default font, does indeed have bold and italic versions.

**Comment by madmaxio** [comment]
No bold option at the moment, right?

**Comment by hecrj** [comment]
I believe we should tackle this once we work on #156.

**Comment by kiedtl** [comment]
For anyone who came here via Google search, like me: Iced does in fact support bold variants, through the `weight` field of `iced::font::Font`:

```
text("Foo")
.font(font::Font{
    weight: iced::font::Weight::Bold,
    ..font::Font::DEFAULT
})
```
