### ISSUE TITLE
Noto Color Emoji font not rendering for the Text widget

### ISSUE THREAD

**Issue by samyak-jain** [iced-rs/iced#734]
```rust
use iced::{Color, Element, Font, Sandbox, Settings, Text};

pub fn main() -> iced::Result {
    Hello::run(Settings::default())
}

struct Hello;

impl Sandbox for Hello {
    type Message = ();

    fn new() -> Hello {
        Hello
    }

    fn title(&self) -> String {
        String::from("A cool application")
    }

    fn update(&mut self, _message: Self::Message) {
        // This application has no interactions
    }

    fn view(&mut self) -> Element<Self::Message> {
        const ICONS: Font = Font::External {
            name: "Icons",
            bytes: include_bytes!("/usr/share/fonts/noto/NotoColorEmoji.ttf"),
        };
        Text::new("🐱").color(Color::BLACK).font(ICONS).into()
    }
}
```

I just end up getting a blank screen. However, if I switch out with any other font which supports this character, it renders properly. 
The only difference I can see in this font is that Noto is actually colored. Could this be a reason why it's not rendering?

**Comment by hecrj** [comment]
Could be. Our text rendering strategy isn't very sophisticated (see #33).

**Comment by twitchyliquid64** [comment]
IIRC Noto emoji's use embedded PNGs, which isnt supported by glyph-brush (once of Iced' dependencies).

**Comment by samyak-jain** [comment]
@twitchyliquid64 Makes sense. Do you know any way I can work around this? Some way I can go with a unicode codepoint -> The embedded png -> Iced Image Handle? Maybe there's a way to render this as an image rather than text. Do you think that's possible?

@hecrj, In light of what @twitchyliquid64 has said, do you think solving this should be a part of #33?

**Comment by twitchyliquid64** [comment]
@samyak-jain unfortunately not, its a super duper edge-casey font and most of the ecosystem is working to get the foundations right before tackling that kind of thing

**Comment by hecrj** [comment]
@samyak-jain Yes, this should be a part of #33!

**Comment by GyulyVGC** [comment]
> I just end up getting a blank screen. However, if I switch out with any other font which supports this character, it renders properly.

May I ask you which font to support emoji did you use to render it properly? @samyak-jain 

Thanks in advance.
