### ISSUE TITLE
SVG rasterization cache appears not to be working in all cases

### ISSUE THREAD

**Issue by fastotp** [iced-rs/iced#735]
Using Iced revision `2f10a1f2a2c92aada5d167d82e008588256b590f` (HEAD master at time of writing)

Testing my  application https://gitlab.com/fastotp1/fastotp found that after a while it would crash with no memory available panic error. After debugging found that if I put: `println!("Cache miss");` right after `wgpu/src/image/vector.rs:90`, it would keep printing it, thus no caching it seems.

If I add `let key = (id, width, height);` right after `wgpu/src/image/vector.rs:79`, and replace all occurrences of `(id, width, height)` inside the function with `key`, it shows `"Cache miss"` only one time.

Tried to replicate with SVG example to avoid reporting using my application but I was unable to replicate. I don't know if this is a bug but if yes I can create a pull request with fix.

**Comment by hecrj** [comment]
I believe this should be fixed by #952. Reopen otherwise!
