### ISSUE TITLE
Windows 7 - GraphicsAdapterNotFound

### ISSUE THREAD

**Issue by rnd-ash** [iced-rs/iced#736]
This is being discussed on my applications repository:
https://github.com/rnd-ash/OpenVehicleDiag/issues/11

It appears the users PC has full Dx11 support (Sandy bridge Pentium) yet he still sees the error.

Any help appreciated

**Comment by hecrj** [comment]
I believe the DX11 backend of `wgpu` still has some rough edges (see [the supported platforms table](https://github.com/gfx-rs/wgpu#supported-platforms)).
