### ISSUE TITLE
run/build integration example for wasm

### ISSUE THREAD

**Issue by whiterabbit42k** [iced-rs/iced#740]
I'm not sure how to build iced when using it in "integration" mode, e.g., similar to how the integration example works.

There's a number of problems just when targetting e.g., `wasm32-unknown-unknown`, mostly related to deps using `memmap2`, which are as i understand it:

1. fontdb (optional)
2. usvg (optional)
3. smithay-client-toolkit (required)

so i think smithay-client-toolkit is the failing link here, at least from compile perspective.

Assuming these issues can be resolved, is there any other guidelines for how to accomplish this? it seems a reasonable usecase, since wgpu itself can target wasm32 without much issue?

**Comment by hecrj** [comment]
The `integration` example does not run on web, as it uses `iced_native` directly and not `iced_web`.

The [`ECOSYSTEM` guide](https://github.com/hecrj/iced/blob/master/ECOSYSTEM.md) may be helpful to understand how everything is tied together.

**Comment by whiterabbit42k** [comment]
yes but wgpu can target web (i'm suggesting what does a user do if they want to target `wasm32-unknown-unknown` for e.g., the experimental webgpu web api for wgpu and also used iced?). as i can see the list i gave above are the current blockers for why iced won't even compile with that target when using iced_native.

do you see what i mean?

basically if using iced native and targeting wasm32, this should be possible

**Comment by hecrj** [comment]
Fixed by #1096!
