### ISSUE TITLE
How can I flex a collection of elements to be the same width/fill remaining space?

### ISSUE THREAD

**Issue by WilliamVenner** [iced-rs/iced#746]
How could I flex these buttons to fill the remaining space (designated by the red square)?

## Code

```rust
Container::new(Column::new()

    .push(

        Container::new(Column::new()
        .align_items(Align::Center)
        .width(Length::Shrink)

        .push(
            Image::new(image::Handle::from_memory(include_bytes!("../assets/gmpublisher.png").to_vec()))
            .width(Length::Units(128))
        )

        .push(
            Text::new(format!("gmpublisher v{} by Billy", env!("CARGO_PKG_VERSION")))
            .horizontal_alignment(HorizontalAlignment::Center)
            .color(Color::WHITE)
        )

        .push(
            Landing::button(star_btn, "Star on GitHub")
            .on_press(Message::GitHubStar)
        )

        .push(
            Landing::button(new_addon_btn, "New Addon")
            .on_press(Message::NewAddon)
        )

        .push(
            Landing::button(open_addon_btn, "Open Addon")
            .on_press(Message::OpenAddon)
        )

        .push(
            Landing::button(my_workshop_btn, "My Workshop")
            .on_press(Message::MyWorkshop)
        )

        .push(
            Landing::button(settings_btn, "Settings")
            .on_press(Message::Settings)
        )

        .push(
            Landing::button(help_btn, "Help")
            .on_press(Message::Help)
        )

        .push(
            Landing::button(close_btn, "Close")
            .on_press(Message::Close)
        )

    )
    .width(Length::Fill)
    .height(Length::Fill)
    .center_x()
    .center_y()

    )

    .push(
        Column::new()
        .align_items(Align::Center)
        .width(Length::Fill)

        .push(
            Text::new(
                match &app_vars.gmod {
                    Some(gmod) => gmod.to_string_lossy().to_string(),
                    None => String::from("Garry's Mod installation directory not found! Add it in Settings.")
                }
            )
            .horizontal_alignment(HorizontalAlignment::Center)
            .color(Color::WHITE)
        )

    )

)

.width(Length::Fill)
.height(Length::Fill)
.center_x()
.center_y()
.padding(20).into()
```

## Result

![image](https://user-images.githubusercontent.com/14863743/108942919-bb315b00-764f-11eb-92c5-7d522725c919.png)

**Comment by Kaiden42** [comment]
Have you tried to set the width of the buttons to `Length::Fill`?
```Rust
Button::new(&mut state, "Press Me!").width(Length::Fill)
```

**Comment by WilliamVenner** [comment]
Yes, this causes them to fill the width of the entire window.

**Comment by hangleang** [comment]
Just wrap all those buttons in a button group (Container) and give the container a specified width, then set all buttons width to **Length::Fill**.

**Comment by WilliamVenner** [comment]
I don't want to specify a fixed width.

In HTML/CSS you can just do this:

```html
<style>
    #container {
        display: flex;
    }
    #container .btn {
        flex: 1;
    }
</style>
<div id="container">
    <div class="btn">...</div>
    <div class="btn">...</div>
    <div class="btn">...</div>
    ...
</div>
```

No need to specify any widths. The `.btn`s will just fill the remaining space in their `#container`.

Druid is capable of this, which apparently the flex component of iced is inspired by: https://github.com/linebender/druid/issues/1608#issuecomment-784461421

**Comment by ruza-net** [comment]
Is the fix of this particularly hard? Can I perhaps contribute in any way (I haven't yet looked at the inner workings of iced)?

I'm doing a school project with iced which depends on this functionality, and I need to know if this has potential to land in time, or if I'm better off migrating to druid.

**Comment by ruza-net** [comment]
Is the fix of this particularly hard? Can I perhaps contribute in any way (I haven't yet looked at the inner workings of iced)?

I'm doing a school project with iced which depends on this functionality, and I need to know if this has potential to land in time, or if I'm better off migrating to druid.

**Comment by WilliamVenner** [comment]
You might be better off with using [Tauri](https://tauri.studio), I found the data model of Druid very complex and the documentation is very poor. I don't think we're GUI yet, at least for a full blown application.

**Comment by Surferlul** [comment]
How do you fix this, now that https://github.com/iced-rs/iced/pull/1735 has reverted https://github.com/iced-rs/iced/pull/1044?
