### ISSUE TITLE
Transparent on latest master is black

### ISSUE THREAD

**Issue by TimUntersberger** [iced-rs/iced#756]
Setting the background color of the application to transparent like this:

```rust
fn background_color(&self) -> Color {
  Color::TRANSPARENT
}
```

works on `v0.2.0` but not on latest master. Instead it displays black.

**Comment by TimUntersberger** [comment]
I am using the native renderer on Windows 10

**Comment by dppo** [comment]
macOS Big Sur is also.
window is set transparent:true 
`
    fn background_color(&self) -> Color {
        Color::from_rgba(0.11, 0.42, 0.87, 0.3)
    }
`
alpha color does not take effect.

**Comment by hecrj** [comment]
Duplicate of #596.
