### ISSUE TITLE
Performance difference of scrollable is immense between debug and release executable

### ISSUE THREAD

**Issue by GiulianoCTRL** [iced-rs/iced#783]
Hi,

first off, thanks for the amazing crate, I enjoy working with it.

I was playing around with the scrollable widget and one of my [requests](http://data.riksdagen.se/dokument/sfs-1998-899) filled it with quite some text (200k+ characters ). The debug build was almost unusable on both my Mac (M1, 16GB) and my workstation (Arch Linux, i7-8700K, 32GB), but the release build was running as smooth as it possibly can be.

This is reproducible simply by replacing the string in the "scrollable" example with a huge string and running it once with ````cargo run --release --package scrollable```` and then with ````cargo run --package scrollable````.

I guess this issue is somewhat related to https://github.com/hecrj/iced/pull/584, but I just wanted to inform about this behaviour and wanted to know if there is anything one can currently do to mitigate the issue.

**Comment by 13r0ck** [comment]
Same is true with the [game of life example](https://github.com/hecrj/iced/tree/master/examples/game_of_life). As far as I am aware nothing can be done now to fix the issue. I'm assuming it has to do with the Iced text rendering. There are already plans to rebuild that. 

If you need the scrollable to be long while developing use 
`[cfg(debug_assertions)]` to fill the scrollable with an empty `Column::new().height(Length::Units('height you want'))` and the `Text` when using a release compile

**Comment by hecrj** [comment]
The main issue here is that Rust is quite slow in `debug` mode.

There is also the fact that `Text` widgets do not try to render only the visible text inside the viewport. They simply rasterize, layout, and draw absolutely everything all the time.

I believe using the `iced_glow` backend may improve `debug` performance, but probably not in this case.

**Comment by hecrj** [comment]
Closing this in favor of #897.
