### ISSUE TITLE
Linux + Xorg - Strange scaling issue which makes app unusable!

### ISSUE THREAD

**Issue by rnd-ash** [iced-rs/iced#793]
Using Iced 0.2.0.

My system is a Razer blade 2018, with an integrated 15.6" 1920x1080 display, and I have attached to that a 1920x1080 external monitor. Both are set to 96dpi.

The issue is that my application seems to suddenly scale up 1.5x whenever running on the internal laptop monitor. There is no setting to control this, but it always happens when my application window is open on the laptop display.

This also occurs if the laptop is unplugged from any external monitor, which (See in the video), makes the window unusable, since 30% of the window exceeds the bounds of the monitor.

In the video, I am capturing both displays. The left display is the laptop monitor, and the Right display is the external monitor.
https://user-images.githubusercontent.com/14551965/112340844-dcba4c80-8cb8-11eb-850f-6aefce5263c0.mp4

However, this does not seem to occur under Wayland, just when running on Xorg!

**Comment by dearkarm** [comment]
Hi rnd-ash,

I am also on Linux but on Gnome with wayland. Two monitors (laptop + 40" external). I noticed a similar behavior to what you are showing, but with many programs, not just Iced. What I usually do is I move the window to the desired screen and double click on the title bar so that the program maximizes. That usually helps.

I know my answer is not Iced specific, but maybe it would help to narrow down the source of the issue.

**Comment by hecrj** [comment]
I believe this is caused by [`winit`](https://github.com/rust-windowing/winit) trying to keep the same logical size of the window when there is a DPI scale factor change.

Maybe we should report the issue there?

**Comment by rnd-ash** [comment]
Maybe...

But what I find odd is that if I just have my laptop monitor, and start an iced app, it instantly applies an odd scaling factor, meaning a 1366x768 app window becomes larger than my entire display as soon as the app launches!

This doesn't happen under Wayland though...

**Comment by hecrj** [comment]
Is this issue still present in the latest `master`?

**Comment by LunarEclipse363** [comment]
I have the same issue on X11 with various monitor configurations (single/double). In my case it happens in Veloren's launcher - Airshipper ([Binary Download](https://veloren.net/download/)) ([Source Code](https://gitlab.com/veloren/airshipper/)).

I'm running Arch Linux, using AwesomeWM with Picom as the compositor, I have a Ryzen 7 4800H with integrated graphics.

**Comment by kprasadvnsi** [comment]
I am having a similar issue on my SBC connected to an external monitor running Arch Linux with XFCE desktop. The Iced Application show up 1.5x scaled.
