### ISSUE TITLE
High memory since 0.3

### ISSUE THREAD

**Issue by casperstorm** [iced-rs/iced#820]
Since updating [Ajour ](https://github.com/ajour/ajour)to iced 0.3, we have noticed very high memory on especially Windows.

|          | Windows | MacOS |
|----------|---------|-------|
| iced 0.3 | ~195mb  | ~90mb |
| iced 0.2 | ~70mb   | ~70mb |

Here's a picture of Windows running Ajour with both 0.2 and 0.3, both builds built in release mode.

![iced](https://user-images.githubusercontent.com/2248455/114043443-93582880-9886-11eb-8bc1-0213aff95b18.PNG)

It should be quite easy testable
[master](https://github.com/ajour/ajour/tree/master) runs 0.2 and [development](https://github.com/ajour/ajour/tree/development) runs 0.3.

**Comment by tarkah** [comment]
Can confirm same issue here on windows.

The issue isn't present on Linux, pre /post the 0.3 commit its at ~112mb on my machine.

**Comment by Ssaely** [comment]
There's a post in the [Zulip](https://iced.zulipchat.com/#narrow/stream/213316-general/topic/.60wgpu.60.20upgrade/near/208728504) about this.  Memory usage has increased noticeably ever since upgrading the `wgpu` dependency to `0.6`, and `0.7` made it even worse.  The `glow` renderer is fine, so something is up on the `wgpu` side of things.

**Comment by tarkah** [comment]
@Ssaely Thanks for the heads up on that.

I wish I knew more about profiling on windows to help figure out what's causing this. We have some really cool features dependent on 0.3, but we're hesitant to roll this out when memory usage ships 3x and one of our selling points is performance :P

**Comment by hecrj** [comment]
Probably related to #786.

**Comment by Dispersia** [comment]
that's awesome ajour uses iced, didn't know that, absolutely love Ajour so thanks for your team :). On this issue, I tried the fix that helped the #786 example, but it didn't change anything here. Going to try and take a look, was hoping 0.8 would have helped also but it didn't, so it's probably some niche usage of wgpu

**Comment by Dispersia** [comment]
created issue: https://github.com/gfx-rs/wgpu/issues/1407

**Comment by wellitecho** [comment]
Running the simple "Hello World" example [from the Application trait](https://docs.rs/iced/0.3.0/iced/trait.Application.html) is eating 180 Mb ram on my Win10 ...
