### ISSUE TITLE
OpenGL backend does not support images

### ISSUE THREAD

**Issue by MCOfficer** [iced-rs/iced#846]
As per #354:

> The OpenGL renderer still does not support the Image and Svg widgets, but I believe we can tackle that in another PR.

Also in that PR's discussion:

> Are there any estimates on how hard it is to implement image support for OpenGL renderer ?

> hecrj on 8 Jul 2020:
>
> It shouldn't be hard to get a similar implementation to the iced_wgpu one.
> However, we should try to abstract and move the atlas logic to iced_graphics instead of duplicating code. Additionally, it would be great to set the foundations for asynchronous loading of images at the same time. This is the hard part.

It's not ideal that I'm creating this tracking issue, but imo it's better than not having a tracking issue at all.

**Comment by JoshStrobl** [comment]
Just chiming in here. I wanted to evaluate iced as an alternative to GTK4 when porting over my [GTK4+C Linux audio manager](https://github.com/joshstrobl/Koto) to Rust. This backend makes heavy use of iconography for "normal" UX elements, for example various buttons for playback. The lack of support for images on the OpenGL backend is of considerable impact, as unfortunately I can't rely on the end user having hardware supported by wgpu. **I fully understand that iced is experimental** and **not remotely** comparable to something like GTK4 at this time, however my _hope_ is that this will be treated with some priority for resolution before the grand 1.0 release.

**Comment by MCOfficer** [comment]
Just in case this helps your or anyone else: If you don't load images dynamically, i.e. they are known to you at compile/development time, you might be able to work around it using vector graphics. Specifically, one of my projects uses font characters for iconography, which works perfectly and is more painless because they are vector graphics (no scaling issues). You can also use the `Svg` widget for the same purpose.

**Comment by hecrj** [comment]
Closing this in favor of #674.
