### ISSUE TITLE
how is cursor_position supposed to work with touch?

### ISSUE THREAD

**Issue by aentity** [iced-rs/iced#871]
I have hit issue where on touch only device, the cursor_position is set to 0,0 (it is not updated in winit event handling code, for example).

this appears cause issues inside iced, making it ignore or drop touches, on for example, buttons. In fact, i can see the touch events in my event collection, and i pass them to `user_interface.update()` (https://docs.rs/iced_native/0.4.0/iced_native/struct.UserInterface.html#method.update) but it seems that simulated cursor_position is required? i thought that touch would not need such a thing (since it doesn't exist)

what is recommended way to deal with cursor_position passed to:
```rust
user_interface.update(&events, cursor_position, ...)
```

when making integration based (wgpu) iced programs?

**Comment by aentity** [comment]
so i've spent some time to simulate a cursor_position, and it seems to be correct, but i still do not receive messages sent to buttons on ios device. is there something i am missing? has iced been tested on ios?

so for example, this code never prints messages, but prints on a touchscreen laptop when i tap the button:

```rust
let size = Size::new(logical_size.width, logical_size.height);
let mut user_interface = UserInterface::build(
    sandbox.view(),
    size,
    self.cache.take().unwrap(),
    &mut self.renderer,
);

let mut messages = Vec::new();
let _statuses = user_interface.update(
    &self.events,
    cursor_position,
    &self.renderer,
    &mut self.clipboard as _,
    &mut messages,
);
self.events.clear();

let mut user_interface = if messages.is_empty() {
    user_interface
} else {
    self.cache = Some(user_interface.into_cache());
    for message in messages.drain(..) {
        println!("Iced got message: {:?}", message);
        sandbox.update(message);
    }
```

**Comment by hecrj** [comment]
Is there any reason the current touch events do not work? See #57.

I'm not completely sure what the issue is here. Please, feel free to reopen with an SSCCE!
