### ISSUE TITLE
Column doesn't show last entry

### ISSUE THREAD

**Issue by Orchaldir** [iced-rs/iced#911]
I want to use a column to split my window in 3 parts:

- toolbar
- main
- status bar

https://github.com/Orchaldir/texture_generator/commit/aafdaf6890376446a773f7cdfbb9e488cd949dbc

But the status bar isn't shown. If I move the status bar before main, I can see it.

**Comment by 13r0ck** [comment]
Why are you pushing the status_bar text inside of a row? Just push the text itself. If that doesn't work then try putting the text into a `Container`

**Comment by Orchaldir** [comment]
My plan was to have a row of things in the status bar, but I had problems with the 1.test. The other 2 options don't work too.

```
let status_bar = Container::new(Text::new(format!(
            "{} x {} tiles",
            size.width(),
            size.height()
        )));
```

```
let status_bar = Text::new(format!(
            "{} x {} tiles",
            size.width(),
            size.height()
        ));
```

**Comment by 13r0ck** [comment]
Can you add some screenshots please?

**Comment by Orchaldir** [comment]
![no-status-bar](https://user-images.githubusercontent.com/63156/121963051-df818680-cd69-11eb-8763-d3cf864cfc03.PNG)

**Comment by Orchaldir** [comment]
I just had an idea and tested something. It works correctly with image::Viewer instead of my custom widget.

**Comment by Orchaldir** [comment]
So I found that problem, but I am not sure if it is a bug in Iced or if I missundertand something.

No status bar:

```
fn layout(&self, _renderer: &Renderer, limits: &Limits) -> Node {
     let mut size = limits.max();
     Node::new(size)
}
```

Working status bar:

```
fn layout(&self, _renderer: &Renderer, limits: &Limits) -> Node {
     let mut size = limits.max();
     size.height -= 20.0;
     Node::new(size)
}
```

Does my widget need to know how much space the other elements below it in the column need? That does sound strange.

**Comment by 13r0ck** [comment]
I believe so yes, I do know that Iced native widgets have a step that calculates sizes of widgets, so I assume custom widgets need to do the same.

**Comment by hecrj** [comment]
If the layout strategy of your custom widget is to fill all the available space in the Y axis, make sure that `Widget::height` returns `Length::Fill`.

That way, the layout engine will defer layout computation for your widget until the other non-fill elements have been placed.
