### ISSUE TITLE
What features does wgpu support that glow doesn't?

### ISSUE THREAD

**Issue by dumrich** [iced-rs/iced#935]
I was compiling through some of the examples, and I noticed that some of them, mainly the ones with a canvas and images didn't work with the glow feature enabled. Is there a workaround for this, or a plan to allow this in the future?

**Comment by dumrich** [comment]
Okay, thank you!

**Comment by dumrich** [comment]
@13r0ck I saw the [CryptoWatch](https://www.reddit.com/r/rust/comments/jey2uh/built_with_iced_rust_cryptowatch_desktop/g9gzizr?utm_source=share&utm_medium=web2x&context=3) Desktop app (that was written in iced) is able to use both Canvas and Images in the application. My GPU doesn't support vulkan, which means they must have been using glow. How were they able to use glow and render these canvas and images?

**Comment by 13r0ck** [comment]
The cryptowatch app isn't open source so I can only speculate, but it is either 

1. They are using WGPU with DX12 
2. Cryptowatch gets features before they are open sourced. ( I believe Hecrj works there), so maybe they have an internal build of the iced glow feature that supports those widgets, and that build hasn't been open sourced yet. 
3. Or its something else entirely that I don't know, and I'm sure Hecrj will correct me 😁

**Comment by Kaiden42** [comment]
There exists a `glow_canvas` feature along with the `canvas` feature. You have to use `glow_canvas` in combination with `glow` to be able to render a canvas in OpenGL. But AFAIK images are not working with `glow`.

**Comment by hecrj** [comment]
@dumrich Cryptowatch Desktop doesn't use any `Image` widget. The "images" you have in mind are probably font icons.

**Comment by madmaxio** [comment]
When you guys say wgpu, it is wgpu working in browser or desktop?

**Comment by 13r0ck** [comment]
Desktop
