### ISSUE TITLE
Panic in wasm when creating several buttons in a row with text inside

### ISSUE THREAD

**Issue by madmaxio** [iced-rs/iced#939]
The code creates some buttons (wasm) and panics:

```
top_panel = top_panel.push(
			Button::new(&mut self.state1, Text::new("12345"))
				.on_press(Message::TopPanelAction("Hello".into()))
		);
		
		top_panel = top_panel.push(
			Button::new(&mut self.state2, Text::new("123456789"))
				.on_press(Message::TopPanelAction("Hello".into()))
		);		
		
		top_panel = top_panel.push(
			Button::new(&mut self.state3, Text::new("12345"))
				.on_press(Message::TopPanelAction("Hello".into()))
		);
```

However this one works:

```
top_panel = top_panel.push(
			Button::new(&mut self.state1, Text::new("12345"))
				.on_press(Message::TopPanelAction("Hello".into()))
		);
		
		top_panel = top_panel.push(
			Button::new(&mut self.state2, Text::new("12345"))
				.on_press(Message::TopPanelAction("Hello".into()))
		);		
		
		top_panel = top_panel.push(
			Button::new(&mut self.state3, Text::new("12345"))
				.on_press(Message::TopPanelAction("Hello".into()))
		);
```

Here is the panic message :

  | __rust_start_panic | @ | sky-app_bg.wasm:0x1f14b0
-- | -- | -- | --
  | rust_panic | @ | sky-app_bg.wasm:0x1eb785
  | std::panicking::rust_panic_with_hook::h03201bc01a0ed891 | @ | sky-app_bg.wasm:0x14b9d8
  | std::panicking::begin_panic_handler::{{closure}}::h29e946ca7f59bf10 | @ | sky-app_bg.wasm:0x178095
  | std::sys_common::backtrace::__rust_end_short_backtrace::h43323731dc0e6815 | @ | sky-app_bg.wasm:0x1e82ba
  | rust_begin_unwind | @ | sky-app_bg.wasm:0x1dda50
  | core::panicking::panic_fmt::hd44f353696296fec | @ | sky-app_bg.wasm:0x1e831e
  | core::panicking::panic::ha58827a77b951c10 | @ | sky-app_bg.wasm:0x1ce46b
  | dodrio::builder::ElementBuilder<bumpalo::collections::vec::Vec<dodrio::node::Listener>,Attributes,Children>::on::h784fb7f6d64bdcf8 | @ | sky-app_bg.wasm:0x9477c
  | <iced_web::widget::button::Button<Message> as iced_web::widget::Widget<Message>>::node::h9234a399231b5d10 | @ | sky-app_bg.wasm:0x53a23
  | <iced_web::widget::row::Row<Message> as iced_web::widget::Widget<Message>>::node::{{closure}}::hcc98a796b0a3a0b2 | @ | sky-app_bg.wasm:0x187f8f
  | core::iter::adapters::map::map_fold::{{closure}}::he0e88621494b360e | @ | sky-app_bg.wasm:0x15a424
  | core::iter::traits::iterator::Iterator::fold::h2e64a5ce84dc8cb4 | @ | sky-app_bg.wasm:0x148734
  | <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h1b67f495ae0a2c44 | @ | sky-app_bg.wasm:0x139612
  | core::iter::traits::iterator::Iterator::for_each::h19b774f310c1afe5 | @ | sky-app_bg.wasm:0x12d322
  | <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend::hdcf2714394553224 | @ | sky-app_bg.wasm:0xdb977
  | <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter::h678ab475e3076522 | @ | sky-app_bg.wasm:0x1364b7
  | <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h395e976ed91adb24 | @ | sky-app_bg.wasm:0x169048
  | <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter::h06d127bfe5412ba2 | @ | sky-app_bg.wasm:0x15e0ba
  | core::iter::traits::iterator::Iterator::collect::hf5251b4bc9e9105b | @ | sky-app_bg.wasm:0x1690e6
  | <iced_web::widget::row::Row<Message> as iced_web::widget::Widget<Message>>::node::h1e1edd1db3cc3567 | @ | sky-app_bg.wasm:0x59029
  | <iced_web::widget::row::Row<Message> as iced_web::widget::Widget<Message>>::node::{{closure}}::hcc98a796b0a3a0b2 | @ | sky-app_bg.wasm:0x187f8f
  | core::iter::adapters::map::map_fold::{{closure}}::he0e88621494b360e | @ | sky-app_bg.wasm:0x15a424
  | core::iter::traits::iterator::Iterator::fold::h2e64a5ce84dc8cb4 | @ | sky-app_bg.wasm:0x148734
  | <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold::h1b67f495ae0a2c44 | @ | sky-app_bg.wasm:0x139612
  | core::iter::traits::iterator::Iterator::for_each::h19b774f310c1afe5 | @ | sky-app_bg.wasm:0x12d322
  | <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend::hdcf2714394553224 | @ | sky-app_bg.wasm:0xdb977
  | <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter::h678ab475e3076522 | @ | sky-app_bg.wasm:0x1364b7
  | <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter::h395e976ed91adb24 | @ | sky-app_bg.wasm:0x169048
  | <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter::h06d127bfe5412ba2 | @ | sky-app_bg.wasm:0x15e0ba
  | core::iter::traits::iterator::Iterator::collect::hf5251b4bc9e9105b | @ | sky-app_bg.wasm:0x1690e6
  | <iced_web::widget::row::Row<Message> as iced_web::widget::Widget<Message>>::node::h1e1edd1db3cc3567 | @ | sky-app_bg.wasm:0x59029
  | <iced_web::Instance<A> as dodrio::render::Render>::render::h249f05ed407dfb6b | @ | sky-app_bg.wasm:0xb2809
  | dodrio::vdom::VdomInnerExclusive::render::ha363792b2c02785a | @ | sky-app_bg.wasm:0x775d6
  | dodrio::vdom::VdomWeak::render::{{closure}}::{{closure}}::{{closure}}::{{closure}}::hf54c4fc6bb8b4201 | @ | sky-app_bg.wasm:0xb5f46
  | dodrio::vdom::with_animation_frame::{{closure}}::h5fabce071476ff52 | @ | sky-app_bg.wasm:0x1375f6
  | <dyn core::ops::function::FnMut<()>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hf5f21d556cdb2e18 | @ | sky-app_bg.wasm:0x162b02
  | __wbg_adapter_27 | @ | sky-app.js:232
  | real | @ | sky-app.js:217
  | requestAnimationFrame (async) |   |  
  | (anonymous) | @ | sky-app.js:368
  | handleError | @ | sky-app.js:241
  | imports.wbg.__wbg_requestAnimationFrame_aa3bab1f9557a4da | @ | sky-app.js:367
  | web_sys::features::gen_Window::Window::request_animation_frame::h418d8c015ef99a2e | @ | sky-app_bg.wasm:0x1276e1
  | dodrio::vdom::request_animation_frame::h00510ca01d059a75 | @ | sky-app_bg.wasm:0x13dede
  | dodrio::vdom::with_animation_frame::h635f561da21c91a7 | @ | sky-app_bg.wasm:0xbe2ba
  | dodrio::vdom::VdomWeak::render::{{closure}}::{{closure}}::{{closure}}::hd613a38e9def4dae | @ | sky-app_bg.wasm:0x1890c5
  | wasm_bindgen::convert::closures::invoke2_mut::hd93a13730f26ba63 | @ | sky-app_bg.wasm:0x141b19
  | __wbg_adapter_93 | @ | sky-app.js:251
  | cb0 | @ | sky-app.js:435
  | imports.wbg.__wbg_new_c143a4f563f78c4e | @ | sky-app.js:440
  | js_sys::Promise::new::h1fcbc9108bb48032 | @ | sky-app_bg.wasm:0x19715b
  | dodrio::vdom::VdomWeak::render::{{closure}}::{{closure}}::h56dea7d2f9a05e86 | @ | sky-app_bg.wasm:0x1ad2c9
  | core::option::Option<T>::unwrap_or_else::h164dac218eae9fe1 | @ | sky-app_bg.wasm:0x15adac
  | dodrio::vdom::VdomWeak::render::{{closure}}::h9d842cae96a5d082 | @ | sky-app_bg.wasm:0xbc96c
  | <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hc05db2451836661e | @ | sky-app_bg.wasm:0x14f474
  | dodrio::vdom::VdomWeak::schedule_render::{{closure}}::h6a80b215740c3ea6 | @ | sky-app_bg.wasm:0xf7717
  | <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h78a57a9e02aaee68 | @ | sky-app_bg.wasm:0x15cb72
  | wasm_bindgen_futures::task::singlethread::Task::run::h89e39a465b570a2b | @ | sky-app_bg.wasm:0xe24be
  | wasm_bindgen_futures::queue::QueueState::run_all::hc4a9257407607ac1 | @ | sky-app_bg.wasm:0xfcbf3
  | wasm_bindgen_futures::queue::Queue::new::{{closure}}::h33ebbfed29610b27 | @ | sky-app_bg.wasm:0x1a3248
  | <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hecf4181350d42092 | @ | sky-app_bg.wasm:0x14c4e6
  | __wbg_adapter_30 | @ | sky-app.js:236
  | real | @ | sky-app.js:217
  | Promise.then (async) |   |  
  | imports.wbg.__wbg_then_c2361a9d5c9a4fcb | @ | sky-app.js:451
  | js_sys::Promise::then::h144ef2a3c8d2d31a | @ | sky-app_bg.wasm:0x19edb7
  | wasm_bindgen_futures::queue::Queue::push_task::h1da1183561e79ee8 | @ | sky-app_bg.wasm:0x11ab5d
  | wasm_bindgen_futures::task::singlethread::Task::wake_by_ref::{{closure}}::h945993dbe1b08bd6 | @ | sky-app_bg.wasm:0x1c454b
  | std::thread::local::LocalKey<T>::try_with::hf9235266b7b37dd0 | @ | sky-app_bg.wasm:0x14adcf
  | std::thread::local::LocalKey<T>::with::hebfbecf3329c8022 | @ | sky-app_bg.wasm:0x19b0c3
  | wasm_bindgen_futures::task::singlethread::Task::wake_by_ref::ha80a85e0fd58f16a | @ | sky-app_bg.wasm:0x15cd49
  | wasm_bindgen_futures::task::singlethread::Task::into_raw_waker::raw_wake::h761b1bbbcf377b1b | @ | sky-app_bg.wasm:0x19ece0
  | core::task::wake::Waker::wake::h48e41e27fc5038eb | @ | sky-app_bg.wasm:0x1b2aef
  | <wasm_bindgen_futures::JsFuture as core::convert::From<js_sys::Promise>>::from::finish::ha37fe6aac8d43352 | @ | sky-app_bg.wasm:0xb63ba
  | <wasm_bindgen_futures::JsFuture as core::convert::From<js_sys::Promise>>::from::{{closure}}::h6c8902a820dc2bf3 | @ | sky-app_bg.wasm:0x18ab5d
  | core::ops::function::FnOnce::call_once::h51417d6e4142bda0 | @ | sky-app_bg.wasm:0x19c909
  | <T as wasm_bindgen::closure::WasmClosureFnOnce<A,R>>::into_fn_mut::{{closure}}::hdd8f09a2dc5f4fc0 | @ | sky-app_bg.wasm:0x199032
  | <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hecf4181350d42092 | @ | sky-app_bg.wasm:0x14c4e6
  | __wbg_adapter_30 | @ | sky-app.js:236
  | real | @ | sky-app.js:217
  | Promise.then (async) |   |  
  | imports.wbg.__wbg_then_6c9a4bf55755f9b8 | @ | sky-app.js:455
  | js_sys::Promise::then2::hdc225078eddeb85b | @ | sky-app_bg.wasm:0x18ac4d
  | <wasm_bindgen_futures::JsFuture as core::convert::From<js_sys::Promise>>::from::h776fb362ab852260 | @ | sky-app_bg.wasm:0x89c79
  | sky_app::fetch_wasm32::rpc::{{closure}}::hb8ca131c4a39c62f | @ | sky-app_bg.wasm:0x26567
  | <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h7ca829ce646f549e | @ | sky-app_bg.wasm:0x12a65c
  | <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::hbc699d2b9fd48425 | @ | sky-app_bg.wasm:0xd521c
  | <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::had2d7e9274d389ca | @ | sky-app_bg.wasm:0x1c9364
  | <core::pin::Pin<P> as core::future::future::Future>::poll::h4800f9e92c3bcb6b | @ | sky-app_bg.wasm:0x16cfcd
  | <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::ha274baf6171172db | @ | sky-app_bg.wasm:0xd5e4e
  | <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::h12939ff8bb8b4f69 | @ | sky-app_bg.wasm:0x1c931e
  | <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll::hb9010218bc122c74 | @ | sky-app_bg.wasm:0xb6ffd
  | <futures_util::future::future::Then<Fut1,Fut2,F> as core::future::future::Future>::poll::h5ba3a64ec3817746 | @ | sky-app_bg.wasm:0x1b329f
  | wasm_bindgen_futures::task::singlethread::Task::run::h89e39a465b570a2b | @ | sky-app_bg.wasm:0xe24be
  | wasm_bindgen_futures::queue::QueueState::run_all::hc4a9257407607ac1 | @ | sky-app_bg.wasm:0xfcbf3
  | wasm_bindgen_futures::queue::Queue::new::{{closure}}::h33ebbfed29610b27 | @ | sky-app_bg.wasm:0x1a3248
  | <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hecf4181350d42092 | @ | sky-app_bg.wasm:0x14c4e6
  | __wbg_adapter_30 | @ | sky-app.js:236
  | real | @ | sky-app.js:217
  | Promise.then (async) |   |  
  | imports.wbg.__wbg_then_c2361a9d5c9a4fcb | @ | sky-app.js:451
  | js_sys::Promise::then::h144ef2a3c8d2d31a | @ | sky-app_bg.wasm:0x19edb7
  | wasm_bindgen_futures::queue::Queue::push_task::h1da1183561e79ee8 | @ | sky-app_bg.wasm:0x11ab5d
  | wasm_bindgen_futures::task::singlethread::Task::wake_by_ref::{{closure}}::h945993dbe1b08bd6 | @ | sky-app_bg.wasm:0x1c454b
  | std::thread::local::LocalKey<T>::try_with::hf9235266b7b37dd0 | @ | sky-app_bg.wasm:0x14adcf
  | std::thread::local::LocalKey<T>::with::hebfbecf3329c8022 | @ | sky-app_bg.wasm:0x19b0c3
  | wasm_bindgen_futures::task::singlethread::Task::wake_by_ref::ha80a85e0fd58f16a | @ | sky-app_bg.wasm:0x15cd49
  | wasm_bindgen_futures::task::singlethread::Task::into_raw_waker::raw_wake::h761b1bbbcf377b1b | @ | sky-app_bg.wasm:0x19ece0
  | core::task::wake::Waker::wake::h48e41e27fc5038eb | @ | sky-app_bg.wasm:0x1b2aef
  | <wasm_bindgen_futures::JsFuture as core::convert::From<js_sys::Promise>>::from::finish::ha37fe6aac8d43352 | @ | sky-app_bg.wasm:0xb63ba
  | <wasm_bindgen_futures::JsFuture as core::convert::From<js_sys::Promise>>::from::{{closure}}::h6c8902a820dc2bf3 | @ | sky-app_bg.wasm:0x18ab5d
  | core::ops::function::FnOnce::call_once::h51417d6e4142bda0 | @ | sky-app_bg.wasm:0x19c909
  | <T as wasm_bindgen::closure::WasmClosureFnOnce<A,R>>::into_fn_mut::{{closure}}::hdd8f09a2dc5f4fc0 | @ | sky-app_bg.wasm:0x199032
  | <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hecf4181350d42092 | @ | sky-app_bg.wasm:0x14c4e6
  | __wbg_adapter_30 | @ | sky-app.js:236
  | real | @ | sky-app.js:217
  | Promise.then (async) |   |  
  | imports.wbg.__wbg_then_6c9a4bf55755f9b8 | @ | sky-app.js:455
  | js_sys::Promise::then2::hdc225078eddeb85b | @ | sky-app_bg.wasm:0x18ac4d
  | <wasm_bindgen_futures::JsFuture as core::convert::From<js_sys::Promise>>::from::h776fb362ab852260 | @ | sky-app_bg.wasm:0x89c79
  | sky_app::fetch_wasm32::rpc::{{closure}}::hb8ca131c4a39c62f | @ | sky-app_bg.wasm:0x2611a
  | <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h7ca829ce646f549e | @ | sky-app_bg.wasm:0x12a65c
  | <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::hbc699d2b9fd48425 | @ | sky-app_bg.wasm:0xd521c
  | <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::had2d7e9274d389ca | @ | sky-app_bg.wasm:0x1c9364
  | <core::pin::Pin<P> as core::future::future::Future>::poll::h4800f9e92c3bcb6b | @ | sky-app_bg.wasm:0x16cfcd
  | <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::ha274baf6171172db | @ | sky-app_bg.wasm:0xd5e4e
  | <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll::h12939ff8bb8b4f69 | @ | sky-app_bg.wasm:0x1c931e
  | <futures_util::future::future::flatten::Flatten<Fut,<Fut as core::future::future::Future>::Output> as core::future::future::Future>::poll::hb9010218bc122c74 | @ | sky-app_bg.wasm:0xb6ffd
  | <futures_util::future::future::Then<Fut1,Fut2,F> as core::future::future::Future>::poll::h5ba3a64ec3817746 | @ | sky-app_bg.wasm:0x1b329f
  | wasm_bindgen_futures::task::singlethread::Task::run::h89e39a465b570a2b | @ | sky-app_bg.wasm:0xe24be
  | wasm_bindgen_futures::queue::QueueState::run_all::hc4a9257407607ac1 | @ | sky-app_bg.wasm:0xfcbf3
  | wasm_bindgen_futures::queue::Queue::new::{{closure}}::h33ebbfed29610b27 | @ | sky-app_bg.wasm:0x1a3248
  | <dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::hecf4181350d42092 | @ | sky-app_bg.wasm:0x14c4e6
  | __wbg_adapter_30 | @ | sky-app.js:236
  | real | @ | sky-app.js:217
  | Promise.then (async) |   |  
  | imports.wbg.__wbg_then_c2361a9d5c9a4fcb | @ | sky-app.js:451
  | js_sys::Promise::then::h144ef2a3c8d2d31a | @ | sky-app_bg.wasm:0x19edb7
  | wasm_bindgen_futures::queue::Queue::push_task::h1da1183561e79ee8 | @ | sky-app_bg.wasm:0x11ab5d
  | wasm_bindgen_futures::task::singlethread::Task::wake_by_ref::{{closure}}::h945993dbe1b08bd6 | @ | sky-app_bg.wasm:0x1c454b
  | std::thread::local::LocalKey<T>::try_with::hf9235266b7b37dd0 | @ | sky-app_bg.wasm:0x14adcf
  | std::thread::local::LocalKey<T>::with::hebfbecf3329c8022 | @ | sky-app_bg.wasm:0x19b0c3
  | wasm_bindgen_futures::task::singlethread::Task::wake_by_ref::ha80a85e0fd58f16a | @ | sky-app_bg.wasm:0x15cd49
  | wasm_bindgen_futures::task::singlethread::Task::spawn::h849114bf26d0eebd | @ | sky-app_bg.wasm:0xbffc0
  | wasm_bindgen_futures::spawn_local::h19e8f91ba41facd8 | @ | sky-app_bg.wasm:0x174af0
  | <iced_futures::executor::wasm_bindgen::WasmBindgen as iced_futures::executor::Executor>::spawn::h1112440d34c2a5d2 | @ | sky-app_bg.wasm:0x1bf7aa
  | <iced::executor::platform::Default as iced_futures::executor::Executor>::spawn::h7cd9e4dc196f2d3b | @ | sky-app_bg.wasm:0x1bd065
  | iced_futures::runtime::Runtime<Hasher,Event,Executor,Sender,Message>::spawn::he6803673ffb79bdf | @ | sky-app_bg.wasm:0xd1013
  | iced_web::Application::run::h52798c166f2229a8 | @ | sky-app_bg.wasm:0x80339
  | iced::application::Application::run::h6f737bb06eb3fcb6 | @ | sky-app_bg.wasm:0x1f0ee6
  | sky_app::main::h00803cebd8afff67 | @ | sky-app_bg.wasm:0x1b21fa
  | core::ops::function::FnOnce::call_once::h4d1dece6040d5d6e | @ | sky-app_bg.wasm:0x1ddf72
  | std::sys_common::backtrace::__rust_begin_short_backtrace::hdc4c8aad37c2893f | @ | sky-app_bg.wasm:0x1d9c07
  | std::rt::lang_start::{{closure}}::h296d310391743c64 | @ | sky-app_bg.wasm:0x1bce8e
  | std::rt::lang_start_internal::hed614352a2361bbf | @ | sky-app_bg.wasm:0x18b0af
  | std::rt::lang_start::h02141b6eefba791f | @ | sky-app_bg.wasm:0x1a6926
  | main | @ | sky-app_bg.wasm:0x1f0b31
  | __wbindgen_start | @ | sky-app_bg.wasm:0x1f11e0
  | init | @ | sky-app.js:561
  | async function (async) |   |  
  | init

</span></div>
</body>
</html>

**Comment by 13r0ck** [comment]
Note, rather than typing `top_panel = top_panel.push();`

You can just chain the push several times `top_panel=Row::new().push().push()` etc.

**Comment by 13r0ck** [comment]
Do you have the same issue if you move them into a `vec` then use `row::with_children()`?

**Comment by madmaxio** [comment]
Well, you can't pass buttons to with_children:

^ expected struct `iced::Element`, found struct `iced::Button`
    |
    = note: expected struct `iced::Element<'_, _>`
               found struct `iced::Button<'_, Message>`

**Comment by 13r0ck** [comment]
There might be something wrong with your `with_children` code. As I have [used it with buttons before](https://github.com/GCI-Global/bathtub/blob/8010934fac2a564dfe66d5b05652bb57a192a233/src/build.rs#L368)

**Comment by madmaxio** [comment]
Perhaps you used not the latest version of code?

Function signature is pretty clear and accepts Vec<Element<'a, Message, Renderer>>:

/// Creates a [`Row`] with the given elements.
    pub fn with_children(
        children: Vec<Element<'a, Message, Renderer>>,
    ) -> Self

**Comment by hecrj** [comment]
You should be able to call `into` for any `Widget` to turn it into an `Element`.

**Comment by madmaxio** [comment]
Ah. Build it, same issue happened. Same panic when using with_children.

**Comment by madmaxio** [comment]
Can be workarounded with Container, and most likely will be fixed with dodrio replacement.
