### ISSUE TITLE
Download progress example doesn't compile.

### ISSUE THREAD

**Issue by Kesanov** [iced-rs/iced#985]
The error I am getting is:
```rust
error[E0277]: the trait bound `Download: iced_futures::subscription::Recipe<iced_native::hasher::Hasher, (iced_native::event::Event, iced_native::event::Status)>` is not satisfied
 --> src\download.rs:5:37
  |
5 |     iced::Subscription::from_recipe(Download { url: url.to_string(), })
  |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `iced_futures::subscription::Recipe<iced_native::hasher::Hasher, (iced_native::event::Event, iced_native::event::Status)>` is not implemented for `Download`
  |
  = note: required by `Subscription::<H, E, O>::from_recipe`
```

**Comment by hecrj** [comment]
Could you describe the steps to reproduce? OS, Rust version...

**Comment by Josef-Vonasek** [comment]
Windows, latest rust. The problem is that trait implemented is `iced_native::subscription::Recipe` instead of `iced_futures::subscription::Recipe`.

**Comment by hecrj** [comment]
I cannot seem to reproduce.

We use GitHub CI to compile all of our examples in [our `test` workflow](https://github.com/hecrj/iced/runs/3249877398?check_suite_focus=true) every time there is a change in the codebase. All the tests are passing.

**Comment by tarkah** [comment]
@Josef-Vonasek Can you run a `cargo update` and a `cargo clean` and see if that resolves the issue?

**Comment by Josef-Vonasek** [comment]
@tarkah Didn't help. @hecrj What are your dependencies? Mine are 
```toml
[dependencies]
iced = { version = "0.3.0", features = ["tokio"] }
iced_native = "0.3.0"
iced_futures = "0.3.0"
reqwest = "0.11"
```

**Comment by hecrj** [comment]
@Kesanov You are using the code of `download_progress` in the `master` branch of the repository and trying to compile it with the latest `0.3` release.

This won't always work, as the `README` points out:

> __Iced moves fast and the `master` branch can contain breaking changes!__ If you want to learn about a specific release, check out [the release list].

If you want to rely on `0.3`, check the repository and the examples using [the `0.3.0` tag instead](https://github.com/hecrj/iced/tree/0.3.0).
