### ISSUE TITLE
Any plans to support components?

### ISSUE THREAD

**Issue by tema3210** [iced-rs/iced#995]
Just an idea of doing API for components: [API](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=41a88313146f4594e4f5e85f5c233d1c)

The benefits of providing that API is that we might want to allow user defined components as well as see them defined in other crates.

Note: GAT for `Message` is used to leave opportunities for GADTs use for messages. Hope that they will be eventually added.

Unresolved question is do we really need to go with both `State` and `View` associated types?

**Comment by cryptoquick** [comment]
What do you mean by "components" ? Are you referring to what was discussed in #648, or are you referring to a widget library, like https://github.com/iced-rs/iced_aw ?

**Comment by tema3210** [comment]
> 
> 
> What do you mean by "components" ? Are you referring to what was discussed in #648, or are you referring to a widget library, like https://github.com/iced-rs/iced_aw ?

The first, I've tried to build an example client for my study project and my `Message` type was like 15 variants, so I tried to build an initial version of components API, on top of iced. It worked well, but I had no way to typecheck messages that went "upper", to a holder of a widget.

**Comment by hecrj** [comment]
I recently introduced a `Component` trait that allows users to use the Elm Architecture for implementing custom widgets in #1131.

However, my previous comment still stands! You should rarely use this trait! Mainly, it should only be used to implement very "internally state-heavy" custom widgets.
