### ISSUE TITLE
Creating a window that doesn't block the current thread

### ISSUE THREAD

**Issue by TimUntersberger** [iced-rs/iced#996]
I currently am trying to integrate iced into one of my own projects which requires the window event loop to be in a seperate thread, so I can continue using the main thread.

When I try to put the `run` call inside a new thread I get the following panic:

```
Initializing the event loop outside of the main thread is a significant cross-platform compatibility hazard. 
If you really, absolutely need to create an EventLoop on a different thread, please use the `EventLoopExtWindows::new_any_thread` function
```

It looks like winit expects `EventLoop::new` to be called on the main thread.

Any suggestions?

**Comment by PolyMeilex** [comment]
On MacOS all UI calls have to be done on main thread, that's probably one of main reasons for this check

**Comment by TimUntersberger** [comment]
@PolyMeilex how would you usually do this on macos?

**Comment by AndiHofi** [comment]
I see the following options for this:
1.  change your main logic to run in on another thread and have the UI on the main thread. With iced that is a bit of a problem, as closing the main application ends the program - overriding Application::mode() to return Mode::Hidden can help there
2. Put the UI in it's own executable and communicate over IPC. I tend to use this option to improve my productivity, by keeping compile times low.

**Comment by hecrj** [comment]
Since #1112, `Application::run` now returns control to the main thread when the `Application` exits (e.g. window is closed or `should_exit` returns `true`).

Therefore, I believe this use case should be satisfied. Feel free to reopen otherwise!
